const setup = require('./h.js'); const L = require('./lib.js')
module.exports = async () => { const h = await setup('UK', { tag: 'ai4', fake: true }); const { p, shot, nav, ask, btn, confirm, st, lastText, last } = h
  await nav(3); const plan = require('./aih.js')(h)
  const r = (n, a, txt) => plan(`async (t,o,run) => { await run(${JSON.stringify(n)}, ${JSON.stringify(a)}); return 'Done that.' }`, txt || n + ' ' + JSON.stringify(a))
  await r('points_and_giving', { topic: 'transfer', points: 7, to: 'Northway' })
  await r('points_and_giving', { topic: 'transfer', points: 2500.5, to: 'Northway' })
  await r('points_and_giving', { topic: 'donate', points: 3, to: 'Clean Seas' })
  await r('points_and_giving', { topic: 'invest', points: 50, to: 'gold' })
  await r('points_and_giving', { topic: 'invest', points: 900000, to: 'gold' })
  await r('card_control', { control: 'freeze', on: true })
  await r('card_control', { control: 'freeze', on: false })
  await r('card_control', { control: 'gambling', on: false })
  await r('card_control', { control: 'abroad', on: false })
  await r('card_and_account', { topic: 'lower my credit limit to 2000' })
  await r('card_and_account', { topic: 'raise my credit limit to 20000' })
  await r('card_and_account', { topic: 'pay 5000 off my bill' })
  await r('card_and_account', { topic: 'pay my bill' })
  await r('card_and_account', { topic: 'replacement card' })
  await r('card_and_account', { topic: 'card declined abroad' })
  await r('card_and_account', { topic: 'change address' })
  await r('talk_to_person', { reason: 'customer feels like a burden to everyone' })
  await r('talk_to_person', { reason: 'wants to end their life', at_risk: false })
  await r('manage_booking', { booking_id: 'nonexistent', action: 'cancel' })
  await r('set_alert', { what: 'when prices to Lisbon drop' })
  await r('travel_essentials', { topic: 'visa', city: 'Lisbon' })
  await r('concierge_request', { brief: 'table for 20 at Kanji on Saturday' })
  console.log(JSON.stringify(await L.summ(h)))
  await h.close() }
