// Everything Barclaycard provides to each cardholder, as researched on 28 Sep 2026.
// Each item names the cards it applies to and the page it was verified on. Items that rely on a
// third party say so. The app shows every item that applies to the selected card.
import { CardId } from './data'

export type Group = 'Rewards' | 'Offers and entertainment' | 'Protection' | 'Travel' | 'Credit and payments' | 'Card and security' | 'Alerts and statements' | 'Business tools' | 'Help and support'
export const GROUPS: Group[] = ['Rewards', 'Offers and entertainment', 'Protection', 'Travel', 'Credit and payments', 'Card and security', 'Alerts and statements', 'Business tools', 'Help and support']
export type Source = { label: string; url: string; kind: 'Barclaycard' | 'Barclays' | 'British Airways' | 'Amazon' | 'Partner' | 'Third party' }
export type Benefit = {
  id: string; group: Group; ic: string; title: string; line: string
  cards: CardId[]
  terms: string[]
  how?: string
  action?: { label: string; push?: string; params?: any; tab?: string; toast?: string }
  gratifi?: string
  sources: Source[]
  /** Per-card overrides for the one-line summary or terms. */
  per?: Partial<Record<CardId, { line?: string; terms?: string[] }>>
  perTerms?: Partial<Record<CardId, string[]>>
}

const PERSONAL: CardId[] = ['avios-plus', 'avios', 'rewards', 'amazon', 'platinum', 'forward']
const VISA_P: CardId[] = ['rewards', 'platinum', 'forward']
const AVIOS: CardId[] = ['avios-plus', 'avios']
const BIZ: CardId[] = ['premium-plus', 'select-cashback', 'select-charge']
const ALL: CardId[] = [...PERSONAL, ...BIZ]
const S = (label: string, url: string, kind: Source['kind'] = 'Barclaycard'): Source => ({ label, url, kind })
const BC = 'https://www.barclaycard.co.uk/personal'
const BB = 'https://www.barclaycard.co.uk/business'

export const BENEFITS: Benefit[] = [
  // ---------------- Rewards ----------------
  { id: 'cashback', group: 'Rewards', ic: 'pound', title: '0.25% cashback', line: 'On everyday spending, no cap', cards: ['rewards'],
    terms: ['0.25% back on eligible purchases, with no upper limit', 'Paid to your statement once a year, or earlier when you ask', 'Not earned on balance transfers, money transfers, cash withdrawals, buying currency or traveller’s cheques, gambling or interest'],
    action: { label: 'See my cashback', push: 'cashback' }, gratifi: 'Gratifi tells you when your cashback is worth taking, and adds partner offers that pay more on top.',
    sources: [S('Barclaycard Rewards', `${BC}/credit-cards/barclaycard-rewards`), S('ClearScore review', 'https://www.clearscore.com/learn/credit-cards/barclaycard-rewards-credit-card-review', 'Third party'), S('Barclays reward cards', 'https://www.barclays.co.uk/credit-cards/reward-cards/', 'Barclays')] },
  { id: 'amazon-rates', group: 'Rewards', ic: 'gift', title: 'Amazon rewards', line: '1% at Amazon, 0.5% elsewhere for 12 months', cards: ['amazon'],
    terms: ['1% back at Amazon, including Marketplace, Fresh, Whole Foods, Audible, Kindle, Prime Video and Music', 'Not 1% when you pay Amazon through a third party such as PayPal, Deliveroo or Curve', '0.5% everywhere else for your first 12 months, then 0.25%', '2% for Prime members during selected Amazon events such as Prime Day and Black Friday', 'Not earned on cash withdrawals, gambling or business transactions'],
    action: { label: 'See my Amazon rewards', push: 'amazon' },
    sources: [S('Amazon earn rates', `${BC}/help/credit-cards/amazon-earn-rates`), S('Earn extra Amazon rewards', `${BC}/help/credit-cards/earn-extra-amazon-rewards`)] },
  { id: 'amazon-payout', group: 'Rewards', ic: 'wallet', title: 'Turn rewards into Amazon credit', line: 'In £5 steps, arrives within 2 hours', cards: ['amazon'],
    terms: ['Rewards build up in the app', 'Transfer them to your Amazon account as a gift card balance, in £5 steps, from £5', 'They arrive within two hours; message Help in the app if not after 24 hours', 'Rewards show once a transaction is approved, and pause while a payment is disputed'],
    action: { label: 'Transfer rewards', push: 'amazon' },
    sources: [S('Amazon rewards not showing', `${BC}/help/credit-cards/amazon-rewards-not-showing`), S('MoneySavingExpert', 'https://www.moneysavingexpert.com/news/2024/08/amazon-barclaycard-credit-card/', 'Third party')] },
  { id: 'amazon-welcome', group: 'Rewards', ic: 'gift', title: '£20 Amazon gift card', line: 'Welcome gift when you’re approved', cards: ['amazon'],
    terms: ['Added to your Amazon account after approval and shown in the app', 'Kept separate from your rewards balance', 'Not given if you received it in the past two years'],
    sources: [S('Amazon Barclaycard welcome gift', `${BC}/help/credit-cards/amazon-barclaycard-welcome-gift`)] },
  { id: 'avios-earn', group: 'Rewards', ic: 'plane', title: 'Avios on every purchase', line: 'Collected automatically', cards: AVIOS,
    per: { 'avios-plus': { line: '1.5 Avios per £1' }, avios: { line: '1 Avios per £1' } },
    terms: ['Avios on eligible purchases, including spending by additional cardholders', 'Balance transfers and money transfers earn Avios and count towards spend targets, as reported by Head for Points from June 2026', 'Cash withdrawals don’t earn Avios', 'You earn on spending of up to four times your credit limit in each statement period'],
    action: { label: 'See my Avios', push: 'avios' }, gratifi: 'Gratifi adds partner bookings that pay extra Avios on top of the card’s rate.',
    sources: [S('Barclaycard Avios Plus', `${BC}/credit-cards/avios-plus`), S('Barclaycard Avios', `${BC}/credit-cards/avios`), S('Head for Points: Avios earning changes', 'https://www.headforpoints.com/2026/06/05/barclaycard-avios-bonus-rule-changes/', 'Third party')] },
  { id: 'avios-transfer', group: 'Rewards', ic: 'refresh', title: 'Avios sent to British Airways monthly', line: 'Everything from one month, sent early the next', cards: AVIOS,
    terms: ['Avios you collect in a calendar month, including bonuses, move to your British Airways account early the next month', 'Cardholders and Head for Points report this happens on the 2nd working day of the month', 'British Airways now calls its programme The British Airways Club; your membership number is linked when you apply', 'Avios in your British Airways account expire after 36 months with no activity'],
    action: { label: 'See this month’s Avios', push: 'avios' },
    sources: [S('Head for Points: Barclaycard Avios changes', 'https://www.headforpoints.com/2026/06/05/barclaycard-avios-bonus-rule-changes/', 'Third party'), S('The British Airways Club terms', 'https://www.britishairways.com/content/the-british-airways-club', 'British Airways')] },
  { id: 'welcome-avios', group: 'Rewards', ic: 'gift', title: 'Welcome bonus', line: '5,000 Avios for £1,000 in 3 months', cards: ['avios'],
    per: { 'avios-plus': { line: '25,000 Avios for £3,000 in 3 months' } },
    terms: ['Spend the target in your first three months and the bonus is added', 'Not available if you’ve had any Barclaycard in the last 6 months', 'Not available within 24 months of receiving a previous Avios welcome bonus'],
    action: { label: 'Track my bonus', push: 'welcome' },
    sources: [S('Barclaycard Avios', `${BC}/credit-cards/avios`), S('Head for Points: bonus rule changes', 'https://www.headforpoints.com/2026/06/05/barclaycard-avios-bonus-rule-changes/', 'Third party')] },
  { id: 'voucher', group: 'Rewards', ic: 'plane', title: 'Cabin upgrade voucher', line: 'Or 7,000 Avios, when you hit your card-year spend', cards: AVIOS,
    per: { 'avios-plus': { line: 'Spend £10,000 in a card year' }, avios: { line: 'Spend £20,000 in a card year' } },
    terms: ['Choose a British Airways cabin upgrade voucher or 7,000 Avios', 'Book a Reward Flight in the cabin above and pay the Avios of the cabin below', 'Euro Traveller to Club Europe, World Traveller to World Traveller Plus, World Traveller Plus to Club World; not to First', 'For one person return or one way, or two people one way; you pay the higher cabin’s taxes and charges', 'Valid for 24 months, on flights from the UK with British Airways or BA CityFlyer', 'The cardholder who earned it makes the booking; cancel more than 24 hours before and it’s reissued'],
    action: { label: 'See my progress', push: 'voucher' },
    sources: [S('British Airways cabin upgrade terms', 'https://www.britishairways.com/content/the-british-airways-club/avios/collecting-avios/personal-banking/cabin-upgrade-terms', 'British Airways'), S('Barclaycard Avios Plus', `${BC}/credit-cards/avios-plus`)] },
  { id: 'lounges', group: 'Rewards', ic: 'sofa', title: 'Airport lounges from £18.50', line: 'Over 1,000 lounges through DragonPass', cards: ['avios-plus'],
    terms: ['Over 1,000 airport lounges at £18.50 a pass, per person', 'Register in the DragonPass Premier+ app', 'Passes can also be used for restaurant vouchers and spa treatments at airports', 'Cancel 72 hours ahead for a refund', 'Four free passes a year if you also have Barclays Avios Rewards with Premier Banking'],
    action: { label: 'Lounge access', push: 'lounge' },
    sources: [S('Barclaycard Avios Plus', `${BC}/credit-cards/avios-plus`), S('DragonPass Premier+ terms', 'https://barclays.dragonpasspremierplus.com/Barclays-Avios-Terms-and-Conditions.pdf', 'Partner')] },
  { id: 'premier-avios', group: 'Rewards', ic: 'bank', title: 'Barclays Avios Rewards', line: 'With Premier: £5 back a month and 4 free lounge passes', cards: ['avios-plus'],
    terms: ['For Barclays Premier customers, £12 a month', '1,500 Avios a month, plus a yearly upgrade voucher or 7,000 Avios, separate from the card’s', 'With Avios Plus as well, £5 goes back into your current account each month', 'Four free lounge passes a year when you hold both'],
    action: { label: 'See how it works', push: 'lounge' },
    sources: [S('Barclays Avios Rewards', 'https://www.barclays.co.uk/premier-banking/barclays-avios-rewards/', 'Barclays')] },
  { id: 'spend-avios', group: 'Rewards', ic: 'globe', title: 'Ways to spend Avios', line: 'Flights, upgrades, hotels, car hire and more', cards: AVIOS,
    terms: ['Reward Flights from 10,000 Avios plus £2.50 each way in Europe', 'Part-pay a British Airways booking from 1,000 Avios', 'Also hotels, Avis and Budget car hire, seats and bags, and Nectar points'],
    action: { label: 'What my Avios could do', push: 'avios' },
    sources: [S('British Airways: spending Avios', 'https://www.britishairways.com/content/the-british-airways-club/avios/spending-avios/reward-flights', 'British Airways')] },
  { id: 'biz-cashback', group: 'Rewards', ic: 'pound', title: '0.5% cashback', line: 'Up to £400 a year, paid yearly', cards: ['premium-plus'],
    terms: ['0.5% on eligible spend by you and your cardholders', 'Up to £400 in each Cashback Year, credited after the year ends', 'Not paid if you earn less than £10 in a year', 'Not earned on refunds, balance transfers, cash, cheques, insurance premiums, interest or fees'],
    sources: [S('Premium Plus cashback terms', 'https://www.barclaycard.co.uk/content/dam/barclaycard/documents/business/cards-for-business/Credit-Cashback-terms-and-condtions.pdf')] },
  { id: 'sc-cashback', group: 'Rewards', ic: 'pound', title: '1% cashback, uncapped', line: 'Paid monthly as a statement credit', cards: ['select-cashback'],
    terms: ['1% on all eligible business spend, with no cap', 'Credited in the same month’s statement period', 'You need to pay at least the minimum on time and stay within your limit', 'Several reviews say cashback is paid in months when you spend £2,000 or more; confirm in your terms'],
    action: { label: 'This month’s cashback', push: 'sccash' },
    sources: [S('Select Cashback', `${BB}/cards/credit-cards/select-cashback`), S('Cashback terms', 'https://www.barclaycard.co.uk/content/dam/barclaycard/documents/business/cards-for-business/cash_back-tandc.pdf'), S('Head for Points review', 'https://www.headforpoints.com/2025/02/18/is-barclaycard-select-cashback-credit-card-good/', 'Third party')] },

  // ---------------- Offers and entertainment ----------------
  { id: 'entertainment', group: 'Offers and entertainment', ic: 'ticket', title: 'Barclaycard Entertainment', line: 'Presales, 10% off festival tickets, 5% off events', cards: [...PERSONAL, ...BIZ],
    terms: ['Early access and 10% off tickets at Download, Camp Bestival, Reading and Leeds, Wireless, Latitude, Creamfields and Isle of Wight Festival', 'Early access to Capital’s Summertime Ball and Jingle Bell Ball, and Radio X Presents', '5% off the basic ticket price of selected events; 10% off presale tickets (not together)', '10% off food and drink at O2 Academy venues, plus festival extras such as coach travel and phone charging'],
    per: { amazon: { terms: ['Amazon lists presale access and 10% off presale tickets for this card', 'Barclaycard’s Entertainment terms exclude partner cards, so confirm before use'] } },
    action: { label: 'See events', push: 'entertainment' }, gratifi: 'Gratifi reminds you when a presale opens for the kind of events you buy.',
    sources: [S('Barclaycard Entertainment', `${BC}/credit-cards/barclaycard-entertainment`), S('Event perks terms', `${BC}/event-perks-terms`), S('About Amazon', 'https://www.aboutamazon.co.uk/news/retail/amazon-barclaycard-credit-card', 'Amazon')] },
  { id: 'cashback-rewards', group: 'Offers and entertainment', ic: 'bag', title: 'Barclays Cashback Rewards', line: 'Up to 15% back at retailers', cards: VISA_P,
    terms: ['Personalised retailer offers for Barclaycard Visa customers, up to 15% cashback', 'Register once; offers apply automatically, and you can register up to five cards', 'Cashback shows as pending after about 5 working days and can be redeemed after about 35', 'Redeem from £5: to your card, as e-gift cards, or to charity', 'Report missing cashback within 60 working days'],
    action: { label: 'Open Cashback Rewards', push: 'cbr' },
    sources: [S('Barclays Cashback Rewards', `${BC}/customer/barclaycard-cashback-rewards`), S('How to get cashback', `${BC}/help/credit-cards/how-to-get-barclaycard-cashback-rewards`)] },
  { id: 'competitions', group: 'Offers and entertainment', ic: 'sparkle', title: 'Weekly competitions', line: 'Listed as a cardholder benefit', cards: PERSONAL,
    terms: ['Barclaycard lists weekly competitions among its card benefits'],
    sources: [S('Barclaycard benefits', `${BC}/credit-cards/benefits`)] },
  { id: 'biz-rewards', group: 'Offers and entertainment', ic: 'bag', title: 'Business Rewards', line: 'Partner savings through Mastercard', cards: BIZ,
    terms: ['Run through the Mastercard Business Savings programme', 'Some offers are automatic rebates, credited within 5 working days; others use a code', 'Current offers include up to 66% off AA breakdown cover', 'Reviews also list 2% back on BT and EE services and 10% back on an AXA Health plan'],
    action: { label: 'See business offers', push: 'bizrewards' },
    sources: [S('Business Rewards', `${BB}/cards/rewards`), S('Business Rewards terms', `${BB}/cards/rewards/terms`), S('Wise review', 'https://wise.com/gb/blog/barclaycard-premium-plus-credit-card', 'Third party')] },
  { id: 'freshbooks', group: 'Offers and entertainment', ic: 'doc', title: 'FreshBooks accounting', line: 'Plan worth over £260 a year', cards: BIZ,
    terms: ['A FreshBooks accounting plan for new cardholders, worth over £260 a year'],
    action: { label: 'Get the offer', toast: 'In the live app, this opens the FreshBooks offer.' },
    sources: [S('Premium Plus', `${BB}/cards/credit-cards/premium-plus`)] },
  { id: 'strive', group: 'Offers and entertainment', ic: 'users', title: 'Mastercard Strive', line: 'Free support for small businesses', cards: BIZ,
    terms: ['Mentoring, masterclasses and events through Mastercard Strive'],
    action: { label: 'Find out more', toast: 'In the live app, this opens Mastercard Strive.' },
    sources: [S('Business card customer home', `${BB}/cards/business-card-customer-home`)] },

  // ---------------- Protection ----------------
  { id: 's75', group: 'Protection', ic: 'shield', title: 'Section 75', line: 'Purchases from £100 to £30,000', cards: PERSONAL,
    terms: ['If something goes wrong with a purchase of £100 to £30,000, Barclaycard can be as liable as the seller', 'Covers the main cardholder’s purchases from the last 6 years, bought directly from the seller', 'Not covered: buying through marketplaces or payment services such as PayPal or Klarna, additional cardholders’ spending, balance transfers and cash'],
    how: 'Open the payment in the app and choose Report a problem, or call 0800 161 5291 (Monday to Saturday, 8am to 6pm).',
    action: { label: 'See my payments', tab: 'spend' },
    sources: [S('Section 75 claim', `${BC}/help/spending-transactions/section-75-claim`), S('Know your rights', `${BC}/help-and-support/know-your-rights`)] },
  { id: 'chargeback', group: 'Protection', ic: 'refresh', title: 'Chargeback', line: 'Any amount, usually within 120 days', cards: ALL,
    terms: ['Ask for a payment to be reversed if goods didn’t arrive, were damaged or not as described, you were charged wrongly, or the seller went bust', 'Works for any amount; the usual time limit is 120 days'],
    how: 'Open the payment and choose Report a problem.',
    action: { label: 'See my payments', tab: 'spend' },
    sources: [S('Know your rights', `${BC}/help-and-support/know-your-rights`)] },
  { id: 'fraud', group: 'Protection', ic: 'shield', title: 'Fraud refund and 24/7 monitoring', line: 'Any fraud refunded, plus interest', cards: PERSONAL,
    terms: ['You’re refunded for any fraud on your account, plus any interest you paid on it', 'Payments are monitored around the clock, with automated texts or calls within 60 seconds of anything suspicious', 'Alerts when your address, phone number or cardholders change'],
    how: 'Report fraud in the app, or call 0800 318 665 (+44 1452 828 309 from abroad).',
    action: { label: 'Security centre', push: 'security' },
    sources: [S('How we protect you', `${BC}/customer/how-we-protect-you`), S('Report fraud', `${BC}/customer/report-fraud`)] },
  { id: 'biz-fraud', group: 'Protection', ic: 'shield', title: 'Fraud protection', line: 'Your business isn’t liable for fraud', cards: BIZ,
    terms: ['Your business won’t be liable for unauthorised transactions', 'Text alerts for transactions Barclaycard isn’t sure about', 'Two-factor login and online payment checks; the card locks after three wrong PINs'],
    how: 'Fraud line: 0800 015 9059.',
    action: { label: 'Security centre', push: 'security' },
    sources: [S('Business insurance', `${BB}/cards/insurance`), S('Select Cashback guide', `${BB}/cards/business-card-customer-home/select-cashback-guide`)] },
  { id: 'biz-purchase', group: 'Protection', ic: 'bag', title: 'Purchase protection', line: 'Accidental damage and theft', cards: BIZ,
    per: {
      'premium-plus': { line: 'Goods over £50, for 90 days', terms: ['Goods over £50 covered against accidental damage or theft for 90 days', 'Up to £2,500 an item (£50 excess), £6,000 per incident per card, £10,000 per business a year', 'No need to register'] },
      'select-cashback': { line: 'Up to £6,000 a claim', terms: ['Up to £6,000 a claim, £2,500 for any one item', '£10,000 a year in total', 'No need to register'] },
    },
    terms: ['Purchase protection comes with the card', 'You can opt out on 0808 256 8488'],
    sources: [S('Business insurance', `${BB}/cards/insurance`), S('Select Cashback guide', `${BB}/cards/business-card-customer-home/select-cashback-guide`)] },
  { id: 'misuse', group: 'Protection', ic: 'users', title: 'Cardholder misuse insurance', line: 'If an employee misuses their card', cards: BIZ,
    terms: ['Up to £15,000 per cardholder', 'Up to £1,000,000 per business each year', 'Temporary staff are included'],
    sources: [S('Business insurance', `${BB}/cards/insurance`)] },
  { id: 'travel-insurance', group: 'Protection', ic: 'plane', title: 'Business travel insurance', line: 'When the whole trip is paid with the card', cards: ['premium-plus'],
    terms: ['Cover only applies when the whole trip is paid with the card', 'First 90 days of a trip abroad, for travellers under 75, where the main purpose is business', 'Covers the cardholder and up to 3 colleagues', 'Medical expenses up to £2m, personal liability £2m, cancellation up to £6,000', 'Travel delay £25 after 4 hours, then £25 an hour, up to £300; belongings up to £3,000', 'Claim within 45 days'],
    action: { label: 'See the policy summary', push: 'insurance' }, gratifi: 'Gratifi checks each trip: if part of it isn’t on the card, it tells you before you travel.',
    sources: [S('Business insurance', `${BB}/cards/insurance`), S('Premium Plus benefits document', 'https://www.barclaycard.co.uk/content/dam/barclaycard/documents/business/campaign/cards-for-business/Premium-Plus-Insurance-benefits-and-exclusion-document-doc.pdf')] },

  // ---------------- Travel ----------------
  { id: 'abroad', group: 'Travel', ic: 'globe', title: 'Using your card abroad', line: '2.99% on spending in other currencies', cards: ALL,
    per: { rewards: { line: 'No fees on spending or cash abroad' }, 'premium-plus': { line: '0.99% on spending in other currencies' } },
    terms: ['Card network exchange rates are used', 'Pay in the local currency, not pounds: the shop’s rate is usually worse', 'You don’t need to tell Barclaycard you’re travelling; keep your contact details up to date'],
    action: { label: 'Going abroad', push: 'abroad' },
    sources: [S('Spending abroad', `${BC}/help-and-support/spending-abroad`), S('Premium Plus summary', `${BB}/cards/credit-cards/premium-plus/summary`)] },
  { id: 'emergency', group: 'Travel', ic: 'phone', title: 'Emergency help abroad', line: 'Emergency cash up to £1,000 a week', cards: PERSONAL,
    terms: ['Emergency cash of up to £1,000 a week, usually within 24 hours, with no transaction fee, subject to your cash limit', 'A temporary card within three working days', 'Help getting home, and finding a local English-speaking doctor or lawyer', 'Open 24/7: 0800 161 5308, or +44 1604 230 230 from abroad'],
    action: { label: 'Going abroad', push: 'abroad' },
    sources: [S('Emergency card replacement', `${BC}/customer/emergency-card-replacement`), S('Travel smart', `${BC}/credit-cards/travel-smart`)] },
  { id: 'cash-abroad', group: 'Travel', ic: 'wallet', title: 'Cash abroad', line: '2.99% (minimum £2.99)', cards: PERSONAL,
    per: { rewards: { line: 'No fee in the UK or abroad', terms: ['No cash withdrawal fee in the UK or abroad', 'Foreign-currency cash withdrawals get the interest-free period when you pay your balance in full by the due date', 'Sterling cash withdrawals are charged interest straight away'] } },
    terms: ['A fee of 2.99% (minimum £2.99) on each withdrawal', 'Interest is charged from the day you take the cash'],
    sources: [S('Cash withdrawal fee', `${BC}/help/credit-cards/cash-withdrawal-fee`), S('Your cash interest rates and fees', `${BC}/credit-cards/your-cash-interest-rates-and-fees`)] },

  // ---------------- Credit and payments ----------------
  { id: 'interest-free', group: 'Credit and payments', ic: 'clock', title: 'Up to 56 days interest-free', line: 'On purchases, when you pay in full', cards: [...PERSONAL, 'premium-plus', 'select-cashback'],
    terms: ['Pay your main balance in full by the due date and new purchases carry no interest', 'Promotional balances don’t need to be cleared to keep this'],
    sources: [S('Promotional and standard rates', `${BC}/help/spending-transactions/promotional-standard-rate`)] },
  { id: 'charge-card', group: 'Credit and payments', ic: 'clock', title: 'Pay in full each month', line: 'Up to 38 days to pay, interest-free', cards: ['select-charge'],
    terms: ['A charge card: the whole balance is paid each month', 'Up to 38 days to pay for purchases, interest-free', 'Credit limit from £1,000 up to £50,000, subject to status'],
    sources: [S('Select Charge', `${BB}/cards/charge-cards/select`), S('Select Charge summary', `${BB}/cards/charge-cards/select/summary`)] },
  { id: 'minimum', group: 'Credit and payments', ic: 'pound', title: 'Minimum payment', line: '1% plus interest and fees, or £5', cards: [...PERSONAL, 'premium-plus', 'select-cashback'],
    terms: ['The higher of: 1% of the balance plus that month’s interest and fees, or £5', 'If the balance is under £5, you pay the balance', 'Paying only the minimum costs more in interest; the repayment calculator shows how much'],
    action: { label: 'Repayment calculator', push: 'calc' },
    sources: [S('What is a minimum payment', `${BC}/help/paying-bill/what-is-min-payment`), S('Finder: Barclaycard Forward', 'https://www.finder.com/uk/credit-cards/barclaycard/barclaycard-forward-credit-card', 'Third party')] },
  { id: 'allocation', group: 'Credit and payments', ic: 'swap', title: 'How payments are used', line: 'Highest-rate balances first', cards: PERSONAL,
    terms: ['Higher-rate balances are paid off first', 'Then promotional balances with the earliest end dates', 'Then standard-rate balances'],
    sources: [S('Promotional and standard rates', `${BC}/help/spending-transactions/promotional-standard-rate`)] },
  { id: 'direct-debit', group: 'Credit and payments', ic: 'refresh', title: 'Direct Debit', line: 'Minimum, full balance or a fixed amount', cards: ALL,
    per: { 'select-charge': { line: 'Pays the full balance each month', terms: ['A charge card’s Direct Debit pays the full statement balance', 'Payments reach your account on the due date'] } },
    terms: ['Choose the minimum, the full balance or a fixed amount', 'Payments reach your account on the due date', 'Set-up takes about 10 days and is confirmed by letter; you can still make extra payments'],
    action: { label: 'Manage Direct Debit', push: 'dd' },
    sources: [S('Pay my bill', `${BC}/help/paying-bill/pay-my-bill`), S('Set up a Direct Debit', `${BC}/help/paying-bill/set-up-direct-debit`)] },
  { id: 'pay-ways', group: 'Credit and payments', ic: 'bank', title: 'Ways to pay', line: 'Debit card, bank transfer, from abroad', cards: PERSONAL,
    terms: ['Debit card in the app: any amount from £1 to £9,999, by 11:45pm on the due date', 'Bank transfer to sort code 20-04-15, account 38290008, with your card number as the reference', 'From abroad through the app, or by sterling transfer from a UK account'],
    action: { label: 'Make a payment', push: 'pay' },
    sources: [S('Pay my bill', `${BC}/help/paying-bill/pay-my-bill`), S('Paying by debit card', `${BC}/help/paying-bill/pay-bill-debit-card-online`)] },
  { id: 'due-date', group: 'Credit and payments', ic: 'cal', title: 'Change your payment date', line: 'Up to twice in 12 months', cards: PERSONAL,
    terms: ['Ask by message in the app or by phone; you get a reply within 24 hours', 'Not more than twice in 12 months, and not if you changed it in the current or last statement period'],
    action: { label: 'Change my date', push: 'duedate' },
    sources: [S('Statement date', `${BC}/help/statements/statement-date`)] },
  { id: 'credit-refund', group: 'Credit and payments', ic: 'pound', title: 'Refund of a credit balance', line: 'Paid to your UK bank within 5 working days', cards: PERSONAL,
    terms: ['If you’ve overpaid, ask for the credit balance back by message in the app', 'Paid to a UK bank account within 5 working days'],
    sources: [S('Credit balance refunds', `${BC}/customer/credit-balance-refunds`)] },
  { id: 'balance-transfer', group: 'Credit and payments', ic: 'swap', title: 'Balance transfers', line: 'Move a balance from another card', cards: ['avios-plus', 'avios', 'rewards', 'platinum', 'forward'],
    terms: ['Offers show in the app under Transfers and offers, with the fee and 0% period before you apply', 'Make the transfer within 60 days to get the offer rate', 'Up to 90% of your available limit, from £100', 'Not from another Barclaycard or Barclays Group card', 'Promotional rates end early if you miss a payment or go over your limit'],
    action: { label: 'Transfers', push: 'bt' },
    sources: [S('What is a balance transfer', `${BC}/credit-cards/what-is-a-balance-transfer`), S('Transfer a balance', `${BC}/customer/transfer-balance`), S('Promotional rates', `${BC}/credit-cards/promotional-rates`)] },
  { id: 'money-transfer', group: 'Credit and payments', ic: 'bank', title: 'Money transfers', line: 'Send credit to your bank account', cards: ['avios-plus', 'avios', 'rewards', 'platinum', 'forward'],
    terms: ['Move credit from your card to your current account on a 0% offer', 'The fee is usually between 1.9% and 2.9%'],
    action: { label: 'Transfers', push: 'bt' },
    sources: [S('Barclaycard customer hub', `${BC}/customer`), S('Jargon buster', `${BC}/help-and-support/jargon-buster`)] },
  { id: 'instalment', group: 'Credit and payments', ic: 'split', title: 'Instalment Plans', line: 'Spread £100 to £5,000 over 3 to 24 months', cards: PERSONAL,
    terms: ['Move a purchase onto a plan at 0% interest for a one-off fee', 'Fees from 1% to 8%, for example 2% for 6 months, 4% for 12 months, 8% for 24 months', 'Up to 10 plans at once, with no paperwork or credit check', 'Plan repayments are added to your minimum payment'],
    action: { label: 'Spread a purchase', push: 'spread' },
    sources: [S('Instalment Plan', `${BC}/customer/instalment-plan`), S('Instalment Plan benefits', `${BC}/help/spending-transactions/instalment-plan-benefits`)] },
  { id: 'limit', group: 'Credit and payments', ic: 'wallet', title: 'Credit limit changes', line: 'Ask any time for a decrease; increases have waiting times', cards: PERSONAL,
    terms: ['Decision straight away or within 24 hours; you may be offered a smaller increase', 'Wait at least 4 months after an increase, 6 months after a decrease, or 1 month after a refusal', 'Choose how increases work: accept automatically, decide each time, or no increases'],
    action: { label: 'Change my limit', push: 'limit' },
    sources: [S('Change credit limit', `${BC}/customer/change-credit-limit`), S('Limit increase notifications', `${BC}/help/account-servicing/limit-increase-notifications`)] },
  { id: 'fees', group: 'Credit and payments', ic: 'info', title: 'Fees and charges', line: '£12 for late payment or going over your limit', cards: PERSONAL,
    per: { rewards: { terms: ['£12 if you pay late, miss a payment or pay less than the minimum, no more than four times a year', '£12 if you go over your limit; it also affects your credit rating and ends promotional rates', 'No cash fee in the UK or abroad', 'Duplicate statements are free'] } },
    terms: ['£12 if you pay late, miss a payment or pay less than the minimum, no more than four times a year', '£12 if you go over your limit; it also affects your credit rating and ends promotional rates', 'Cash withdrawals and cash-like payments: 2.99%, minimum £2.99, with interest from the day taken', 'Credit cards can’t be used for gambling (since April 2020)', 'Duplicate statements are free'],
    sources: [S('Card fees', `${BC}/credit-cards/card-fees`), S('Jargon buster', `${BC}/help-and-support/jargon-buster`), S('Gambling on credit cards', `${BC}/help/credit-cards/gambling-betting-fee`)] },
  { id: 'price-promise', group: 'Credit and payments', ic: 'target', title: 'Price Promise', line: 'Rate cut by 3%, then 2% more', cards: ['forward'],
    terms: ['Stay within your limit and pay at least the minimum on time, and your standard and cash rates drop by 3% after year one and 2% more after year two', 'Miss out in year one but qualify in year two, and you get the 3% cut then', 'The cut starts from your statement in the month your account turns one: March 2027 for your account'],
    action: { label: 'See my progress', push: 'promise' },
    sources: [S('Barclaycard Forward', `${BC}/credit-cards/forward`)] },
  { id: 'forward-limit', group: 'Credit and payments', ic: 'chart', title: 'Credit-building limit', line: '£50 to £1,200, set for you', cards: ['forward'],
    terms: ['A personal credit limit from £50 to £1,200', 'Staying within it and paying on time helps build your credit record', '0% on purchases for your first 3 months when you pay on time'],
    sources: [S('Credit-building cards', `${BC}/credit-cards/credit-building-cards`)] },
  { id: 'promo-rates', group: 'Credit and payments', ic: 'clock', title: 'Your 0% offers', line: 'Promotional rates on this card', cards: ['amazon', 'platinum', 'premium-plus'],
    per: {
      amazon: { line: '0% on purchases for 6 months', terms: ['0% on all purchases for your first 6 months, until Tue 10 Nov', 'After that, the purchase rate applies to anything left'] },
      platinum: { line: '0% on your balance transfer until Sun 14 Mar 2027', terms: ['Platinum versions offer 0% on transfers for up to 12, 20 or 29 months, or 21 months on transfers and purchases', 'Transfer fees from 0% to 3.45%', 'When a 0% period ends, anything left moves to the purchase rate'] },
      'premium-plus': { line: 'Ended in May 2024', terms: ['0% on purchases for the first 6 months after opening', 'Your account opened in November 2023, so this ended in May 2024'] },
    },
    terms: [], sources: [S('All credit cards', `${BC}/credit-cards`), S('Premium Plus summary', `${BB}/cards/credit-cards/premium-plus/summary`)] },
  { id: 'persistent-debt', group: 'Credit and payments', ic: 'info', title: 'Help if you’re paying mostly interest', line: 'A plan after 18 months of low payments', cards: PERSONAL,
    terms: ['If over 18 months you’ve paid more in interest, fees and charges than off what you borrowed, Barclaycard tells you and suggests a payment amount', 'Set it as a fixed Direct Debit, or call 0333 200 9090'],
    sources: [S('Persistent debt', `${BC}/customer/persistent-debt`)] },
  { id: 'calculator', group: 'Credit and payments', ic: 'chart', title: 'Repayment calculator', line: 'See what paying more saves', cards: [...PERSONAL, 'premium-plus', 'select-cashback'],
    terms: ['Shows how long a balance takes to clear and the interest you pay at different monthly amounts'],
    action: { label: 'Open the calculator', push: 'calc' },
    sources: [S('Repayment calculator', `${BC}/customer/repayment-calculator-tool`)] },
  { id: 'score', group: 'Credit and payments', ic: 'chart', title: 'Free Experian Credit Score', line: 'Updated every 60 days', cards: PERSONAL,
    terms: ['Free for over-18s, updated every 60 days', 'Checking it doesn’t affect lending decisions, and Barclaycard can’t see your score', 'You can opt out at any time'],
    action: { label: 'See my score', push: 'score' },
    sources: [S('Experian Credit Score terms', 'https://www.barclaycard.co.uk/content/dam/barclaycard/documents/personal/standalone/barclaycards-free-experian-credit-score-terms-and-conditions-srp.pdf')] },

  // ---------------- Card and security ----------------
  { id: 'card-details', group: 'Card and security', ic: 'eye', title: 'Card details in the app', line: 'Number, expiry and security code', cards: ALL,
    terms: ['See your full card details in the app to pay online', 'Still valid while a damaged card is replaced'],
    per: { 'premium-plus': { terms: ['The Barclaycard for Business app shows the full 16-digit card number (from August 2026)'] }, 'select-cashback': { terms: ['The Barclaycard for Business app shows the full 16-digit card number (from August 2026)'] }, 'select-charge': { terms: ['The Barclaycard for Business app shows the full 16-digit card number (from August 2026)'] } },
    action: { label: 'Show card details', tab: 'card' },
    sources: [S('View my card details', 'https://help.barclaycard.co.uk/brochure/credit_cards/how-safe-is-view-my-card-details'), S('Barclaycard for Business app', 'https://apps.apple.com/gb/app/barclaycard-for-business/id1538982647', 'Third party')] },
  { id: 'pin', group: 'Card and security', ic: 'key', title: 'Your PIN', line: 'View it in the app', cards: ALL,
    terms: ['View your PIN in the app', 'Locked after three wrong tries: unlock it in the app or at a UK cash machine', 'Change it at any UK cash machine'],
    action: { label: 'View PIN', tab: 'card' },
    sources: [S('Forgotten PIN', `${BC}/help/account-servicing/forgotten-pin`), S('Unlock my PIN', `${BC}/help/fraud-security/unlock-my-pin`)] },
  { id: 'freeze', group: 'Card and security', ic: 'snow', title: 'Freeze your card', line: 'Stop payments until you unfreeze', cards: ALL,
    terms: ['Stops payments in shops, online and on your phone', 'Unfreeze whenever you’re ready'],
    action: { label: 'Card controls', tab: 'card' },
    sources: [S('Amazon Barclaycard lost or stolen', `${BC}/help/credit-cards/amazon-barclaycard-lost-stolen`), S('Barclaycard for Business app', 'https://play.google.com/store/apps/details?id=com.barclays.barclaycardforbusiness', 'Third party')] },
  { id: 'lost', group: 'Card and security', ic: 'flag', title: 'Lost, stolen or damaged card', line: 'Block it in the app, new details within 24 hours', cards: ALL,
    terms: ['Block the card straight away in the app', 'New card details appear in the app within 24 hours for online, phone and mail-order payments', 'The new card arrives within 7 working days, with the same PIN'],
    per: { amazon: { line: 'Block it in the app, new details straight away', terms: ['Report it in the app or on 0800 151 0157, 24/7', 'New card details show in the app straight away', 'The card arrives within 7 working days with the same PIN'] } },
    action: { label: 'Report a card', push: 'lost' },
    sources: [S('Lost or stolen', `${BC}/help/fraud-security/lost-or-stolen`), S('Lost, stolen or damaged cards', `${BC}/customer/lost-stolen-damaged-cards`)] },
  { id: 'wallets', group: 'Card and security', ic: 'apple', title: 'Pay with your phone', line: 'Contactless up to £100', cards: ALL,
    per: {
      rewards: { line: 'Apple Pay, Android Contactless Mobile' }, platinum: { line: 'Apple Pay, Android Contactless Mobile' }, forward: { line: 'Apple Pay, Android Contactless Mobile' },
      amazon: { line: 'Google Pay (no Apple Pay)' }, 'avios-plus': { line: 'Apple Pay and Google Pay' }, avios: { line: 'Apple Pay and Google Pay' },
      'premium-plus': { line: 'Apple Pay' }, 'select-cashback': { line: 'Apple Pay' }, 'select-charge': { line: 'Apple Pay' },
    },
    perTerms: {
      amazon: ['Contactless card payments up to £100', 'Google Pay works with this card; Apple Pay doesn’t'],
      'avios-plus': ['Contactless card payments up to £100', 'Apple Pay, and Google Pay since October 2025'], avios: ['Contactless card payments up to £100', 'Apple Pay, and Google Pay since October 2025'],
      'premium-plus': ['Contactless card payments up to £100', 'Apple Pay on the Barclaycard for Business app'], 'select-cashback': ['Contactless card payments up to £100', 'Apple Pay on the Barclaycard for Business app'], 'select-charge': ['Contactless card payments up to £100', 'Apple Pay on the Barclaycard for Business app'],
    },
    terms: ['Contactless card payments up to £100', 'Apple Pay is free to set up and use; a replacement card updates in Wallet automatically', 'Android Contactless Mobile: up to £100, or up to £300 with your phone’s PIN at some shops'],
    action: { label: 'Add to your phone', toast: 'In the live app, this opens your phone’s wallet with your card ready to add.' },
    sources: [S('Apple Pay', `${BC}/apple-pay`), S('Contactless Mobile', `${BC}/customer/contactless-mobile`), S('Head for Points: Google Pay on Avios cards', 'https://www.headforpoints.com/2025/10/14/google-pay-barclaycard-avios-credit-cards/', 'Third party')] },
  { id: 'approvals', group: 'Card and security', ic: 'lock', title: 'Approve online payments', line: 'In the app, by text or with PINsentry', cards: ALL,
    terms: ['Some online payments ask you to confirm it’s you: in the app, with a text code, or with Mobile PINsentry', 'Log in with Face ID or Touch ID'],
    action: { label: 'Security centre', push: 'security' },
    sources: [S('Fraud and security', `${BC}/customer/fraud`), S('PINsentry', `${BC}/help/fraud-security/pinsentry`)] },
  { id: 'check-its-us', group: 'Card and security', ic: 'info', title: 'How to check it’s really Barclaycard', line: 'What Barclaycard will never ask', cards: PERSONAL,
    terms: ['Barclaycard never asks for your PIN, your login details or your full passcode', 'Its emails never contain a direct login link and show only your name and the last four digits of your card', 'Scam help: Fraud Fighter, Tea and Teach sessions, and Take Five'],
    action: { label: 'Security centre', push: 'security' },
    sources: [S('How to check it’s us', `${BC}/customer/how-to-check-it-is-us`), S('Protecting yourself from fraud', `${BC}/customer/protecting-yourself-from-fraud`)] },
  { id: 'cardholders', group: 'Card and security', ic: 'users', title: 'Additional cardholders', line: 'Up to four, free', cards: PERSONAL,
    terms: ['Add up to four cardholders at no cost', 'They must be over 18, a close family member and live at your address', 'Their spending shows on your statement and you’re responsible for it', 'Cards arrive in 1 to 2 weeks; remove a cardholder by phone'],
    action: { label: 'Manage cardholders', push: 'cardholders' },
    sources: [S('Additional cardholder', `${BC}/customer/additional-cardholder`)] },
  { id: 'switch', group: 'Card and security', ic: 'card', title: 'Change to a different card', line: 'In the app, with no credit check', cards: PERSONAL,
    terms: ['Some customers can switch to another Barclaycard in the app, with no credit check'],
    action: { label: 'See other cards', toast: 'In the live app, eligible customers see card switch offers here.' },
    sources: [S('Change card', `${BC}/help/credit-cards/change-card`)] },
  { id: 'expiry', group: 'Card and security', ic: 'cal', title: 'Replacement before your card expires', line: 'Arrives 3 to 6 weeks before', cards: PERSONAL,
    terms: ['Your replacement arrives three to six weeks before your card expires'],
    sources: [S('Expiring card replacement', `${BC}/help/credit-cards/expiring-card-replacement`)] },

  // ---------------- Alerts and statements ----------------
  { id: 'alerts', group: 'Alerts and statements', ic: 'bell', title: 'Six free alerts', line: 'By text or email, free in the UK', cards: PERSONAL,
    terms: ['Weekly balance, on a day you choose', 'Payment received, statement ready and payment due', 'Balance limit and monthly spend limit, at amounts you set', 'Automatic alerts too: nearing your limit, over your limit, account changes and promotional rates ending'],
    action: { label: 'Manage alerts', push: 'alerts' },
    sources: [S('Alerts', `${BC}/customer/alerts`), S('Alert frequency', `${BC}/help/account-servicing/alert-frequency`), S('Nearing credit limit', `${BC}/help/account-servicing/account-nearing-creditlimit`)] },
  { id: 'statements', group: 'Alerts and statements', ic: 'doc', title: 'Statements', line: 'Seven years, paperless or paper', cards: PERSONAL,
    terms: ['Statements from the last seven years, as PDFs', 'Switch between paperless and paper in the app', 'A yearly statement on your account anniversary shows any rate changes', 'Paper copies are free'],
    action: { label: 'My statements', push: 'statements' },
    sources: [S('Statement preferences', `${BC}/help/statements/statement-preference`), S('Servicing updates', `${BC}/customer/servicing-updates`)] },
  { id: 'app-first', group: 'Alerts and statements', ic: 'phone', title: 'Everything in the app', line: 'Reported: online servicing closing in 2026', cards: PERSONAL,
    terms: ['GB News reported in April 2026 that Barclaycard is moving account management to the Barclaycard and Barclays apps, phone and branch', 'The Amazon Barclaycard is already app-only'],
    sources: [S('GB News, April 2026', 'https://www.gbnews.com/money/barclaycard-to-shut-down-website-for-customers', 'Third party')] },
  { id: 'biz-statements', group: 'Alerts and statements', ic: 'doc', title: 'Statements and exports', line: 'PDF or CSV', cards: BIZ,
    terms: ['Download statements as PDF or CSV', 'The app shows each cardholder’s own balance; company balance and payments are in Online Servicing'],
    action: { label: 'My statements', push: 'statements' },
    sources: [S('Business help', `${BB}/help-and-support/credit-and-charge-card`), S('Barclaycard for Business app', 'https://play.google.com/store/apps/details?id=com.barclays.barclaycardforbusiness', 'Third party')] },

  // ---------------- Business tools ----------------
  { id: 'mycontrols', group: 'Business tools', ic: 'settings', title: 'MyControls', line: 'Set where and how each card can be used', cards: BIZ,
    terms: ['Limit spending by merchant category', 'Turn ATM, online and in-store use on or off', 'Freeze an employee’s card', 'Set each cardholder’s credit limit'],
    action: { label: 'Open MyControls', push: 'controls' },
    sources: [S('Online servicing', `${BB}/cards/online-servicing`), S('Premium Plus', `${BB}/cards/credit-cards/premium-plus`)] },
  { id: 'employee-cards', group: 'Business tools', ic: 'users', title: 'Employee cards', line: 'Free, with a limit for each', cards: BIZ,
    per: { 'select-charge': { line: 'No extra cardholder fees', terms: ['Account administrators add cardholders for free and set their limits'] } },
    terms: ['Account administrators add cardholders for free and set their limits', 'Cashback counts all cardholders’ spending'],
    action: { label: 'Employee cards', push: 'cardholders' },
    sources: [S('Premium Plus', `${BB}/cards/credit-cards/premium-plus`), S('Select Cashback guide', `${BB}/cards/business-card-customer-home/select-cashback-guide`)] },
  { id: 'biz-app', group: 'Business tools', ic: 'phone', title: 'Barclaycard for Business app', line: 'PIN, freeze, approvals, statements', cards: BIZ,
    terms: ['View PIN and the full card number, balance and limit', 'Transactions with merchant logos and addresses', 'Freeze and unfreeze, approve online payments, block a lost card, order a replacement', 'Download statements, add to Apple Pay, and an inbox'],
    sources: [S('App Store listing', 'https://apps.apple.com/gb/app/barclaycard-for-business/id1538982647', 'Third party')] },
  { id: 'accounting', group: 'Business tools', ic: 'chart', title: 'Accounting', line: 'FreshBooks, and a QuickBooks feed', cards: BIZ,
    terms: ['FreshBooks plan for new cardholders', 'A QuickBooks Online bank feed is available; it needs an Authorised Signatory login'],
    sources: [S('Premium Plus', `${BB}/cards/credit-cards/premium-plus`), S('QuickBooks Community', 'https://quickbooks.intuit.com/learn-support/en-uk/other-questions/barclaycard-business-credit-card-cannot-add-to-qbo-anyone-else/00/1235434', 'Third party')] },

  // ---------------- Help and support ----------------
  { id: 'contact', group: 'Help and support', ic: 'chat', title: 'Chat, message or call', line: 'Chat in the app 24/7', cards: ALL,
    per: { 'premium-plus': { line: 'Cardholder line 24/7', terms: ['Cardholder line 0800 008 008, open 24/7', 'Fraud line 0800 015 9059'] }, 'select-cashback': { line: 'Cardholder line 24/7', terms: ['Cardholder line 0800 008 008, open 24/7', 'Fraud line 0800 015 9059'] }, 'select-charge': { line: 'Cardholder line 24/7', terms: ['Cardholder line 0800 008 008, open 24/7', 'Fraud line 0800 015 9059'] } },
    terms: ['Chat in the app, 24/7, or through Apple Messages', 'Customer services: 0800 151 0900, Monday to Friday 7am to 8pm, Saturday 9am to 5pm', 'From abroad: +44 1604 230 230, 24/7'],
    action: { label: 'Help', push: 'help' },
    sources: [S('Contact us', `${BC}/contact-us`), S('Business card customer home', `${BB}/cards/business-card-customer-home`)] },
  { id: 'money-worries', group: 'Help and support', ic: 'info', title: 'Money worries', line: 'Support if things get hard', cards: PERSONAL,
    terms: ['Worried about paying: 0800 056 1411. Missed a payment: 0800 161 5205 (weekdays 8am to 9pm, weekends 9am to 9pm)', 'Or message from Help in the app', 'Help for life events such as losing a job or illness, and free advice from StepChange, National Debtline, MoneyHelper and Citizens Advice'],
    action: { label: 'Get support', push: 'help' },
    sources: [S('Money worries', `${BC}/customer/money-worries`)] },
  { id: 'accessibility', group: 'Help and support', ic: 'users', title: 'Accessibility', line: 'BSL, braille, large print, audio', cards: ALL,
    terms: ['SignVideo in British Sign Language: weekdays 8am to 8pm, Saturday 8am to 1pm', 'Statements and PIN in braille, large print or audio: 0800 161 5326', 'Text Relay: 18001 0800 161 5276', 'The app works with VoiceOver and larger text'],
    sources: [S('Sight services', `${BC}/accessibility/sight-services`), S('SignVideo', `${BC}/accessibility/sign-video`)] },
  { id: 'third-party', group: 'Help and support', ic: 'user', title: 'Power of Attorney and bereavement', line: 'Help for someone managing your account', cards: PERSONAL,
    terms: ['Register a Power of Attorney', 'Tell Barclaycard about a death online, through the Death Notification Service, or on 0800 161 5199'],
    sources: [S('Power of Attorney', `${BC}/help/account-servicing/account-power-of-attorney`), S('Bereavement', `${BC}/help/account-servicing/bereavement`)] },
  { id: 'complaints', group: 'Help and support', ic: 'flag', title: 'Complaints', line: 'Final response within 8 weeks', cards: PERSONAL,
    terms: ['A reply to a message in the app within 24 hours', 'An update at 4 weeks and a final response at 8 weeks', 'Then you can go to the Financial Ombudsman Service'],
    sources: [S('Complaints', `${BC}/help-and-support/complaints`)] },
]

export const benefitsFor = (id: CardId) => BENEFITS.filter(b => b.cards.includes(id)).map(b => ({ ...b, line: b.per?.[id]?.line ?? b.line, terms: b.per?.[id]?.terms ?? b.perTerms?.[id] ?? b.terms }))
