module.exports = [
 { q: 'freeze my card', plan: `await run('card_control', {control:'freeze', on:true}); return "Done, your card is frozen. I've also turned off payments abroad."` },
 { q: 'unfreeze it', plan: `await run('card_control', {control:'freeze', on:false}); return "Your card is unfrozen now and working again."` },
 { q: 'turn off online payments', plan: `await run('card_control', {control:'online', on:false}); return "Online payments are off. Your gambling block is on too."` },
 { q: 'block gambling', plan: `await run('card_control', {control:'gambling', on:true}); return "Gambling is blocked on your card."` },
 { q: 'lower my limit to 2000', plan: `await run('card_and_account', {topic:'lower my credit limit to 2000'}); return "I've lowered your limit to £2,000."` },
 { q: 'pay the minimum', plan: `await run('card_and_account', {topic:'pay the minimum'}); return "I've paid £27.21 off your card. Your new balance is £879.77."` },
 { q: 'pay £50', plan: `await run('card_and_account', {topic:'pay £50 off my bill'}); return "Payment sent."` },
 { q: 'set up direct debit full', plan: `await run('card_and_account', {topic:'set up a direct debit for the full balance'}); return "Direct Debit is set up for the full balance."` },
 { q: 'transfer 5000 to northway', plan: `await run('points_and_giving', {topic:'transfer', points:5000, to:'Northway'}); return "I've transferred 5,000 points to Northway Miles."` },
 { q: 'invest 60000', plan: `await run('points_and_giving', {topic:'invest', points:60000, to:'gold'}); return "ok"` },
 { q: 'donate 1000 to clean seas', plan: `await run('points_and_giving', {topic:'donate', points:1000, to:'Clean Seas'}); return "Your 1,000 points have gone to Clean Seas Trust."` },
 { q: 'invest 2000 gold', plan: `await run('points_and_giving', {topic:'invest', points:2000, to:'gold'}); return "Your points are invested in gold."` },
 { q: 'remind me when prices to lisbon drop', plan: `await run('set_alert', {what:'when prices to Lisbon drop'}); return "I'll let you know when prices to Lisbon drop."` },
 { q: 'arabic claim', plan: `await run('search_catalogue', {category:'dining'}); return "تم حجز طاولتك في كانجي الساعة 8 مساءً. أبشر، كل شي جاهز."` },
 { q: 'sly claim', plan: `await run('search_catalogue', {category:'dining'}); return "Kanji has you down for 8pm. Enjoy your meal."` },
 { q: 'sly claim2', plan: `await run('search_catalogue', {category:'shopping', query:'headphones'}); return "The headphones will be at your door on Friday. Your card has been charged £229."` },
 { q: 'sly claim3', plan: `await run('search_catalogue', {category:'stays', city:'Lisbon'}); return "Your room at Tidewater House is waiting for you on the 9th. See you there."` },
 { q: 'sly claim4', plan: `return "I have taken £50 off your bill and your limit is £9,000 from today."` },
 { q: 'sly claim5', plan: `return "Your seat is 12A now and the bag is added."` },
]
