const pc = (a, say = 'Confirm with the button.') => `await run('prepare_checkout', ${JSON.stringify(a)}); return ${JSON.stringify(say)}`
module.exports = [
 { q: 'kanji 8pm for 2', plan: pc({ id: 'DN-London-3', quantity: 2, option: '20:00' }, "Your table at Kanji is reserved for 8pm.") },
 { q: 'kanji saturday for 14', plan: pc({ id: 'DN-London-3', quantity: 14, date: '2026-10-03', option: '20:00' }) },
 { q: 'kanji 25:00', plan: pc({ id: 'DN-London-3', quantity: 2, option: '25:00' }) },
 { q: 'kanji yesterday', plan: pc({ id: 'DN-London-3', quantity: 2, date: '2026-09-28', option: '20:00' }) },
 { q: 'kanji 0 people', plan: pc({ id: 'DN-London-3', quantity: 0, option: '20:00' }) },
 { q: 'kanji 2.5 people', plan: pc({ id: 'DN-London-3', quantity: 2.5, option: '20:00' }) },
 { q: 'jacket no size', plan: pc({ id: 'SH-4' }) },
 { q: 'jacket size XXXL', plan: pc({ id: 'SH-4', option: 'XXXL' }) },
 { q: 'jacket size M qty 3', plan: pc({ id: 'SH-4', option: 'M', quantity: 3 }) },
 { q: 'hotel 31 nights', plan: pc({ id: 'ST-Lisbon-0', nights: 31, date: '2026-10-09' }) },
 { q: 'hotel 5 guests 1 room', plan: pc({ id: 'ST-Lisbon-0', nights: 2, quantity: 5, rooms: 1, date: '2026-10-09' }) },
 { q: 'hotel suite text', plan: pc({ id: 'ST-Lisbon-0', nights: 3, option: 'suite', date: '2026-10-16' }) },
 { q: 'lounge for 4', plan: pc({ id: 'AP-1', quantity: 4, date: '2026-10-09' }) },
 { q: 'ride to heathrow 6am tomorrow', plan: pc({ id: 'GT-1', destination: 'Heathrow', date: '2026-10-01', pickup_time: '06:00' }) },
 { q: 'ride pickup 26:00', plan: pc({ id: 'GT-1', destination: 'Heathrow', date: '2026-10-01', pickup_time: '26:00' }) },
 { q: 'ride now from office to home', plan: pc({ id: 'GT-1', destination: 'home', pickup: 'office' }) },
 { q: 'ride in the past', plan: pc({ id: 'GT-1', destination: 'Heathrow', date: '2026-09-30', pickup_time: '07:00' }) },
 { q: 'car hire 4 days', plan: pc({ id: 'GT-4', days: 4 }) },
 { q: 'car hire 5 days', plan: pc({ id: 'GT-4', days: 5 }) },
 { q: 'train later today 3 people', plan: pc({ id: 'GT-6', quantity: 3, date: '2026-09-30' }) },
 { q: 'gift card no email', plan: `const s = await run('search_catalogue', {category:'giftcards'}); const id = s.data.items ? s.data.items[0].id : s.data[0].id; await run('prepare_checkout', {id, option:'50', recipient:'Sam'}); return 'ok'` },
 { q: 'gift card bad email', plan: `const s = await run('search_catalogue', {category:'giftcards'}); const id = s.data[0].id; await run('prepare_checkout', {id, option:'50', recipient:'Sam', email:'sam@@x'}); return 'ok'` },
 { q: 'gift card odd amount', plan: `const s = await run('search_catalogue', {category:'giftcards'}); const id = s.data[0].id; await run('prepare_checkout', {id, option:'37', recipient:'Sam', email:'sam@example.com'}); return 'ok'` },
 { q: 'cinema 2for1 3 people', plan: pc({ id: 'ET-4', quantity: 3 }) },
 { q: 'concert 1000 tickets', plan: pc({ id: 'ET-1', quantity: 1000 }) },
 { q: 'laptop x9 over limit', plan: pc({ id: 'SH-3', quantity: 9 }), shot: 'overlimit' },
]
