module.exports = async (h) => { const { p, nav, say, click } = h
  const audit = async (tag) => { const r = await p.evaluate(() => {
    const name = e => (e.getAttribute('aria-label') || e.getAttribute('aria-labelledby') && document.getElementById(e.getAttribute('aria-labelledby'))?.textContent || e.textContent || e.getAttribute('title') || '').trim()
    const vis = e => { const b = e.getBoundingClientRect(); return b.width > 0 && b.height > 0 }
    const btn = [...document.querySelectorAll('button,[role=button],a')].filter(vis).filter(e => !name(e)).map(e => e.outerHTML.slice(0, 100))
    const inp = [...document.querySelectorAll('input,textarea,select')].filter(vis).filter(e => !(e.getAttribute('aria-label') || e.id && document.querySelector(`label[for="${e.id}"]`) || e.closest('label') || e.getAttribute('placeholder'))).map(e => e.outerHTML.slice(0, 100))
    const noPlaceholderOnly = [...document.querySelectorAll('input,textarea')].filter(vis).filter(e => !e.getAttribute('aria-label') && !e.closest('label') && e.getAttribute('placeholder')).length
    const small = [...document.querySelectorAll('button,[role=button],[role=switch],a,input[type=checkbox]')].filter(vis).filter(e => { const b = e.getBoundingClientRect(); return b.height < 24 || b.width < 24 }).map(e => (name(e) || e.outerHTML.slice(0, 60)).slice(0, 40) + ':' + Math.round(e.getBoundingClientRect().width) + 'x' + Math.round(e.getBoundingClientRect().height))
    const lum = c => { const m = c.match(/[\d.]+/g).map(Number); const f = v => { v /= 255; return v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4 }; return 0.2126 * f(m[0]) + 0.7152 * f(m[1]) + 0.0722 * f(m[2]) }
    const bgOf = e => { while (e) { const c = getComputedStyle(e).backgroundColor; if (c && !/rgba\(0, 0, 0, 0\)|transparent/.test(c)) return c; e = e.parentElement } return 'rgb(255,255,255)' }
    const low = []; document.querySelectorAll('body *').forEach(e => { if (!vis(e) || !e.childNodes.length || ![...e.childNodes].some(n => n.nodeType === 3 && n.textContent.trim())) return; const cs = getComputedStyle(e); if (cs.visibility === 'hidden' || +cs.opacity < 0.5) return; const a = lum(cs.color), b = lum(bgOf(e)); const cr = (Math.max(a, b) + 0.05) / (Math.min(a, b) + 0.05); const big = parseFloat(cs.fontSize) >= 24 || (parseFloat(cs.fontSize) >= 18.66 && +cs.fontWeight >= 700); if (cr < (big ? 3 : 4.5)) low.push(e.textContent.trim().slice(0, 30) + ' ' + cr.toFixed(2)) })
    return { btn: btn.slice(0, 5), inp: inp.slice(0, 5), noPlaceholderOnly, small: [...new Set(small)].slice(0, 12), low: [...new Set(low)].slice(0, 15), lang: document.documentElement.lang, dir: document.documentElement.dir }
  }); console.log('AUDIT', tag, JSON.stringify(r)) }
  await audit('home'); await nav(2); await audit('explore'); await nav(5); await audit('me'); await nav(4); await audit('wallet')
  await nav(3); await say('Flights to Lisbon next weekend for two'); await p.locator('.gr-flight').first().click(); await p.waitForTimeout(400); await click(/Continue with/); await audit('seats')
  await say('Noise-cancelling headphones'); await p.locator('.gr-answer').last().locator('.gr-itemrow').first().click(); await p.waitForTimeout(400); await p.locator('.gr-answer').last().locator('.gr-detail .gr-btn').last().click(); await p.waitForTimeout(300); await click(/^Pay /); await p.waitForTimeout(300)
  const dlg = await p.evaluate(() => { const d = document.querySelector('[role=dialog]'); return d && { modal: d.getAttribute('aria-modal'), label: d.getAttribute('aria-label') || d.getAttribute('aria-labelledby'), focusInside: d.contains(document.activeElement), active: document.activeElement?.outerHTML.slice(0, 80), inert: !!document.querySelector('[inert]') } }); console.log('DIALOG', JSON.stringify(dlg)); await audit('sheet')
  for (let i = 0; i < 12; i++) await p.keyboard.press('Tab'); console.log('focus after tabs inside dialog?', await p.evaluate(() => document.querySelector('[role=dialog]')?.contains(document.activeElement)))
  await p.keyboard.press('Escape'); await p.waitForTimeout(300); console.log('focus returned to', await p.evaluate(() => document.activeElement?.outerHTML.slice(0, 80)))
}
