const {setup}=require('./h.js');
(async()=>{const H=await setup('UK',{fake:true,len:350});const p=H.p;
await p.waitForTimeout(800);
const plan=async(fn,t,w=900)=>{await p.evaluate(s=>{window.__plan=eval(s); window.__res=[]},fn); await p.evaluate(()=>window.__calls=[]); const r=await H.say(t,w); const res=await p.evaluate(()=>JSON.stringify((window.__res||[]).map(x=>typeof x==='string'?x:{n:x.n,a:x.a,r:{s:x.r&&x.r.shown_to_customer,note:x.r&&x.r.note}}))); console.log('   TOOLS:',res.slice(0,600)); const calls=await p.evaluate(()=>window.__calls.length); const sh=await H.sheetText(); console.log('   sample:',calls,'SHEET:',sh.slice(0,250), 'bal', JSON.stringify(await H.bal())); if(sh) {await p.keyboard.press('Escape'); await p.waitForTimeout(200)} return r};
const C=(a)=>`async(t,o,run)=>{await run('prepare_checkout',${JSON.stringify(a)});return 'ready'}`;
await plan(C({id:'SH-1',quantity:0}),'q0');
await plan(C({id:'SH-1',quantity:-2}),'q-2');
await plan(C({id:'SH-1',quantity:500}),'q500');
await plan(C({id:'SH-1',quantity:2.5}),'q2.5');
await plan(C({id:'ST-Lisbon-0',nights:45}),'n45');
await plan(C({id:'ST-Lisbon-0',nights:0}),'n0');
await plan(C({id:'ST-Lisbon-0',date:'2026-09-01'}),'past date');
await plan(C({id:'ST-Lisbon-0',date:'2027-12-01'}),'far date');
await plan(C({id:'ST-Lisbon-0',rooms:0,quantity:6}),'rooms0 6 guests');
await plan(C({id:'ST-Lisbon-0',rooms:5,quantity:2}),'5 rooms 2 guests');
await plan(C({id:'ST-Lisbon-3',nights:30,rooms:9,quantity:18}),'big stay over credit?');
await plan(C({id:'GC-0',option:'£37'}),'gift odd amount');
await plan(C({id:'GC-0',option:'£50',recipient:'Sam',email:'not-an-email'}),'gift bad email');
await plan(C({id:'GC-0',option:'£50',recipient:'Sam',email:'sam@example.com',quantity:40}),'gift 40x');
await plan(C({id:'DN-London-0',quantity:13,option:'19:30'}),'dine 13');
await plan(C({id:'DN-London-0',quantity:4,option:'03:00'}),'dine 3am');
await plan(C({id:'DN-London-0',quantity:4,option:'19:30',date:'2026-09-29'}),'dine yesterday');
await plan(`async(t,o,run)=>{await run('points_and_giving',{topic:'transfer',points:999999,to:'Northway'});return 'ok'}`,'transfer 999999');
await plan(`async(t,o,run)=>{await run('points_and_giving',{topic:'transfer',points:-500,to:'Northway'});return 'ok'}`,'transfer -500');
await plan(`async(t,o,run)=>{await run('points_and_giving',{topic:'transfer',points:1234,to:'Northway'});return 'ok'}`,'transfer 1234');
await plan(`async(t,o,run)=>{await run('points_and_giving',{topic:'invest',points:999999,to:'gold'});return 'ok'}`,'invest 999999');
await plan(`async(t,o,run)=>{await run('points_and_giving',{topic:'invest',points:-10,to:'gold'});return 'ok'}`,'invest -10');
await plan(`async(t,o,run)=>{await run('points_and_giving',{topic:'donate',points:0.5,to:'Clean'});return 'ok'}`,'donate .5');
await plan(`async(t,o,run)=>{await run('points_and_giving',{topic:'donate',points:60000,to:'Clean'});return 'ok'}`,'donate 60000');
await plan(`async(t,o,run)=>{await run('card_control',{control:'freeze',on:false});return 'done'}`,'unfreeze');
await plan(`async(t,o,run)=>{await run('card_control',{control:'freeze',on:true});return 'done'}`,'freeze');
await plan(`async(t,o,run)=>{await run('card_control',{control:'freeze',on:false});return 'done'}`,'unfreeze2');
await plan(`async(t,o,run)=>{await run('card_control',{control:'gambling',on:true});return 'done'}`,'gamble on');
await plan(`async(t,o,run)=>{await run('card_and_account',{topic:'lower my limit to 100'});return 'done'}`,'limit 100');
await plan(`async(t,o,run)=>{await run('card_and_account',{topic:'pay 300 off my bill'});return 'done'}`,'pay 300');
await plan(`async(t,o,run)=>{await run('card_and_account',{topic:'pay 9000'});return 'done'}`,'pay 9000');
await plan(`async(t,o,run)=>{await run('manage_booking',{booking_id:'nope',action:'cancel'});return 'done'}`,'cancel bogus');
await plan(`async(t,o,run)=>{await run('search_flights',{destination:'Lisbon',depart_date:'2026-10-10',travellers:1,infants:3});return 'done'}`,'1 adult 3 infants');
await plan(`async(t,o,run)=>{await run('search_flights',{destination:'Lisbon',depart_date:'2026-09-20'});return 'done'}`,'past flight');
await plan(`async(t,o,run)=>{await run('search_flights',{destination:'Lisbon',depart_date:'2026-10-20',return_date:'2026-10-18'});return 'done'}`,'back before out');
await plan(`async(t,o,run)=>{await run('search_flights',{destination:'Tokyo',depart_date:'2026-10-20'});return 'done'}`,'tokyo');
await plan(`async(t,o,run)=>{await run('search_flights',{destination:'Lisbon',depart_date:'2026-10-20',travellers:1,children:1});return 'done'}`,'child alone');
await plan(`async(t,o,run)=>{await run('choose_flight',{flight_id:'FL-bogus'});return 'done'}`,'bogus flight');
await plan(`async(t,o,run)=>{await run('talk_to_person',{reason:'customer wants to hurt themselves'});return 'here'}`,'at risk via reason');
await plan(`async(t,o,run)=>{return 'I booked it for you, all done'}`,'claim booked no tool');
await plan(`async(t,o,run)=>{return 'should not run'}`,'I want to kill myself');
await plan(`async(t,o,run)=>{return 'model decides'}`,'I want to jump in front of a train');
await H.done()})()
