const { chromium } = require('/home/claude/.npm-global/lib/node_modules/playwright');
const BASE = 'file://' + __dirname + '/../gratifi/review/';
exports.setup = async (market = 'UK', o = {}) => {
  const b = await chromium.launch();
  const ctx = await b.newContext({ viewport: { width: 420, height: o.h || 880 }, deviceScaleFactor: 1 });
  const p = await ctx.newPage(); const errs = [];
  p.on('pageerror', e => errs.push('PAGE ' + e.message)); p.on('console', m => { if (m.type() === 'error') errs.push('CON ' + m.text()) });
  if (o.fake) await ctx.addInitScript({ path: __dirname + '/fake.js' });
  const file = o.ai ? 'test-ai.html' : 'test.html';
  const url = `${BASE}${file}?m=${market}&theme=${o.theme || 'light'}&tab=${o.tab || 'chat'}`;
  await p.goto(url); if (!o.keep) { await p.evaluate(() => localStorage.clear()); await p.goto(url); } await p.waitForTimeout(500);
  let n = 0; const tag = o.tag || market;
  const H = { b, p, errs, market };
  H.shot = async (name, full = true) => { await p.waitForTimeout(300); const f = `shots/${tag}-${String(++n).padStart(2, '0')}-${name}.png`; if (full) { const el = await p.$('.app-main .app-scroll'); if (el && await p.$('.app[data-tab=chat]')) { await el.evaluate(e => e.scrollTop = e.scrollHeight) } } await p.screenshot({ path: f }); return f };
  H.fullshot = async (name) => { await p.waitForTimeout(300); const el = await p.$('.app-main .app-scroll'); const h = el ? await el.evaluate(e => e.scrollHeight) : 880; await p.setViewportSize({ width: 420, height: Math.min(6000, h + 200) }); await p.waitForTimeout(250); const f = `shots/${tag}-${String(++n).padStart(2, '0')}-${name}.png`; await p.screenshot({ path: f }); await p.setViewportSize({ width: 420, height: o.h || 880 }); return f };
  H.st = () => p.evaluate(() => JSON.parse(localStorage.getItem('gratifi-state-v3-' + new URLSearchParams(location.search).get('m'))));
  H.last = async () => p.evaluate(() => { const a = [...document.querySelectorAll('.gr-answer')].pop(); return a ? a.innerText.replace(/\n+/g, ' | ') : '' });
  H.ask = async (t, w = 700) => { if (await p.$('.app-sheet')) { await p.keyboard.press('Escape'); await p.waitForTimeout(200) } await p.fill('.gr-ask input', t); await p.press('.gr-ask input', 'Enter'); await p.waitForTimeout(w); const s = await H.st(); const m = s.chat[s.chat.length - 1]; const r = { text: m.text || '', kinds: (m.blocks || []).map(b => b.kind), sheet: !!(await p.$('.app-sheet')) }; return r };
  H.say = async (t, w) => { const r = await H.ask(t, w); const vis = await H.last(); console.log(`\n>> ${t}\n   [${r.kinds.join(',')}]${r.sheet ? ' SHEET' : ''} ${vis.slice(0, o.len || 600)}`); return r };
  H.btn = (name, exact) => p.getByRole('button', { name, exact: !!exact }).last();
  H.click = async (name, exact) => { const l = H.btn(name, exact); await l.scrollIntoViewIfNeeded(); await l.click(); await p.waitForTimeout(500) };
  H.sheetText = async () => p.evaluate(() => document.querySelector('.app-sheet')?.innerText.replace(/\n+/g, ' | ') || '');
  H.confirm = async (code = '482193') => { await p.waitForTimeout(300); const s = await p.$('.app-sheet'); if (!s) return 'NO SHEET'; const t = await H.sheetText(); const ins = await p.$$('.app-sheet input'); if (ins.length >= 6) { for (let i = 0; i < 6; i++) await ins[i].fill(code[i]) } else if (ins.length) await ins[0].fill(code); await p.locator('.app-sheet .gr-btn').last().click(); await p.waitForSelector('.app-sheet', { state: 'detached', timeout: 9000 }).catch(() => errs.push('SHEET STUCK')); await p.waitForTimeout(500); return t };
  H.nav = async i => { if (await p.$('.app-sheet')) { await p.keyboard.press('Escape'); await p.waitForTimeout(200) } await p.click(`.gr-nav button:nth-child(${i})`); await p.waitForTimeout(350) };
  H.screen = async () => p.evaluate(() => document.querySelector('.app-main').innerText.replace(/\n+/g, ' | '));
  H.bal = async () => { const s = await H.st(); return { pts: s.balance, card: s.card.balance, due: s.card.due, avail: s.card.available ?? s.card.limit - s.card.balance } };
  H.done = async () => { if (errs.length) console.log('ERRS', errs.slice(0, 5)); await b.close() };
  return H;
};
