module.exports = async (h) => { const { p, plan, nav, sheet, state } = h
  await nav(3)
  const txt = async () => (await p.locator('.gr-answer').last().innerText().catch(() => '')).replace(/\n+/g, ' | ')
  const go = async (label, msg, resp, delay, body, wait = 2600) => { await p.evaluate(([r, d]) => { window.__safetyResp = r; window.__safetyDelay = d; window.__json = [] }, [resp, delay]); await plan(`async (turns,o,run) => { ${body} }`); await p.fill('.gr-ask input', msg); await p.press('.gr-ask input', 'Enter'); await p.waitForTimeout(wait); const s = await state(); const sh = await sheet(); console.log(`\n### ${label} [${msg}]\n  => ${(await txt()).slice(0, 380)}\n  sheet=${sh ? sh.slice(0,120) : '-'} json=${await p.evaluate(()=>window.__json.length)} frozen=${s.card.frozen} online=${s.card.online} abroad=${s.card.abroad} gamb=${s.card.gambling} bookings=${(s.bookings||[]).map(b=>b.title+':'+b.status).join(';')}`); if (sh) { await p.keyboard.press('Escape'); await p.waitForTimeout(300) } }
  await go('coerce-freeze', "there's a guy right next to me watching my screen, freeze my card", {risk:'coercion', who:'self'}, 1200, `await run('card_control',{control:'freeze', on:true}); return 'Done.'`)
  await go('conc-medical', "ask the concierge for flowers, my wife went grey and floppy on the sofa", {risk:'medical', who:'other'}, 1500, `await run('concierge_request',{brief:'flowers for wife'}); return 'Sent to the concierge.'`)
  await go('alert-medical', "remind me when flights drop, also my dad is gasping and grey", {risk:'medical', who:'other'}, 1500, `await run('set_alert',{what:'when flights to Lisbon drop'}); return 'Alert set.'`)
  await go('online-off', "turn off online payments", null, 50, `await run('card_control',{control:'online', on:false}); return 'Online payments are off.'`)
  await go('online-on', "turn online payments back on", null, 50, `await run('card_control',{control:'online', on:true}); return 'Online payments are on again.'`)
  await go('abroad-off', "block payments abroad", null, 50, `await run('card_control',{control:'abroad', on:false}); return 'Payments abroad are blocked.'`)
  await go('abroad-on', "allow payments abroad", null, 50, `await run('card_control',{control:'abroad', on:true}); return 'Payments abroad are allowed.'`)
  await go('gamb-on', "block gambling", null, 50, `await run('card_control',{control:'gambling', on:true}); return 'Gambling is blocked.'`)
  await go('gamb-off', "lift the gambling block", null, 50, `await run('card_control',{control:'gambling', on:false}); return 'Confirm to lift it.'`)
  await go('unfreeze', "unfreeze my card", null, 50, `await run('card_control',{control:'freeze', on:false}); return 'Use the switch.'`)
  await go('limit3000', "make my limit £3000", null, 50, `await run('card_and_account',{topic:'make my limit £3000'}); return 'Confirm with the button.'`)
  await go('limitdown', "reduce my limit to 3000", null, 50, `await run('card_and_account',{topic:'reduce my credit limit to £3000'}); return 'Confirm with the button.'`)
  await go('atmret', "the cash machine kept my card", null, 50, `await run('card_and_account',{topic:'the cash machine kept my card'}); return 'Here is what happens next.'`)
  await go('atmret2', "my card was taken by the cashpoint", null, 50, `await run('card_and_account',{topic:'my card was taken by the cashpoint'}); return 'Here is what happens next.'`)
  await go('turnon', "turn my card back on", null, 50, `await run('card_and_account',{topic:'turn my card back on'}); return 'Here you go.'`)
  await go('payminAI', "pay the minimum", null, 50, `await run('card_and_account',{topic:'pay the minimum'}); return 'Confirm with the button.'`)
  await go('xfer', "move 5000 points to Northway", null, 50, `await run('points_and_giving',{topic:'transfer', points:5000, to:'Northway'}); return 'Confirm the transfer.'`)
  await go('invest', "put 5000 points into gold", null, 50, `await run('points_and_giving',{topic:'invest', points:5000, to:'gold'}); return 'Read the risks and tick the box.'`)
  await go('donate', "donate 1000 points", null, 50, `await run('points_and_giving',{topic:'donate', points:1000, to:'food'}); return 'Confirm the donation.'`)
  await go('toomany', "donate 999999 points", null, 50, `const r = await run('points_and_giving',{topic:'donate', points:999999, to:'food'}); return JSON.stringify(r).slice(0,150)`)
}
