// Gratifi's own illustrations, carried in the bundle as data URIs so every component has art by default.
import flight from '../../pwa/src/assets/scene-flight.svg'
import lisbon from '../../pwa/src/assets/scene-lisbon.svg'
import pool from '../../pwa/src/assets/scene-pool.svg'
import room from '../../pwa/src/assets/scene-room.svg'
import food from '../../pwa/src/assets/scene-food.svg'
import table from '../../pwa/src/assets/scene-table.svg'
import stage from '../../pwa/src/assets/scene-stage.svg'
import stadium from '../../pwa/src/assets/scene-stadium.svg'
import car from '../../pwa/src/assets/scene-car.svg'
import cinema from '../../pwa/src/assets/scene-cinema.svg'
import jacket from '../../pwa/src/assets/scene-jacket.svg'
import torn from '../../pwa/src/assets/torn-lisbon.svg'
import stampPlane from '../../pwa/src/assets/stamp-plane.svg'
import stampHotel from '../../pwa/src/assets/stamp-hotel.svg'
import stampDining from '../../pwa/src/assets/stamp-dining.svg'
import stampGift from '../../pwa/src/assets/stamp-gift.svg'
import stampTicket from '../../pwa/src/assets/stamp-ticket.svg'
import stampCar from '../../pwa/src/assets/stamp-car.svg'
import stampBag from '../../pwa/src/assets/stamp-bag.svg'
import stampBalloon from '../../pwa/src/assets/stamp-balloon.svg'
import stampMusic from '../../pwa/src/assets/stamp-music.svg'
import stampTakeaway from '../../pwa/src/assets/stamp-takeaway.svg'
export const ART = { flight, lisbon, pool, room, food, table, stage, stadium, car, cinema, jacket, torn, stampPlane, stampHotel, stampDining, stampGift, stampTicket, stampCar, stampBag, stampBalloon, stampMusic, stampTakeaway } as Record<string, string>
