/* Every word the kit itself prints. Content (flight names, answers, offers) comes from the agent and the bank, already in
   the customer's language. `en` is the base; other packs override keys and fall back to `en` for anything missing.
   The Arabic pack is a working draft for layout and must be reviewed by a native writer before launch. */

export const STRINGS: Record<string, Record<string, string>> = {
  en: {
    ask: 'Ask Gratifi anything', askLabel: 'Ask Gratifi', listening: 'Listening', stopListening: 'Stop listening', speak: 'Speak', send: 'Send',
    working: 'Gratifi is working', fromGratifi: 'From Gratifi', yourNote: 'Your note',
    chatNow: 'Chat now', callMe: 'Call me', handoffWho: '{name} from the {role}', handoffHas: 'Already has this conversation', handoffNote: 'You won\'t need to repeat anything. {name} can see what we\'ve covered.',
    add: 'Add', added: 'Added', yes: 'Yes', no: 'No', bestForYou: 'Best for you', sort: 'Sort', best: 'Best', seeAll: 'See all',
    prevMonth: 'Previous month', nextMonth: 'Next month', nights: '{n} nights', pickReturn: 'Pick your return day', cheapest: 'Green marks the cheapest days', cheapestA11y: 'cheapest', fromPrice: 'from {p}',
    dow: 'M,T,W,T,F,S,S',
    adults: 'Adults', adultsSub: '12 and over', children: 'Children', childrenSub: '2 to 11', infants: 'Infants', infantsSub: 'Under 2, on a lap', infantNote: 'One infant per adult. Infants sit on your lap and fly for a reduced fare.',
    fewer: 'Fewer {x}', more: 'More {x}',
    points: 'Points', pointsAndCard: 'Points and card', card: 'Card', payWith: 'Pay with', ptsHave: '{pts} · you have {bal}', ptsShort: '{pts} · {n} more than you have', ptsPlus: '{pts} + {cash}', onCardEnding: '{cash} on card ending {card}',
    ptsN: '{n} points', orPts: 'or {n} points', onYourCard: 'On your card', youHave: 'You have {bal} points', pointRate: '1 point = {v}', pointsToUse: 'Points to use',
    confirmPay: 'Confirm and pay', payFaceId: 'Pay with Face ID', payApp: 'Approve in your banking app', checking: 'Checking it\'s you…', nothingPaid: 'Nothing is paid until you confirm', booked: 'Booked', close: 'Close',
    otpSent: 'Enter the 6-digit code sent to your phone ending {d}', otpResend: 'Send a new code', otpDigit: 'Digit {n}', confirmWithCode: 'Confirm {amt}', appSent: 'We\'ve sent a request to your banking app. Approve it there to finish.',
    sendTo: 'Send to', chosen: '{n} chosen', done: 'Done',
    direct: 'Direct', stop1: '1 stop', stopsN: '{n} stops', leftAtPrice: '{n} left at this price', economy: 'Economy', included: 'Included',
    you: 'You', extraLegroom: 'Extra legroom {p}', free: 'Free', seatA11y: 'Seat {id}', taken: 'taken', adultsOnly: 'exit row, adults only', takenKey: 'Taken', exit: 'EXIT',
    smallBag: 'Small bag', smallBagSub: 'Fits under the seat', cabinBag: 'Cabin bag', cabinBagSub: 'Overhead, up to {kg}kg', checkedBag: 'Checked bag', checkedBagSub: 'Up to {kg}kg', removeX: 'Remove {x}', addX: 'Add {x}',
    boards: 'Boards', gate: 'Gate', seat: 'Seat', group: 'Group', passenger: 'Passenger', boardingCode: 'Boarding code', departs: 'Departs', lands: 'Lands',
    cancelled: 'Cancelled', requestRefund: 'Request refund', moveMe: 'Move me to this flight', rebookingOptions: 'Rebooking options',
    changeOutbound: 'Change your outbound', bookedLabel: 'Booked', newLabel: 'New', changeFee: 'Change fee', freeOnFare: 'Free on your fare', fareDiff: 'Fare difference', toPay: 'To pay', changeFor: 'Change for {p}',
    yourFare: 'Your fare: {f}', ifPlansChange: 'If your plans change', total: 'total', nightsTaxes: '{n} nights, taxes in', save: 'Save', saved: 'Saved', full: 'Full',
    seatsN: '{n} seats', loungePass: 'Lounge pass', youPlus: 'You + {n} guest',
    paymentDue: 'Payment due', minBy: 'Minimum {amt} by {date}', minPaid: 'Minimum paid. Pay the rest by {date} to avoid interest on it', inDays: 'In {n} days', payNow: 'Pay now', setUp: 'Set up {dd}', ddPays: '{dd} pays the full balance on {date}',
    home: 'Home', rewards: 'Rewards', trips: 'Trips', me: 'Me', main: 'Main', alerts: 'Alerts', back: 'Back', moreL: 'More', goodMorning: 'Good morning', goodAfternoon: 'Good afternoon', goodEvening: 'Good evening',
    working2: 'Working', finished: 'Finished',
    nOfBooked: '{a} of {b} booked', toBook: 'To book', standardFare: 'Standard', appReady: 'Tap below and we\'ll send a request to your banking app.', wrongCode: 'That code isn\'t right. Check the text message and try again.', codeLocked: 'Too many wrong codes, so codes are paused. Try again in {n} min, or call the bank if it can\'t wait.', appWaiting: 'Waiting for you to approve it in your banking app…', otpResent: 'A new code is on its way.', wrongCodeLast: 'That code isn\'t right. One more wrong code pauses codes for 15 minutes.', youGetBack: 'You get back', confirmPts: 'Confirm {pts}',
    inDays_one: 'Tomorrow', youPlus_other: 'You + {n} guests', nights_one: '1 night', stopsN_one: '1 stop',
  },
  ar: {
    ask: 'اسأل Gratifi أي شيء', askLabel: 'اسأل Gratifi', listening: 'أستمع إليك', stopListening: 'إيقاف الاستماع', speak: 'تحدّث', send: 'إرسال',
    working: 'Gratifi يعمل على طلبك', fromGratifi: 'من Gratifi', yourNote: 'ملاحظتك',
    chatNow: 'دردشة الآن', callMe: 'اتصلوا بي', handoffWho: '{name} من {role}', handoffHas: 'اطّلعت على المحادثة', handoffNote: 'لن تحتاج إلى تكرار أي شيء، فستطّلع {name} على كل ما ناقشناه.',
    add: 'إضافة', added: 'أُضيف', yes: 'نعم', no: 'لا', bestForYou: 'الأنسب لك', sort: 'ترتيب', best: 'الأفضل', seeAll: 'عرض الكل',
    prevMonth: 'الشهر السابق', nextMonth: 'الشهر التالي', nights: '{n} ليالٍ', pickReturn: 'اختر يوم العودة', cheapest: 'الأيام الأرخص باللون الأخضر', cheapestA11y: 'الأرخص', fromPrice: 'من {p}',
    dow: 'ن,ث,ر,خ,ج,س,ح',
    adults: 'البالغون', adultsSub: '12 سنة فأكثر', children: 'الأطفال', childrenSub: 'من 2 إلى 11', infants: 'الرضّع', infantsSub: 'أقل من سنتين، في الحضن', infantNote: 'رضيع واحد لكل بالغ. يجلس الرضيع في حضنك بسعر مخفّض.',
    fewer: 'تقليل {x}', more: 'زيادة {x}',
    points: 'النقاط', pointsAndCard: 'نقاط وبطاقة', card: 'البطاقة', payWith: 'الدفع عبر', ptsHave: '{pts} · لديك {bal}', ptsShort: '{pts} · ينقصك {n}', ptsPlus: '{pts} + {cash}', onCardEnding: '{cash} على البطاقة المنتهية بـ {card}',
    ptsN: '{n} نقطة', orPts: 'أو {n} نقطة', onYourCard: 'على بطاقتك', youHave: 'لديك {bal} نقطة', pointRate: 'النقطة = {v}', pointsToUse: 'النقاط المستخدمة',
    confirmPay: 'التأكيد والدفع', payFaceId: 'الدفع عبر Face ID', payApp: 'الموافقة في تطبيق البنك', checking: 'نتحقق من هويتك…', nothingPaid: 'لن يُدفع شيء قبل تأكيدك', booked: 'تم الحجز', close: 'إغلاق',
    otpSent: 'أدخل الرمز المكوّن من 6 أرقام المرسل إلى هاتفك المنتهي بـ {d}', otpResend: 'إرسال رمز جديد', otpDigit: 'الرقم {n}', confirmWithCode: 'تأكيد {amt}', appSent: 'أرسلنا طلبًا إلى تطبيق البنك. وافق عليه هناك لإتمام العملية.',
    sendTo: 'إرسال إلى', chosen: 'تم اختيار {n}', done: 'تم',
    direct: 'مباشرة', stop1: 'توقف واحد', stopsN: '{n} توقفات', leftAtPrice: 'بقي {n} بهذا السعر', economy: 'الدرجة السياحية', included: 'مشمول',
    you: 'أنت', extraLegroom: 'مساحة إضافية للساقين {p}', free: 'مجانًا', seatA11y: 'المقعد {id}', taken: 'محجوز', adultsOnly: 'صف الطوارئ، للبالغين فقط', takenKey: 'محجوز', exit: 'مخرج',
    smallBag: 'حقيبة صغيرة', smallBagSub: 'تحت المقعد', cabinBag: 'حقيبة المقصورة', cabinBagSub: 'في الخزانة العلوية، حتى {kg} كغ', checkedBag: 'حقيبة مشحونة', checkedBagSub: 'حتى {kg} كغ', removeX: 'إزالة {x}', addX: 'إضافة {x}',
    boards: 'وقت الصعود', gate: 'البوابة', seat: 'المقعد', group: 'المجموعة', passenger: 'المسافر', boardingCode: 'رمز الصعود', departs: 'المغادرة', lands: 'الوصول',
    cancelled: 'أُلغيت', requestRefund: 'طلب استرداد', moveMe: 'انقلني إلى هذه الرحلة', rebookingOptions: 'خيارات إعادة الحجز',
    changeOutbound: 'تغيير رحلة الذهاب', bookedLabel: 'المحجوز', newLabel: 'الجديد', changeFee: 'رسوم التغيير', freeOnFare: 'مجانًا على تذكرتك', fareDiff: 'فرق السعر', toPay: 'المطلوب دفعه', changeFor: 'التغيير مقابل {p}',
    yourFare: 'تذكرتك: {f}', ifPlansChange: 'إذا تغيّرت خططك', total: 'الإجمالي', nightsTaxes: '{n} ليالٍ، شامل الضرائب', save: 'حفظ', saved: 'محفوظ', full: 'ممتلئ',
    seatsN: '{n} مقاعد', loungePass: 'تصريح الصالة', youPlus: 'أنت + {n} ضيف',
    paymentDue: 'الدفعة المستحقة', minBy: 'الحد الأدنى {amt} بحلول {date}', minPaid: 'تم دفع الحد الأدنى. ادفع الباقي بحلول {date} لتجنّب الفوائد عليه', inDays: 'خلال {n} أيام', payNow: 'ادفع الآن', setUp: 'تفعيل {dd}', ddPays: 'يسدّد {dd} الرصيد كاملًا في {date}',
    home: 'الرئيسية', rewards: 'المكافآت', trips: 'الرحلات', me: 'حسابي', main: 'الرئيسية', alerts: 'التنبيهات', back: 'رجوع', moreL: 'المزيد', goodMorning: 'صباح الخير', goodAfternoon: 'مساء الخير', goodEvening: 'مساء الخير',
    working2: 'قيد العمل', finished: 'اكتمل',
    nOfBooked: 'تم حجز {a} من {b}', toBook: 'للحجز', standardFare: 'العادية', appReady: 'اضغط أدناه وسنرسل طلبًا إلى تطبيق البنك.', wrongCode: 'الرمز غير صحيح. تحقق من الرسالة وحاول مجددًا.', codeLocked: 'محاولات خاطئة كثيرة، لذا أُوقفت الرموز. حاول مجددًا بعد {n} دقيقة، أو اتصل بالبنك إن كان الأمر عاجلًا.', appWaiting: 'بانتظار موافقتك في تطبيق البنك…', otpResent: 'رمز جديد في الطريق إليك.', wrongCodeLast: 'الرمز غير صحيح. رمز خاطئ آخر سيوقف الرموز لمدة 15 دقيقة.', youGetBack: 'المبلغ المسترد', confirmPts: 'تأكيد {pts}',
    nights_one: 'ليلة واحدة', nights_two: 'ليلتان', inDays_one: 'غدًا', inDays_two: 'خلال يومين', stopsN_two: 'توقفان', youPlus_two: 'أنت + ضيفان',
  },
}
