const { open } = require('./h.js');
(async () => { const h = await open('UK', { tag: 'a11y' }); const { p } = h;
 await h.nav(3); await h.ask('Skincare set', 800); await h.last().locator('.gr-itemrow').first().click(); await p.waitForTimeout(300); await h.last().locator('.gr-detail .gr-btn').last().click(); await p.waitForTimeout(400);
 await h.btn(/^Pay /).click(); await p.waitForTimeout(500);
 console.log(await p.evaluate(() => { const s = document.querySelector('.app-sheet'); const d = s.closest('[role=dialog]') || s.querySelector('[role=dialog]') || (s.getAttribute('role') === 'dialog' ? s : null); return { role: d && d.getAttribute('role'), modal: d && d.getAttribute('aria-modal'), label: d && (d.getAttribute('aria-labelledby') || d.getAttribute('aria-label')), active: document.activeElement && (document.activeElement.outerHTML.slice(0, 120)), inertMain: document.querySelector('.app-main').inert || document.querySelector('.app-main').closest('[inert]') !== null, lang: document.documentElement.lang } }));
 for (let i = 0; i < 8; i++) { await p.keyboard.press('Tab'); } console.log('focus after tabs:', await p.evaluate(() => document.activeElement.closest('.app-sheet') ? 'in sheet' : document.activeElement.outerHTML.slice(0, 100)));
 await p.keyboard.press('Escape'); await p.waitForTimeout(300); console.log('sheet after esc', !!(await p.$('.app-sheet')), 'focus', await p.evaluate(() => document.activeElement.outerHTML.slice(0, 100)));
 // contrast sample
 console.log(await p.evaluate(() => { const lum = c => { const m = c.match(/[\d.]+/g).map(Number); const f = v => { v /= 255; return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4) }; return 0.2126 * f(m[0]) + 0.7152 * f(m[1]) + 0.0722 * f(m[2]) }; const bgOf = el => { while (el) { const b = getComputedStyle(el).backgroundColor; if (b && !/rgba\(0, 0, 0, 0\)|transparent/.test(b)) return b; el = el.parentElement } return 'rgb(255,255,255)' }; const out = {}; const sel = { pts: '.gr-pts, [class*=pts]', meta: '.gr-meta', sub: '.gr-sub' }; for (const [k, s] of Object.entries(sel)) { const el = document.querySelector(s); if (!el) { out[k] = 'none'; continue } const a = lum(getComputedStyle(el).color), b = lum(bgOf(el)); out[k] = getComputedStyle(el).color + ' on ' + bgOf(el) + ' = ' + ((Math.max(a, b) + 0.05) / (Math.min(a, b) + 0.05)).toFixed(2) + ' size ' + getComputedStyle(el).fontSize } return out }));
 const unl = await p.evaluate(() => [...document.querySelectorAll('button')].filter(b => !b.innerText.trim() && !b.getAttribute('aria-label')).map(b => b.outerHTML.slice(0, 80)));
 console.log('unlabelled buttons', unl.length, unl.slice(0, 5));
 const imgs = await p.evaluate(() => [...document.querySelectorAll('img')].filter(i => !i.hasAttribute('alt')).length); console.log('img no alt', imgs);
 await h.close() })();
