const P = f => '(' + f.toString() + ')';
module.exports = {
 v1: { q: 'gift card', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'GC-0', option: '50', recipient: 'Sam', email: 'not-an-email' }); return 'Confirm.' }) },
 v2: { q: 'gift card', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'GC-0', option: '50', recipient: 'Sam' }); return 'Confirm.' }) },
 v3: { q: 'gift card', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'GC-0', option: '37', recipient: 'Sam', email: 'sam@example.com' }); return 'Confirm.' }) },
 v4: { q: 'jacket', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'SH-4' }); return 'Confirm.' }) },
 v5: { q: 'jacket', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'SH-4', option: 'XXL' }); return 'Confirm.' }) },
 v6: { q: 'headphones', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'SH-1', option: 'Black', quantity: 1.5 }); return 'Confirm.' }) },
 v7: { q: 'headphones', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'SH-1', option: 'Black', quantity: 500 }); return 'Confirm.' }) },
 v8: { q: 'hotel', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'ST-Lisbon-0', date: '2026-02-30', nights: 2 }); return 'Confirm.' }) },
 v9: { q: 'hotel', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'ST-Lisbon-0', date: '2026-09-20', nights: 2 }); return 'Confirm.' }) },
 v10: { q: 'hotel', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'ST-Lisbon-0', date: '2026-10-20', nights: 45 }); return 'Confirm.' }) },
 v11: { q: 'hotel', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'ST-Lisbon-0', date: '2026-10-20', nights: 3, quantity: 5, option: 'Suite' }); return 'Confirm.' }) },
 v12: { q: 'table', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'DN-London-0', quantity: 13, date: '2026-10-03', option: '19:00' }); return 'Confirm.' }) },
 v13: { q: 'table', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'DN-London-0', quantity: 2, date: '2026-10-03', option: '03:00' }); return 'Confirm.' }) },
 v14: { q: 'cinema', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'ET-4', quantity: 3, option: '19:15' }); return 'Confirm.' }) },
 v15: { q: 'cinema', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'ET-4', quantity: 2, option: '19:15', date: '2026-10-20' }); return 'Confirm.' }) },
 v16: { q: 'cinema', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'ET-4', quantity: 2, option: '17:40', date: '2026-10-01' }); return 'Confirm.' }) },
 v17: { q: 'ride', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'GT-1', destination: 'Manchester' }); return 'Confirm.' }) },
 v18: { q: 'ride', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'GT-1', destination: 'airport', date: '2026-10-02', pickup_time: '06:00', pickup: 'home' }); return 'Confirm.' }) },
 v19: { q: 'ride', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'GT-1', destination: 'office', pickup_time: '25:00', date: '2026-10-02' }); return 'Confirm.' }) },
 v20: { q: 'car hire', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'GT-4', days: 4 }); return 'Confirm.' }) },
 v21: { q: 'car hire', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'GT-4', days: 3 }); return 'Confirm.' }) },
 v22: { q: 'lounge', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'AP-1', quantity: 5 }); return 'Confirm.' }) },
 v23: { q: 'flights', plan: P(async (t, o, run) => { await run('search_flights', { destination: 'Lisbon', depart_date: '2026-10-09', travellers: 1, children: 1 }); return 'x' }) },
 v24: { q: 'flights', plan: P(async (t, o, run) => { await run('search_flights', { destination: 'Lisbon', depart_date: '2026-10-09', travellers: 1, infants: 2 }); return 'x' }) },
 v25: { q: 'flights', plan: P(async (t, o, run) => { await run('search_flights', { destination: 'Lisbon', depart_date: '2026-10-09', return_date: '2026-10-05', travellers: 2 }); return 'x' }) },
 v26: { q: 'flights', plan: P(async (t, o, run) => { await run('search_flights', { destination: 'Lisbon', depart_date: '2025-10-09', travellers: 2 }); return 'x' }) },
 v27: { q: 'points', plan: P(async (t, o, run) => { await run('points_and_giving', { topic: 'invest', points: 900000, to: 'gold' }); return 'x' }) },
 v28: { q: 'points', plan: P(async (t, o, run) => { await run('points_and_giving', { topic: 'transfer', points: 10000, to: 'Northwind' }); return 'x' }) },
 v29: { q: 'points', plan: P(async (t, o, run) => { await run('points_and_giving', { topic: 'donate', points: 500, to: 'Clean Seas' }); return 'x' }) },
 v30: { q: 'subs', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'SB-1', option: 'Premium 4K (+£5)' }); return 'x' }) },
 v31: { q: 'train', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'GT-R1', option: '07:15', quantity: 2, date: '2026-10-01' }); return 'x' }) },
 v32: { q: 'groceries', plan: P(async (t, o, run) => { await run('groceries', { items: '5 paracetamol, 2 milk, ibuprofen' }); return 'x' }) },
 v33: { q: 'experience', plan: P(async (t, o, run) => { const r = await run('search_catalogue', { category: 'experiences', city: 'Lisbon' }); await run('prepare_checkout', { id: r.data[0].id, quantity: 0 }); return 'x' }) },
 v34: { q: 'table', plan: P(async (t, o, run) => { await run('prepare_checkout', { id: 'DN-London-0', quantity: 2, date: '2026-10-01', option: '18:30' }); return 'x' }) },
};
