const { chromium } = require('/home/claude/.npm-global/lib/node_modules/playwright');
const R = '/tmp/claude-0/-home-claude/d2529b2f-e36e-5c22-8d08-213fa2f214ae/scratchpad/gratifi/review/';
exports.start = async (market = 'UK', theme = 'light', extra = '', file = 'test.html') => {
  const b = await chromium.launch();
  const ctx = await b.newContext({ viewport: { width: 420, height: 880 }, deviceScaleFactor: 1 });
  const p = await ctx.newPage();
  const errs = []; p.on('pageerror', e => errs.push('PAGE ' + e.message)); p.on('console', m => { if (m.type() === 'error') errs.push('CON ' + m.text()) });
  const url = (x = '') => `file://${R}${file}?m=${market}&theme=${theme}${x}`;
  await p.goto(url(extra)); await p.evaluate(() => localStorage.clear()); await p.goto(url(extra)); await p.waitForTimeout(500);
  let n = 0; const tag = market + (theme === 'dark' ? 'd' : '');
  const shot = async (name) => { await p.waitForTimeout(300); const f = `${process.env.SD || 'shots'}/${tag}-${String(++n).padStart(2, '0')}-${name}.png`; await p.screenshot({ path: f }); return f };
  const full = async (name) => { await p.waitForTimeout(350); const el = await p.$('.app-main .app-scroll'); const h = el ? await el.evaluate(e => e.scrollHeight) : 880; await p.setViewportSize({ width: 420, height: Math.min(7000, h + 200) }); await p.waitForTimeout(250); if (el) await el.evaluate(e => e.scrollTop = e.scrollHeight); const f = `${process.env.SD || 'shots'}/${tag}-${String(++n).padStart(2, '0')}-${name}.png`; await p.screenshot({ path: f }); await p.setViewportSize({ width: 420, height: 880 }); return f };
  const nav = async (i) => { await p.click(`.gr-nav button:nth-child(${i})`); await p.waitForTimeout(300) };
  const ask = async (t) => { await p.fill('.gr-ask input', t); await p.press('.gr-ask input', 'Enter'); await p.waitForTimeout(600) };
  const btn = async (name, opt = {}) => { const l = p.getByRole('button', { name, exact: !!opt.exact }).last(); await l.scrollIntoViewIfNeeded(); await l.click(); await p.waitForTimeout(400) };
  const st = () => p.evaluate(() => JSON.parse(localStorage.getItem('gratifi-state-v3-' + new URLSearchParams(location.search).get('m'))));
  const lastText = () => p.evaluate(() => { const a = [...document.querySelectorAll('.gr-answer')]; return a.length ? a[a.length - 1].innerText : '' });
  const sheetText = () => p.evaluate(() => { const s = document.querySelector('.app-sheet'); return s ? s.innerText : null });
  const confirm = async (code = '482193') => { await p.waitForTimeout(300); const s = await p.$('.app-sheet'); if (!s) { errs.push('NO SHEET'); return false } const ins = await p.$$('.app-sheet input'); if (ins.length >= 6) { for (let i = 0; i < 6; i++) await ins[i].fill(code[i]) } else if (ins.length) await ins[0].fill(code); await p.locator('.app-sheet .gr-btn').last().click(); await p.waitForTimeout(2900); return true };
  const summ = async () => { const s = await st(); if (!s) return null; return { pts: s.balance, card: s.card.balance, bookings: s.bookings.map(b => `${b.ref}|${b.cat}|${b.title}|${b.status}|pts${b.pts}|card${b.card}|earn${b.earned}`), ledger: s.ledger.slice(0, 6).map(l => `${l.label}:${l.pts}`), txns: s.txns.slice(0, 4).map(t => `${t.merchant}:${t.amount}${t.refund ? 'R' : ''}${t.pending ? 'P' : ''}`) } };
  return { b, p, errs, shot, full, nav, ask, btn, st, lastText, sheetText, confirm, summ, url };
};
