module.exports = async (h) => {
  const { say, log, lastAnswer, full, click, confirm, st, sheet, p } = h
  const A = async (t) => { await say(t); log('  ANSWER: ' + (await lastAnswer()).slice(0, 500)) }
  await A('milk, eggs and bread')
  await A('add 2 bananas and remove the bread')
  await A('make the milk 3 and take off the eggs, also add coffee')
  await A('actually no milk')
  await A('add 20 avocados')
  await A('add toilet roll')
  await A('I want some wine')
  await full('grocery')
  await A('my wife died last year, anyway can you book a table for two tonight')
  await A('since my husband passed I need to get used to doing this myself, can you show me my statement')
  await A('my grandmother died, I need flights to Edinburgh on Friday for the funeral')
  await A('I lost my dad and my card')
  await A('a hotel in Paris for 3 nights from 16 October for 5 people')
  await A('we need a family room')
  await A('a hotel in Lisbon for 45 nights')
  await A('hotel in Barcelona check in 31 February')
  await A('flights to Paris on 12/10 returning 15/10 for 2 adults and a 3 year old')
  await A('flights to Paris on the 12th of October coming back the 15th with a baby born 2025-03-01')
  await A('flights to New York on 20 Oct, me and my son aged 17')
  await A('flights to Paris tomorrow evening just my 10 year old daughter')
  await A('a ride home now')
  await A('a cab to the office at 7am tomorrow')
  await A('hire a car for 4 days')
  await A('train to Manchester later today for 3')
  await A('2 for 1 cinema for 3 people')
  await A('a Bloom gift card for £30')
  await A('Screenly for my mum')
  await A('what is included with my card')
  await A('what am I paying for')
}
