module.exports = async (H) => { const { p, nav, say, click } = H;
 const r = await p.evaluate(() => { const out = {}; out.nav = [...document.querySelectorAll('.gr-nav button')].map(b => b.getAttribute('aria-label') || b.innerText); out.unlabelledButtons = [...document.querySelectorAll('button')].filter(b => !(b.innerText.trim() || b.getAttribute('aria-label') || b.getAttribute('title'))).length; out.imgsNoAlt = [...document.querySelectorAll('img')].filter(i => !i.hasAttribute('alt')).length; out.svgs = document.querySelectorAll('svg:not([aria-hidden])').length; out.inputsNoLabel = [...document.querySelectorAll('input,textarea')].filter(i => !(i.getAttribute('aria-label') || i.labels?.length || i.placeholder)).length; out.lang = document.documentElement.lang; out.h1 = [...document.querySelectorAll('h1,h2')].map(h => h.innerText).slice(0, 5); out.small = [...document.querySelectorAll('button, a, [role=switch]')].filter(b => { const x = b.getBoundingClientRect(); return x.width > 0 && (x.height < 24 || x.width < 24) }).map(b => (b.innerText || b.getAttribute('aria-label') || '').slice(0, 20)).slice(0, 10); return out });
 console.log('HOME', JSON.stringify(r));
 await nav(3); await say('pay my bill'); await p.getByRole('button', { name: /^Pay |^ادفع/ }).last().click(); await p.waitForTimeout(600);
 const d = await p.evaluate(() => { const s = document.querySelector('.app-sheet'); const dlg = s?.closest('[role=dialog]') || document.querySelector('[role=dialog]'); return { role: dlg?.getAttribute('role'), modal: dlg?.getAttribute('aria-modal'), label: dlg?.getAttribute('aria-labelledby') || dlg?.getAttribute('aria-label'), focusIn: dlg?.contains(document.activeElement), focused: document.activeElement?.innerText?.slice(0, 30) || document.activeElement?.tagName, inert: [...document.querySelectorAll('[inert]')].map(e => e.className.toString().slice(0, 30)) } }); console.log('DIALOG', JSON.stringify(d));
 await p.keyboard.press('Tab'); await p.keyboard.press('Tab'); await p.keyboard.press('Tab'); await p.keyboard.press('Tab'); console.log('after tabs focus in dialog:', await p.evaluate(() => !!document.activeElement.closest('[role=dialog]')));
 await p.keyboard.press('Escape'); await p.waitForTimeout(400); console.log('after esc sheet', await H.sheet(), 'focus', await p.evaluate(() => document.activeElement?.innerText?.slice(0, 30) || document.activeElement?.tagName));
 const live = await p.evaluate(() => [...document.querySelectorAll('[aria-live]')].map(e => e.getAttribute('aria-live') + ':' + e.className.toString().slice(0, 30))); console.log('LIVE', live);
 const sw = await p.evaluate(() => [...document.querySelectorAll('[role=switch]')].slice(0, 3).map(e => e.getAttribute('aria-checked') + ':' + (e.getAttribute('aria-label') || e.getAttribute('aria-labelledby') || e.innerText))); console.log('SWITCHES', sw);
}
