module.exports = async (H) => { const { p, nav, full, click, confirm, state } = H; await nav(3);
 const say = async (q) => { const r = await H.say(q); const sh = await H.sheet(); if (sh) { console.log('  AUTO-SHEET:', sh.slice(0,300)); await confirm(); console.log('  AFTER CONFIRM:', (await H.last()).slice(-300)) } return r };
 const S = async (t) => { const s = await state(); if (s) console.log(`STATE ${t}: card=${s.card.balance} due=${s.card.due} min=${s.card.min} limit=${s.card.limit} dd=${JSON.stringify(s.card.dd || s.card.autopay || null)} gamb=${s.card.gambling}`) };
 await say('pay £100'); await full('pay100');  await S('after £100');
 await say('what do I owe?'); await say('pay the minimum');
 await say('set up a direct debit for the minimum'); const b = p.locator('.gr-answer').last().getByRole('button', { name: /Set up|Confirm|Direct Debit/ }); if (await b.count()) { await b.last().click(); await p.waitForTimeout(400); console.log('DD SHEET', await confirm()) } await S('after dd');
 await say('change my direct debit to the full balance'); const b2 = p.locator('.gr-answer').last().getByRole('button', { name: /Change|Confirm|Switch|full/i }); if (await b2.count()) { await b2.last().click(); await p.waitForTimeout(400); console.log('DD2 SHEET', await confirm()) } await S('after dd2');
 await say('cancel my direct debit'); const b3 = p.locator('.gr-answer').last().getByRole('button', { name: /Cancel|Stop|Turn off/i }); if (await b3.count()) { await b3.last().click(); await p.waitForTimeout(400); console.log('DD3 SHEET', await confirm()) } await S('after dd3');
 await say('block gambling'); const g = p.locator('.gr-answer').last().getByRole('button', { name: /Turn on|Block/i }); if (await g.count()) { await g.last().click(); await p.waitForTimeout(400); console.log('G SHEET', await confirm()) } await S('after gamb');
 await say('remove the gambling block'); await full('gamb-lift'); const g2 = p.locator('.gr-answer').last().getByRole('button', { name: /Lift|Remove|Turn off|Start/i }); if (await g2.count()) { await g2.last().click(); await p.waitForTimeout(400); console.log('G2 SHEET', await confirm()) } await S('after gamb lift'); await say('keep the block'); await S('after keep');
 for (const q of ['what is my credit limit', 'lower my limit to £5000', 'increase my limit', 'send me my statement', 'how much did I spend on dining last month', 'why was my card declined', 'will my card work in Spain', 'do you charge foreign transaction fees', 'can I take cash out abroad', 'I was charged twice at Pantry Market', 'I cancelled Cloudbox but they still charged me', 'Byte Store never refunded my return', 'activate my new card', 'add my card to Apple Pay', 'when does my card expire', 'my new card hasn\'t arrived', 'can I do a balance transfer', 'unfreeze my card', 'turn off online payments', 'I left my card at home', 'the ATM swallowed my card', 'my card is snapped in half', 'my card was stolen', 'I want to dispute a charge', 'I paid for a sofa and it never arrived', 'split my laptop purchase into instalments', 'add my wife as a cardholder', 'I moved house', 'remind me when my bill is due', 'show my alerts']) await say(q);
 await nav(5); await full('mycard');
}
