# Extra flight rows written to close coverage gaps found by the checker.
def r(item, stage, job, constraint, exception, says, does, blocks, rules, markets='', vol=3, val=3, risk=2):
    return dict(item=item, stage=stage, job=job, constraint=constraint, exception=exception, says=says, does=does, blocks=blocks, rules=rules, markets=markets, vol=vol, val=val, risk=risk)

CASES = [
 # FL-02 multi-city, open jaw, groups
 r('FL-02', 'Search', 'Book a multi-city trip', 'Stopover', '', 'London to Singapore with 3 nights in Dubai on the way', 'Prices the stopover as one ticket and shows the extra cost of the stop', 'Itinerary, FlightCard, PriceLines', 'Fare construction by supplier; stopover rules from the fare', '', 2, 4, 2),
 r('FL-02', 'Choose', 'Book a multi-city trip', 'Several stops', 'One leg sold out', 'Book the three flights we planned', 'Says which leg has gone, offers the nearest alternative for that leg only, keeps the rest', 'Itinerary, StateCard (soldout), FlightCard', 'Never book part of a multi-city trip without a new yes', '', 2, 3, 3),
 r('FL-02', 'Pay', 'Book a multi-city trip', 'Separate tickets', 'Second ticket fails', '(confirms)', 'First ticket booked, second failed: explains, offers to retry or cancel the first within its free window', 'StateCard (error), Receipt, Handoff', 'Pair separate tickets only with a clear warning; void window from the supplier', '', 1, 3, 5),
 r('FL-02', 'Search', 'Search for a group', '10 or more', '', 'Flights for our team of 14 to Goa', 'Explains group fares, collects names later, hands to the group desk', 'Travellers, Answer, Handoff', 'Group bookings over 9 go to the group desk', '', 2, 4, 2),
 r('FL-02', 'Pay', 'Search for a group', '10 or more', 'Names not ready', 'I\'ll send the names next week', 'Holds the group fare if the airline allows and sets a reminder for the name deadline', 'StateCard, Toast', 'Name deadline and deposit from the airline', '', 1, 3, 3),
 r('FL-02', 'Before', 'Change a multi-city trip', 'Middle leg', '', 'Stay two more nights in Dubai', 'Prices changing the middle leg and shows the difference', 'ChangeFlight, Itinerary', 'Change rules apply per fare component', '', 1, 3, 3),
 # FL-03 award seats and upgrades
 r('FL-03', 'Search', 'Find award seats', 'Points only', '', 'Business class to Singapore with my airline miles', 'Shows award seat availability and the miles and taxes needed', 'FlightCard, FareFamilies, Price', 'Award space from the airline or partner feed only', 'Award programmes and partners differ per bank and market', 2, 5, 2),
 r('FL-03', 'Search', 'Find award seats', 'Flexible dates', '', 'Any day in March with award seats for two', 'Calendar of days with two award seats', 'PriceCalendar', 'Award space changes by the minute; confirm before transfer', '', 2, 4, 2),
 r('FL-03', 'Choose', 'Find award seats', 'Need a transfer first', '', 'I have bank points, not miles', 'Shows the transfer needed, the rate, how long it takes, and warns it cannot be undone', 'Answer, PriceLines, ConfirmSheet', 'Never transfer before checking award space is still there', '', 2, 5, 4),
 r('FL-03', 'Pay', 'Find award seats', 'Transfer done', 'Seat gone after transfer', '(after transfer)', 'Says the seat went before booking, offers other dates; miles stay in the airline account', 'StateCard (soldout), Handoff', 'Transfers are final; say so before, not after', '', 1, 3, 5),
 r('FL-03', 'Add-ons', 'Upgrade with points', 'Booked', 'No upgrade space', 'Upgrade me to business', 'Says no space now, offers a waitlist or alert if the airline supports it', 'StateCard, Toggle', 'Upgrade inventory from the airline', '', 2, 3, 2),
 r('FL-03', 'Add-ons', 'Upgrade with points', 'Bid upgrade', '', 'Can I bid for an upgrade?', 'Explains the airline\'s bid scheme and places a bid in points or cash', 'Answer, PointsSlider, ConfirmSheet', 'Bid rules from the airline; charged only if accepted', '', 1, 3, 3),
 r('FL-03', 'Before', 'Cancel an award booking', 'Plans changed', '', 'Cancel my award flight', 'Shows the redeposit fee and what comes back as miles', 'FareRules, ConfirmSheet', 'Redeposit fees from the airline programme', '', 1, 3, 3),
 r('FL-03', 'Discover', 'Find award seats', 'Points balance', '', '(Gratifi starts it)', 'Tells them award seats to a saved destination have opened', 'StickyNote, FlightCard', 'Only with alert consent', '', 2, 4, 2),
 # FL-04 ancillaries exceptions
 r('FL-04', 'Add-ons', 'Add bags', 'Checked bag', 'Bag price rose', 'Add a suitcase', 'Shows the new bag price before adding', 'BagPicker, StateCard (price)', 'Re-price before charging', '', 2, 2, 2),
 r('FL-04', 'Add-ons', 'Add meals', 'Dietary', 'Meal not available', 'Vegan meal please', 'Says the airline doesn\'t offer it on this flight and suggests bringing food', 'StateCard', 'Meal list from the airline', '', 1, 2, 2),
 r('FL-04', 'Add-ons', 'Pick seats', 'Paid seat', 'Seat charge failed', '(confirms seat)', 'Says the seat wasn\'t charged or held, offers to try again', 'StateCard (error), SeatMap', 'No seat without payment', '', 1, 2, 2),
 # FL-05 changes and cancellations
 r('FL-05', 'Before', 'Change the date', 'Non-changeable fare', 'Change not allowed', 'Move my flight to Monday', 'Explains the fare doesn\'t allow changes and shows the options: cancel for taxes back, or keep', 'FareRules, StateCard', 'Never promise a change the fare rules forbid', '', 3, 3, 4),
 r('FL-05', 'Before', 'Change the date', 'Before travel', 'Fare difference is higher', 'Move it to Saturday', 'Shows fee plus fare difference; asks to confirm the total', 'ChangeFlight, ConfirmSheet', 'Re-price at confirm', '', 3, 4, 3),
 r('FL-05', 'Before', 'Change the time', 'Same day', '', 'Can I take the earlier flight?', 'Checks same-day change rules and seats, confirms', 'ChangeFlight, ConfirmSheet', 'Same-day change rules from the airline', '', 2, 3, 3),
 r('FL-05', 'Before', 'Cancel the booking', 'Refundable fare', '', 'Cancel and refund', 'Shows refund amount, where it goes (card or points) and when', 'FareRules, ConfirmSheet, Receipt', 'Refund to the original method: points back as points', '', 3, 3, 4),
 r('FL-05', 'Before', 'Cancel the booking', 'Within 24 hours', '', 'I booked the wrong day an hour ago', 'Checks the free cancellation window and cancels in full', 'ConfirmSheet, Receipt', 'Free window depends on airline and market (to confirm)', 'Some markets and airlines give 24-hour free cancellation (to confirm per airline)', 2, 3, 3),
 r('FL-05', 'Before', 'Cancel the booking', 'Travel credit', '', 'Keep it as credit instead', 'Converts to airline credit if allowed and shows expiry', 'Receipt, Toast', 'Credit terms from the airline', '', 2, 3, 3),
 r('FL-05', 'Before', 'Change the date', 'Change request', 'Supplier down', 'Change my flight', 'Says the airline system is not answering, nothing changed, will retry and tell them', 'StateCard (error), Toast', 'No change without supplier confirmation', '', 1, 2, 3),
 r('FL-05', 'Before', 'Add a traveller', 'Booked', '', 'Can my son join the same flight?', 'Books a separate ticket on the same flight and links the bookings', 'FlightCard, Travellers, ConfirmSheet', 'Separate ticket; linked for seats', '', 2, 3, 2),
 # FL-06 day of travel exceptions
 r('FL-06', 'During', 'Show boarding pass', 'At the airport', 'Boarding pass not issued', 'My boarding pass won\'t load', 'Explains why (document check, seat not assigned) and what to do at the desk', 'StateCard, Handoff', 'Reason from the airline', '', 2, 3, 3),
 r('FL-06', 'Before', 'Check in', 'Online', 'Check-in failed', '(automatic)', 'Says online check-in didn\'t work and why, and what to do', 'StateCard, Toast', 'Airline check-in rules', '', 2, 3, 3),
 r('FL-06', 'During', 'Track the flight', 'Live', 'Feeds disagree', '(Gratifi starts it)', 'Shows the airline\'s time and says the airport board may differ', 'FlightTracker, StateCard', 'Airline feed wins; later time shown when feeds disagree', '', 2, 3, 3),
]
