const H = require('./h.js');
(async () => {
  await H.run('ai2', { m: 'UK', fake: true }, async (h) => { const { p, nav, ask, answers, btns, click, log, S, sheet, auth, full } = h;
    await nav(3);
    const plan = async (src) => { await p.evaluate((src) => { window.__plan = eval(src) }, src) };
    const res = async () => JSON.stringify(await p.evaluate(() => (window.__res || []).map(r => typeof r === 'string' ? r : { n: r.n, a: r.a, note: r.r && r.r.note, shown: r.r && r.r.shown_to_customer, data: r.r && r.r.data && JSON.stringify(r.r.data).slice(0, 200) }))).slice(0, 1200);
    const go = async (label, src, q, w = 1500) => { await plan(src); await p.evaluate(() => { window.__res = [] }); await ask(q, w); log(`\n### ${label}\nTOOLS ${await res()}\nUI ${(await answers(1)).replace(/\n/g, ' | ').slice(0, 500)}\nSHEET ${(await sheet() || 'none').replace(/\n/g, ' | ').slice(0, 300)}`); if (await sheet()) { await p.keyboard.press('Escape'); await p.waitForTimeout(400) } };
    await go('qty500', `async (t,o,run)=>{ await run('prepare_checkout',{id:'ET-1',quantity:500}); return 'Confirm with the button.' }`, 'buy 500 tickets');
    await go('qtyneg', `async (t,o,run)=>{ await run('prepare_checkout',{id:'ET-1',quantity:-3}); return 'ok' }`, 'buy -3 tickets');
    await go('qty0', `async (t,o,run)=>{ await run('prepare_checkout',{id:'ET-1',quantity:0.5}); return 'ok' }`, 'buy half ticket');
    await go('opt-bad', `async (t,o,run)=>{ await run('prepare_checkout',{id:'ET-1',option:'VIP box'}); return 'ok' }`, 'vip box');
    await go('gift-amt', `async (t,o,run)=>{ const r=await run('search_catalogue',{category:'giftcards'}); const id=r.data[0].id; await run('prepare_checkout',{id, option:'1234', recipient:'Sam', email:'sam@x.com'}); return 'ok' }`, 'gift card 1234');
    await go('gift-noemail', `async (t,o,run)=>{ const r=await run('search_catalogue',{category:'giftcards'}); const id=r.data[0].id; await run('prepare_checkout',{id, option:'50', recipient:'Sam', email:'not-an-email'}); return 'ok' }`, 'gift card bad email');
    await go('transfer-huge', `async (t,o,run)=>{ await run('points_and_giving',{topic:'transfer', points:10000000, to:'Northway'}); return 'ok' }`, 'transfer 10m points');
    await go('transfer-odd', `async (t,o,run)=>{ await run('points_and_giving',{topic:'transfer', points:1234, to:'Northway'}); return 'ok' }`, 'transfer 1234');
    await go('donate-neg', `async (t,o,run)=>{ await run('points_and_giving',{topic:'donate', points:-500, to:'a'}); return 'ok' }`, 'donate -500');
    await go('invest', `async (t,o,run)=>{ await run('points_and_giving',{topic:'invest', points:5000, to:'gold'}); return 'ok' }`, 'invest 5000 in gold');
    log('invest btns', await btns());
    await go('unfreeze', `async (t,o,run)=>{ await run('card_control',{control:'freeze', on:true}); await run('card_control',{control:'freeze', on:false}); return 'Unfrozen.' }`, 'freeze then unfreeze');
    let s = await S(); log('frozen', s.card.frozen);
    await go('gamble-lift', `async (t,o,run)=>{ await run('card_control',{control:'gambling', on:true}); return 'ok' }`, 'block gambling');
    log(await btns());
    await go('bad-booking', `async (t,o,run)=>{ await run('manage_booking',{booking_id:'nope', action:'cancel'}); return 'Cancelled.' }`, 'cancel booking nope');
    await go('flight-past', `async (t,o,run)=>{ await run('search_flights',{destination:'Lisbon', depart_date:'2026-09-01'}); return 'ok' }`, 'lisbon 1 sep');
    await go('flight-inf', `async (t,o,run)=>{ await run('search_flights',{destination:'Lisbon', depart_date:'2026-10-20', travellers:1, infants:3}); return 'ok' }`, '1 adult 3 infants');
    await go('flight-kids', `async (t,o,run)=>{ await run('search_flights',{destination:'Lisbon', depart_date:'2026-10-20', travellers:2, children:2}); return 'ok' }`, '2 kids alone');
    await go('flight-back-before', `async (t,o,run)=>{ await run('search_flights',{destination:'Lisbon', depart_date:'2026-10-20', return_date:'2026-10-18'}); return 'ok' }`, 'return before out');
    await go('flight-9', `async (t,o,run)=>{ await run('search_flights',{destination:'Lisbon', depart_date:'2026-10-20', travellers:15}); return 'ok' }`, '15 people');
    await go('choose-bogus', `async (t,o,run)=>{ await run('choose_flight',{flight_id:'FL-XXX'}); return 'ok' }`, 'bogus flight');
    await go('at-risk', `async (t,o,run)=>{ await run('talk_to_person',{reason:'customer feels hopeless', at_risk:true}); return 'I am here.' }`, 'everything feels pointless lately');
  });
})();
