require('./h.js')('UK', async (h) => {
  const { p, ask, click, full, confirm, nav, st, log, ans, shot } = h
  await nav(3)
  await ask('flights to barcelona on 14/10 returning 18 october, 2 adults and a 1 year old')
  await ans().locator('.gr-flight').first().click(); await p.waitForTimeout(400)
  await click(/Continue with/); await p.waitForTimeout(400)
  const ins = ans().locator('input')
  await ins.nth(1).fill('Priya Chawla'); await ins.nth(2).fill('Baby Chawla'); await ins.nth(3).fill('2024-10-16')
  const go=async()=>{const b=ans().locator('.gr-btn').last(); log('BTN: '+await b.innerText()+' disabled='+await b.isDisabled()); if(!(await b.isDisabled())) await b.click(); await p.waitForTimeout(500)}
  await go()
  log('AFTER DOB 2024-10-16: ' + (await h.lastText()).replace(/\n+/g,' | ').slice(-400))
  await ins.nth(3).fill('2025-03-01'); await ins.nth(1).fill('Прия Ч')
  await go()
  log('AFTER cyrillic: ' + (await h.lastText()).replace(/\n+/g,' | ').slice(-300))
  await ins.nth(1).fill('Priya Chawla')
  // add bag
  await go()
  log('CHECKOUT: ' + (await h.lastText()).replace(/\n+/g,' | ').slice(0,1200))
  await full('checkout')
  await click(/^Pay /); await p.waitForTimeout(400)
  log('SHEET: ' + await h.sheet())
  await shot('sheet')
  await confirm()
  log('RECEIPT: ' + (await h.lastText()).replace(/\n+/g,' | ').slice(0,1200))
  await full('receipt')
  const s = await st(); log('card', JSON.stringify(s.card).slice(0,300), 'pts', s.balance)
  log(JSON.stringify(s.bookings[0]).slice(0,1500))
  await ask('change my flight to the 16th')
  await full('change')
}, { name: 's2' })
