const pc=(args,txt='Confirm with the button.')=>`await run('prepare_checkout',${JSON.stringify(args)}); return ${JSON.stringify(txt)}`;
module.exports=[
{say:'jacket size M', plan:pc({id:'SH-4'})},
{say:'jacket size XXXL', plan:pc({id:'SH-4',option:'XXXL'})},
{say:'jacket size M qty 0', plan:pc({id:'SH-4',option:'M',quantity:0})},
{say:'5000 jackets', plan:pc({id:'SH-4',option:'M',quantity:5000})},
{say:'gift card £37 to bob', plan:pc({id:'GC-1',option:'£37',recipient:'Bob',email:'bob@example.com'})},
{say:'gift card £50 no email', plan:pc({id:'GC-1',option:'£50',recipient:'Bob'})},
{say:'gift card £50 bad email', plan:pc({id:'GC-1',option:'£50',recipient:'Bob',email:'bob@'})},
{say:'table for 14 at harrow', plan:pc({id:'DN-London-0',quantity:14,time:'19:30',date:'2026-10-02'})},
{say:'table for 2 at 03:00', plan:pc({id:'DN-London-0',quantity:2,option:'03:00',date:'2026-10-02'})},
{say:'table yesterday', plan:pc({id:'DN-London-0',quantity:2,option:'19:00',date:'2026-09-29'})},
{say:'cinema for 3', plan:pc({id:'ET-4',quantity:3})},
{say:'cinema next month', plan:pc({id:'ET-4',quantity:2,date:'2026-11-12'})},
{say:'hotel 45 nights', plan:pc({id:'ST-Lisbon-0',nights:45,date:'2026-10-10'})},
{say:'hotel 5 guests 1 room', plan:pc({id:'ST-Lisbon-0',nights:2,date:'2026-10-10',quantity:5,rooms:1})},
{say:'hotel check-in last week', plan:pc({id:'ST-Lisbon-0',nights:2,date:'2026-09-20'})},
{say:'lounge for 4', plan:pc({id:'AP-1',quantity:4})},
{say:'ride to manchester', plan:pc({id:'GT-1',destination:'Manchester'})},
{say:'ride to the airport at 25:00', plan:pc({id:'GT-1',destination:'airport',pickup_time:'25:00',date:'2026-10-02'})},
{say:'ride to the airport yesterday 9am', plan:pc({id:'GT-1',destination:'Heathrow',pickup_time:'09:00',date:'2026-09-29'})},
{say:'car hire 4 days', plan:pc({id:'GT-4',days:4})},
{say:'car hire 40 days', plan:pc({id:'GT-4',days:40})},
{say:'train 2 people', plan:pc({id:'GT-6',quantity:2})},
{say:'arlo grey 50 tickets', plan:pc({id:'ET-1',quantity:50})},
{say:'laptop', plan:pc({id:'SH-3',quantity:10})},
];
