const { chromium } = require('/home/claude/.npm-global/lib/node_modules/playwright');
(async () => {
  const b = await chromium.launch(); const p = await b.newPage({ viewport: { width: 420, height: 880 } });
  const m = process.argv[2] || 'UK'
  await p.goto(`file://${__dirname}/build/test.html?m=${m}`); await p.evaluate(() => localStorage.clear())
  const audit = async (label) => { const r = await p.evaluate(() => { const name = e => (e.getAttribute('aria-label') || e.innerText || e.getAttribute('title') || (e.querySelector('svg title')?.textContent) || '').trim(); const out = {}; out.btnNoName = [...document.querySelectorAll('button,[role=button],a')].filter(e => e.offsetParent && !name(e)).map(e => e.outerHTML.slice(0, 120)); out.inputNoLabel = [...document.querySelectorAll('input,textarea,select')].filter(e => e.offsetParent && !e.getAttribute('aria-label') && !e.labels?.length && !e.getAttribute('placeholder') && !e.getAttribute('aria-labelledby')).map(e => e.outerHTML.slice(0, 120)); out.imgNoAlt = [...document.querySelectorAll('img')].filter(e => !e.hasAttribute('alt')).length; out.svgRole = [...document.querySelectorAll('svg[role=img]')].filter(s => !s.getAttribute('aria-label') && !s.querySelector('title')).length; out.small = [...document.querySelectorAll('button,[role=button],a,input[type=checkbox],[role=switch],[role=radio]')].filter(e => { const r = e.getBoundingClientRect(); return e.offsetParent && r.width > 0 && (r.width < 24 || r.height < 24) }).map(e => (name(e) || e.className).slice(0, 30) + ':' + Math.round(e.getBoundingClientRect().width) + 'x' + Math.round(e.getBoundingClientRect().height)); out.h1 = document.querySelectorAll('h1').length; out.lang = document.documentElement.lang; out.dir = document.documentElement.dir; out.live = document.querySelectorAll('[aria-live]').length; out.switches = [...document.querySelectorAll('[role=switch]')].filter(e => !e.hasAttribute('aria-checked')).length; return out }); console.log(label, JSON.stringify(r).slice(0, 1200)) }
  for (const t of ['home', 'explore', 'chat', 'wallet', 'me']) { await p.goto(`file://${__dirname}/build/test.html?m=${m}&tab=${t}`); await p.waitForTimeout(500); await audit(t) }
  await p.fill('.gr-ask input', 'What do I owe?'); await p.press('.gr-ask input', 'Enter'); await p.waitForTimeout(700)
  await p.getByRole('button', { name: /^(Pay |ادفع )/ }).last().click(); await p.waitForTimeout(600)
  const d = await p.evaluate(() => { const s = document.querySelector('.app-sheet'); const dlg = document.querySelector('[role=dialog]'); return { role: dlg?.getAttribute('role'), modal: dlg?.getAttribute('aria-modal'), labelled: dlg?.getAttribute('aria-labelledby') || dlg?.getAttribute('aria-label'), focusIn: dlg?.contains(document.activeElement), active: document.activeElement?.outerHTML.slice(0, 100), inert: [...document.querySelectorAll('[inert]')].map(e => e.className).join(',') } }); console.log('sheet', JSON.stringify(d))
  for (let i = 0; i < 12; i++) await p.keyboard.press('Tab'); console.log('after tabs focus in dialog', await p.evaluate(() => document.querySelector('[role=dialog]')?.contains(document.activeElement)))
  await p.keyboard.press('Escape'); await p.waitForTimeout(300); console.log('after esc focus', await p.evaluate(() => document.activeElement?.outerHTML.slice(0, 100)))
  await b.close()
})()
