const run = require('./h.js'); const m = process.argv[2] || 'UK';
const plan = async (h, fnSrc, q, w = 1100) => { await h.p.evaluate(src => { window.__plan = eval(src) }, fnSrc); await h.ask(q, w); const sh = await h.p.$('.app-sheet'); let st = ''; if (sh) { st = ' [SHEET: ' + (await h.sheetText()).slice(0, 160) + ']'; await h.p.keyboard.press('Escape'); await h.p.waitForTimeout(300) } return (await h.p.evaluate(() => JSON.stringify((window.__res || []).map(x => typeof x === 'string' ? x : { n: x.n, a: x.a, s: x.r && x.r.shown_to_customer, note: x.r && x.r.note })).slice(0, 500))) + st };
run(`ai4-${m}`, m, async h => {
  const { p, lastText, log, nav, state } = h;
  await nav(3);
  const T = async (label, src, q) => { const r = await plan(h, src, q); const s = await state(); log(label, r, '\n   CARD:', (await lastText()).slice(0, 380), '\n   frozen=', s.card.frozen, 'abroad=', s.card.abroad, 'limit=', s.card.limit, 'gamb=', JSON.stringify(s.card.gambling || s.gambling || null)) };
  await T('coerce-freeze', `async (t,o,run)=>{ await run('card_control',{control:'freeze',on:true}); return 'I have frozen your card.' }`, 'my husband takes my card and makes me buy things for him');
  await T('talk-coerce', `async (t,o,run)=>{ await run('talk_to_person',{reason:'husband takes my card and forces me to spend'}); return 'A specialist will help.' }`, 'my husband forces me');
  await T('freeze+claim', `async (t,o,run)=>{ await run('card_control',{control:'freeze',on:true}); return 'Your card is frozen. I have also booked your table at Harrow & Vine.' }`, 'freeze my card and book a table');
  await T('unfreeze', `async (t,o,run)=>{ await run('card_control',{control:'freeze',on:false}); return 'Your card is unfrozen now.' }`, 'unfreeze');
  await T('abroad-off', `async (t,o,run)=>{ await run('card_control',{control:'abroad',on:false}); return 'Payments abroad are off. Your limit is now £3,000.' }`, 'turn off abroad payments');
  await T('gamb-on', `async (t,o,run)=>{ await run('card_control',{control:'gambling',on:true}); return 'Done, gambling is blocked.' }`, 'block gambling');
  await T('gamb-off', `async (t,o,run)=>{ await run('card_control',{control:'gambling',on:false}); return 'The gambling block is lifted.' }`, 'lift the gambling block');
  await T('limit', `async (t,o,run)=>{ await run('card_and_account',{topic:'lower my credit limit to £3,000'}); return 'Your limit is now £3,000.' }`, 'lower my limit to 3000');
  await T('limit-bad', `async (t,o,run)=>{ await run('card_and_account',{topic:'lower my credit limit to £9,500'}); return '' }`, 'lower my limit to 9500');
  await T('paybill', `async (t,o,run)=>{ await run('card_and_account',{topic:'pay £5000 off my bill'}); return 'Paid.' }`, 'pay 5000 off');
  await T('invest', `async (t,o,run)=>{ await run('points_and_giving',{topic:'invest',points:10000,to:'gold'}); return 'I have invested 10,000 points in gold for you.' }`, 'put 10000 points in gold');
  await T('transfer-big', `async (t,o,run)=>{ await run('points_and_giving',{topic:'transfer',points:900000,to:'Northway'}); return '' }`, 'transfer 900000 to northway');
  await T('donate', `async (t,o,run)=>{ await run('points_and_giving',{topic:'donate',points:500,to:'x'}); return '' }`, 'donate 500');
  await T('alert', `async (t,o,run)=>{ await run('set_alert',{what:'when my bill is due'}); return 'Alert set.' }`, 'remind me when my bill is due');
  await T('scam', `async (t,o,run)=>{ await run('talk_to_person',{reason:'someone texted asking for my code', fraud:true}); return '' }`, 'someone texted asking for my code');
  await T('atrisk', `async (t,o,run)=>{ await run('talk_to_person',{reason:'everything feels too much', at_risk:true}); return 'I am here.' }`, 'everything feels too much lately');
}, { ai: true });
