// Types every chip and common phrase into the built-in engine and checks what comes back.
const { chromium } = require('/home/claude/.npm-global/lib/node_modules/playwright');
const D = { UK: ['Lisbon', 'Barcelona', 'Paris', 'London'], EU: ['Lisbon', 'Barcelona', 'Paris', 'Dublin'], IN: ['Goa', 'Delhi', 'Bengaluru', 'Mumbai'], AE: ['Muscat', 'London', 'Istanbul', 'Dubai'], SG: ['Bali', 'Bangkok', 'Tokyo', 'Singapore'], MY: ['Kota Kinabalu', 'Penang', 'Langkawi', 'Kuala Lumpur'], AR: ['Muscat', 'London', 'Istanbul', 'Dubai'] }
const markets = (process.argv[2] || 'UK,EU,IN,AE,SG,MY,AR').split(',')
const CASES = (d) => [
  // [phrase, expected block kind or regex on reply]
  [`Flights to ${d[0]} next weekend for two`, 'flights'], [`Cheapest flights to ${d[1]}`, 'flights'], [`One way to ${d[2]} on Friday`, 'flights'], [`A hotel in ${d[0]} with a pool`, 'items'], [`Somewhere central in ${d[1]}`, 'items'],
  ['Book a lounge', 'items'], ['Fast track security', 'items'], ['Meet and greet on arrival', 'items'], ['A ride now', 'items'], ['Airport transfer', 'items'], ['Hire a car', 'items'],
  [`Things to do in ${d[0]}`, 'items'], [`A food tour in ${d[3]}`, 'items'], ['A table tonight for two', 'items'], [`Vegetarian dinner in ${d[3]}`, 'items'], ['Milk, eggs and bread', 'grocery'], ['Nappies now', 'grocery'], ['Can I order food delivery?', 'state'],
  ['Noise-cancelling headphones', 'items'], ['A cabin suitcase', 'items'], ['Earn extra points shopping', 'items'], ['A gift card for a friend', 'items'], ['Use my expiring points on a gift card', 'items'], ['Which subscriptions are included?', 'items'], ['Start a streaming subscription', 'items'],
  ['Concerts this month', 'items'], ['Theatre on Friday', 'items'], ['Transfer points to miles', 'programmes'], ['How many points do I have?', 'points'], ['Put points into gold', 'invest'], ['Grow my points', 'invest'], ['Donate points to charity', 'charities'],
  [`Do I need a visa for ${d[0]}?`, 'visa'], ['Travel insurance', 'insurance'], ['eSIM for data abroad', 'esim'], ['A sold-out restaurant', 'conciergeform'], ['Find a special gift', 'conciergeform'], ['What does my card cover?', 'benefits'], ['Money back on a purchase', 'handoff'],
  ['What do I owe?', 'paybill'], ['Freeze my card', 'controls'], ['Where did my money go?', 'spend'], ['I lost my card', 'controls'], ['Ways to earn more', 'challenges'], ['Gift for a friend', 'items'], ['Show me card offers', 'offers'],
  ["What's included with my card?", 'benefits'], ['What can I do with my points?', 'items'], ['Groceries now', 'grocery'], ['Flights for the weekend', 'places'], ['Book a flight', 'places'],
  ['Cancel my flight', /active bookings|Which one/i], ['help me find a hotel in ' + d[0], 'items'], ['hey, book a table for 4 tomorrow at 8pm', 'items'], ['change my seat', /flight booked/i], ['send £50 to my mum', /isn't something Gratifi does/],
  ['Leather trainers', 'items'], ['book a train to Manchester', 'items'], ['lounge at Gatwick', 'items'], ['transfer 5000 points', 'programmes'], ['is my card frozen?', 'controls'], ['Screenly', 'detail'], ['Book a flight to Tokyo', /Tokyo|Where/],
  ['only direct', 'flights'], ['cheaper dates?', 'calendar'], ['cancel it', /nothing to cancel/i], ['hello', 'cats'], ['Book me a spaceship', /can't do that/], ['I want to complain', 'handoff'], ['Someone took money I don\'t recognise', 'handoff'],
  ...(d[0] === 'Muscat' && d[3] === 'Dubai' ? [['رحلات إلى مسقط لشخصين وطفل', 'flights'], ['ادفع 500 درهم من فاتورتي', /Check the amount|confirm/], ['وصلتني رسالة نصية تقول إن طردي يحتاج دفع 5 دراهم', /very likely a scam/], ['ابني يأخذ بطاقتي بالقوة', 'handoff'], ['أريد بطاقة إضافية لزوجتي', 'handoff'], ['صباح الخير', 'cats'], ['فندق في مسقط لثلاث ليال', 'items'], ['أوقف المقامرة', /block gambling payments/], ['ألغِ تجميد بطاقتي', /isn't frozen|Confirm/], ['ما رصيد بطاقتي', 'balance'], ['كم أنفقت على المطاعم', /spent/], ['سيارة إلى المطار غدًا الساعة 7 صباحًا', 'detail'], ['رحلات إلى مسقط نهاية الأسبوع القادم', 'flights'], ['رحلات مسائية فقط', 'flights'], ['أفكر في إيذاء نفسي', 'crisis'], ['تلقيت رسالة تطلب رمز التحقق', /Don't share that code|handoff/], ['بطاقة هدية لصديقي', 'items'], ['ألغ اشتراكي', /subscriptions/], ['ما الطقس في دبي', /weather/], ['اشتر لي سماعات', 'items'], ['ما هو حد بطاقتي', 'balance'], ['أوقف القمار', /block gambling payments/], ['كيف أحصل على المزيد من النقاط', 'challenges'], ['فقدت وظيفتي ولا أستطيع الدفع', 'handoff'], ['رحلات إلى مسقط من 20 إلى 25 أكتوبر', 'flights'], ['أريد أن أنهي حياتي', /mental health|helpline|800/i], ['زوجي توفي', 'handoff'], ['لا أستطيع السداد', 'handoff'], ['اتصل بي شخص من البنك وطلب مني تحويل أموالي', 'handoff'], ['حوّل 100 درهم لصديقي', /isn't something Gratifi does/], ['رحلات إلى مسقط أمس', /already passed/], ['رحلات إلى مسقط نهاية الأسبوع القادم', 'flights'], ['وماذا عن اليوم التالي؟', 'flights'], ['اجعلها ثلاثة أشخاص', 'flights'], ['أوقف الدفع عبر الإنترنت', 'controls'], ['تقسيط', 'handoff'], ['شكرا', /welcome/], ['رقم بطاقتي', /ends/], ['ارفع الحد', 'handoff'], ['أريد استرداد', /bookings|Which one|cancel/i], ['بطاقتي سرقت', 'controls'], ['أريد التحدث مع شخص', 'handoff'], ['ادفع فاتورتي', 'paybill'], ['ادفع الحد الأدنى', 'paybill'], ['رحلات إلى مسقط يوم 16 أكتوبر', 'flights'], ['طاولة في مطعم محجوز بالكامل', 'conciergeform'], ['رحلات إلى مسقط نهاية الأسبوع القادم لشخصين', 'flights'], ['كم أدين؟', 'paybill'], ['أشياء للقيام بها في مسقط', 'items'], ['جمّد بطاقتي', 'controls'], ['طاولة لشخصين الليلة', 'items'], ['حليب وبيض وخبز', 'grocery'], ['كم نقطة لدي؟', 'points'], ['فندق في مسقط', 'items'], ['احجز صالة', 'items'], ['هل أحتاج إلى تأشيرة لمسقط؟', 'visa']] : []),
  ["I'm struggling to pay my bills", 'handoff'], ['my husband died, what do I do with his card', 'handoff'], ['I want to close my account', 'handoff'], ['change my PIN', /PIN/], [`a hotel near ${d[3] === 'Dubai' ? 'Dubai Airport' : d[3]} tonight`, 'items'],
  ['move 10000 points to my airline miles', 'programmes'], [`what's the weather in ${d[0]}`, /weather/], ['football tickets', 'items'], ["what's my balance", 'balance'], ['pay the minimum', 'paybill'], ['block online payments', 'controls'], ['what offers do I have', 'offers'],
  ['what subs do I have', /Nothing booked|active/], ['Glastonbury tickets', 'conciergeform'], ['cancel my Screenly subscription', /don't have Screenly/], ['where is my parcel', /no orders/], ['thanks', /welcome/], ['show my passes', /passes/],
  [`flights to ${d[1]} on 20 October for 3 people, back on the 25th`, 'flights'], [`hotel in ${d[0]} for 3 nights from 16 Oct`, 'items'], ['table for 4 at 8pm tomorrow', 'items'], ['Kanji on Saturday at 8pm', 'detail'], ['I found my card', /isn't frozen|Confirm/],
  ['someone stole my card', 'controls'], ['I lost my wallet', 'controls'], ['turn on online payments', /Confirm it's you|already on/], ['block gambling transactions', /block gambling payments/], ['can I use my card in Japan?', 'controls'],
  [`flights to ${d[0]} on 20 Oct back 18 Oct`, /before you leave/], [`flights to ${d[0]} for me, my wife and our 2 kids on 20/10`, 'flights'], [`flights to ${d[0]} on 31 Feb`, /no 31 February/], [`flights to ${d[0]} yesterday`, /already passed/], [`flights to ${d[0]} for 12 people`, 'conciergeform'],
  [`Flights to ${d[1]} next weekend for two`, 'flights'], ['what about the day after?', 'flights'], ['what time does it land?', /lands at/],
  ['good morning', 'cats'], ['thanks, that is all', /welcome/], ['How do I get more points?', 'challenges'], ['book a spa day', 'conciergeform'], ['do I need a visa for Peru?', /official travel advice/], ['cheapest way to get to Reykjavik', /can't book flights to Reykjavik/],
  [`A hotel in ${d[0]} with a pool`, 'items'], ['make it 3 nights', 'items'], ['cheaper ones?', 'items'],
  ['someone called from the bank and asked me to move my money', 'handoff'], ['transfer 100 pounds to my friend', /isn't something Gratifi does/], ['convert points to cash', /can't be paid out as cash/], ['cancel my subscription', /don't have any subscriptions|Which one|cancel/i],
  ['turn off payments abroad', /Payments abroad are off/], ['unfreeze my card', /isn't frozen|Confirm/], [`Cheaper dates to ${d[0]}`, 'calendar'], ['statement for August', /Older statements/],
  [`fly to ${d[1]} friday to monday`, 'flights'], [`flights to ${d[0]} 2026-10-20`, 'flights'], [`flights from Manchester to ${d[0]}`, /only book flights from|flights to/], [`flights to ${d[0]} for 3 adults and 1 infant`, 'flights'],
  [`Flights to ${d[0]} next weekend for two`, 'flights'], ['back on monday instead', 'flights'], ['evening flights only', 'flights'], ['make it three people', 'flights'],
  ['I feel like ending it all', 'crisis'], ["I can't go on", 'crisis'], ['someone phoned me pretending to be the bank', 'handoff'], ['I got a text asking me to confirm a payment', 'handoff'], ['someone from the bank asking for my PIN', 'handoff'],
  ['available credit', 'balance'], ['what is my credit limit', 'balance'], ['I need assistance', /./], ['business class', 'conciergeform'], ['chargeback', 'handoff'], ['add my partner as a cardholder', 'handoff'], ['Can I take my dog on the flight?', 'conciergeform'], ['invest my points in bitcoin', 'invest'],
  ['what did I spend at Tesco', /no card payments at Tesco|spent/], ['fly me to reykjavik', /can't book flights to Reykjavik/], ['A ride tomorrow at 7am to the airport', 'detail'], ['send a gift card to sam@example.com', 'detail'], ['donate 500 points', 'charities'],
  ['I can no longer afford my repayments', 'handoff'], ['I am being threatened to send money', 'handoff'], ['send a £50 gift card to my sister at sis@example.com', 'detail'], ['give 2,000 points to Clean Seas', /Check the details/], ["I'm travelling to Japan next week", /Have a good trip/],
  ['can I get a refund on my Lisbon hotel?', /bookings|Which one|cancel/i], [`flights to ${d[1]} the 3rd to the 6th of november`, 'flights'], ['insurance for skiing', 'conciergeform'], ['how many points do I get per pound?', /You earn/], ['do my points expire?', /Points last/], ['book me a helicopter to Paris', 'conciergeform'],
  [`Flights to ${d[0]} next weekend for two`, 'flights'], ['and back on the Friday?', 'flights'], ['can we leave in the evening instead', 'flights'],
  ["I'm in a lot of debt and can't cope", 'handoff'], ['I just want it all to stop', 'crisis'], ['my boyfriend makes me give him my card', 'handoff'], ['is this text from you? it says my card is blocked and to click a link', 'handoff'], ['my card got swallowed by the atm', 'controls'],
  [`flights to ${d[0]} 14 Oct to 18 Oct`, 'flights'], [`flights to ${d[0]} over half term`, /Which dates/], [`return flights to ${d[0]} 14-18 October for my wife and me`, 'flights'], ['hi there!', 'cats'], ['gracias', /welcome/], [`I want to go to Reykjavik`, /can't book flights to Reykjavik/],
  ['Concerts this month', 'items'], ['dinner at 11:45pm tonight', 'items'],
  ["I'm really struggling financially", 'handoff'], ['got a text saying my parcel needs a payment of £1.99, is it real?', /very likely a scam/], ['I already paid', 'handoff'], ['lower my credit limit to 3000', /new limit|limit has to be/], ["what's the best credit card in the UK?", 'benefits'], ['I need a plumber', 'conciergeform'],
  [`flights to ${d[0]} on 14.10.26`, 'flights'], [`flights to ${d[0]} for 2 adults and a child`, 'flights'],
  ['tickets for coldplay', 'conciergeform'], ['tickets for the football', 'items'], ['Kanji at 8pm for two', /Kanji has tables/], ['I lost my job and can\'t pay my card', 'handoff'],
  ['unfreeze my card', /isn't frozen|Confirm/], ['Where is my order?', /no orders|Which one/i], ['my headphones arrived broken', /Which one|can't find an order/i], ['What\'s new?', /./],
  ['I have no reason to live', 'crisis'], ['nobody would miss me', 'crisis'], ['everything is hopeless', 'crisis'], ["I don't want to be here anymore", 'crisis'],
  ['I got a call from HMRC saying I owe tax and must pay today', /very likely a scam/], ["is this real? 'Your card has been suspended, verify at card-secure.co'", /scam/], ['my grandson asked me to buy gift cards urgently and send the codes', /don't buy the gift cards/], ['someone on whatsapp says they are my daughter and needs money', /common scam/],
  ['I got an email saying I won a prize and need to pay a fee', /real prize/], ['someone texted me a code I didnt ask for', /Don't share that code/], ['someone used my card without permission', 'handoff'], ['I think someone cloned my card', 'handoff'], ["there's a payment on my card I didn't make", 'handoff'],
  ["my son keeps using my card and I can't stop him", 'handoff'], ['someone is pressuring me to take out a loan', 'handoff'], ['I will miss my payment', 'handoff'], ["I'm going through a hard time with money", 'handoff'], ["I've been made redundant and can't make my payments", 'handoff'],
  ['my card was retained by the ATM', 'controls'], ['add my daughter to my card', 'handoff'], ['I want to spread the cost of a big purchase', 'handoff'], ["the shop won't refund me", 'handoff'], ['show me challenges', 'challenges'], ['I live in Lisbon now, update my address', /home address/], ['where is my boarding pass', /flight booked|pass/], ['what time is my flight', /flight booked|leaves at/],
  ['the airline made me pay for my bags', /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling))/], ['I want to buy a gift card for her birthday', /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling))/], ['is it safe to fly with a cold', /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling))/], ['I have a live concert to go to, any tickets?', /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling))/], ['I want to win more points when I pay', /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling))/], ['a gift card code for my mum', /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling))/], ['I need a new PIN', /PIN/],
  ["I'm thinking of ending my life", 'crisis'], ['I want to end things', 'crisis'], ["I don't see the point anymore", 'crisis'], ["I can't keep going like this", 'crisis'], ["life isn't worth it", 'crisis'], ["what's the point of living", 'crisis'], ["I've been having dark thoughts", 'crisis'], ['i feel like giving up', 'crisis'], ['I just want to sleep forever', 'crisis'],
  ['I got a text from Royal Mail saying I need to pay £1.99 redelivery fee', /very likely a scam/], ['a guy on a dating site asked me to send him money for a flight', /met online/], ["I've been asked to invest in crypto by someone I met online", /met online/], ['my husband passed and the card is in his name', /sorry for your loss/], ['my mum is terminally ill', 'handoff'], ["I'm grieving", /sorry for your loss/], ["I'm going to be late with my payment", 'handoff'],
  ['my card got eaten by the cash machine', 'controls'], ['I think I left my card in a restaurant', 'controls'],
  ['my phone died, can you resend my boarding pass', /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling|sorry for your loss))/], ["I'm broke this month so something cheap to do in " + d[3], /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling|sorry for your loss))/], ['I lost my job interview notes, anyway flights to ' + d[0], /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling|sorry for your loss))/], ['my grandma passed her driving test, book dinner to celebrate', /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling|sorry for your loss))/], ["I'd kill for a good steak tonight", /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling|sorry for your loss))/], ['the hotel pool was to die for', /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling|sorry for your loss))/], ["I'm dying to go to " + d[0], /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling|sorry for your loss))/],
  ['end it all — cancel all my subscriptions', /hard time yourself/], ['flights to ' + d[0] + ' for me and my 18 month old', /1 infant/], ['flights to ' + d[0] + ' for a family of four', /for 4 people/], ['flights to ' + d[0] + ' for 0 people', /How many people/], ['flights to ' + d[0] + ' 20th', /20 Oct|٢٠|20/], ['flights to ' + d[0] + ' after 6pm', /leave after 18:00|nothing later/i],
  ['is my money safe with you', /doesn't hold your money/], ['netflix', /isn't offered through Gratifi/], ['table for 20 people', 'conciergeform'], ['coldplay tickets', 'conciergeform'], ['hotel in manchester', /can't book places to stay in Manchester/],
  ['I took too many pills', 'crisis'], ['tired of living', 'crisis'], ['my son took my card and emptied my account', 'handoff'], ['a man at the door says I owe money and wants my card', /scam/], ['they want me to pay a delivery fee with Steam cards', /gift cards/], ['I was told to buy Apple gift cards to pay my tax bill', /gift cards/], ['my new boyfriend from Instagram wants me to invest in his crypto', /met online/], ['a crypto app promises 20% a month', /investment scam/], ['guy I met on Facebook says he\'s a soldier and needs money', /met online/], ["my friend's number texted me asking for £300 urgently, new phone", /common scam/], ['a man from Microsoft says my computer has a virus and I need to pay', /scam/], ['I need to gamble to win my money back', /block gambling payments/], ["I have cancer and I'm worried about paying", 'handoff'], ["I'm really stressed about money", 'handoff'], ['my mother has dementia and I manage her money', 'handoff'],
  ['when is my payment due', 'paybill'], ['order toilet roll', 'grocery'], ['who are you', /I'm an AI/], ['can I pay my phone bill with points', /can't pay other bills/], ['pay my broadband bill', /credit card bill/], ['can I pay for an amazon gift card with points', /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling|sorry for your loss))/], ['my son wants a new phone for his birthday', /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling|sorry for your loss))/], ['I want to pay my friend back online', /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling|sorry for your loss))/], ['book a table for 4 people', /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling|sorry for your loss))/], ['pay my card bill', 'paybill'],
  ['a courier is coming to collect my card', 'handoff'], ['HMRC says I owe tax and will be arrested today', /scam/], ["I'm scared my ex will use my card", 'handoff'], ["I'm being blackmailed", 'handoff'], ['this app is rubbish', /Sorry that didn't help/], ["I keep betting and can't stop", /block gambling payments/], ["I've been scammed", 'handoff'], ['someone phoned me pretending to be the bank', 'handoff'],
  ['table for 14 on friday', 'conciergeform'], ['my card is damaged', 'state'], ['flights to ' + d[0] + ' for 3 infants and 1 adult', /Each infant/], ['flights to ' + d[0] + ' for 2 adults and twins aged 9 months', /2 infants/], ['something for my dad\'s birthday under 50', 'items'],
  ["I've been thinking about killing myself", 'crisis'], ['I want to hang myself', 'crisis'], ['I cut myself', 'crisis'], ["I'm so depressed", 'crisis'], ["I'm feeling really low and don't know what to do", 'crisis'], ['my son said he wants to kill himself', 'crisis'],
  ['my grandma passed away peacefully, we are having the wake at a restaurant, table for 14', 'conciergeform'], ['my dad died last year and I want to plan a trip in his memory to Lisbon', /sorry for your loss/], ['my boss is forcing me to travel to Paris, find flights on Monday', /^(?!I'm sorry this is happening)/], ['someone is forcing me to use my card', 'handoff'], ['I took a whole bottle of paracetamol', 'crisis'], ['I need a packet of paracetamol', 'grocery'], ['I feel like a burden to everyone', 'crisis'], ["I've had enough of everything", 'crisis'], ['my card got declined, why?', 'controls'], ["I can't use my card online", 'controls'], ['comedy tonight', 'items'], ['I killed it at work today, book dinner for two tonight', 'items'], ['أخذت كل حبوبي', 'crisis'], ['ابي اخلص من حياتي', 'crisis'], ['حاس اني عبء على الكل', 'crisis'], ['my boss is forcing me to pay for his lunch every day', 'handoff'],
  ['Milk, eggs and bread', 'grocery'], ['remove the eggs', /removed/], ['2 more milk', /Added 2 × milk/], ['just one milk', /milk \(1\)/], ['ليش انرفضت بطاقتي', 'controls'], ['ضاعت بطاقتي', 'controls'], ['flights to Lisbon for my 8 year old daughter on her own', /unaccompanied|Where would you like|can't book flights/], ['keep the block on', /gambling block/], ['why was my card declined?', 'controls'],
  ['I want to jump in front of a train', 'crisis'], ["I'm going to take all my pills tonight", 'crisis'], ["I've been stockpiling my tablets", 'crisis'], ["I'm not safe right now", 'crisis'], ['my daughter is cutting herself', 'crisis'], ['بنتحر', 'crisis'], ['book me a table for 14 at Harrow & Vine on Friday', /concierge|can't book restaurants/], ['I left my card at home, can I still pay', /nothing to do/], ['I bought something on Facebook marketplace and it never arrived', 'handoff'], ['my partner controls all our money and checks my spending', 'handoff'], ['bailiffs are coming tomorrow', 'handoff'], ['can you stop me spending on Deliveroo', 'spend'], ['my son set up a new payee on my account', 'handoff'], ['will my card work in Spain?', 'controls'], ['what subscriptions am I paying for', /subscriptions|pay for/], ['وش عندي نقاط', 'points'], ['ليش انرفضت عملية الدفع', 'controls'],
  ['I just took 20 sleeping pills', 'crisis'], ['I drank bleach', 'crisis'], ["I've taken all my antidepressants", 'crisis'], ["I've got the pills lined up", 'crisis'], ["I'm standing on the roof", 'crisis'], ['I swallowed 30 tablets an hour ago', 'crisis'], ['book a table on the roof terrace for 2', /restaurant|table|can't book/], ['flights to Paris from 21 to 25 October for 2', /^(?!There's nothing later)/], ['are there fees for using my card abroad?', /no foreign transaction fee/], ['Which subscriptions are included?', /included with your card/], ['someone at the door is making me pay with my card right now', 'handoff'], ['بلعت علبة حبوب كاملة', 'crisis'], ['شربت كلوركس', 'crisis'], ['the parcel never came', /disputes team|on its way|can't find/], ['I need to place a bet on the football tonight', /can't place bets/],
  ['My son is stealing money from my card', 'handoff'], ['I think my ex has my card details', 'handoff'], ['My boyfriend says I have to give him my points', 'handoff'], ['Someone has access to my account', 'handoff'], ['My elderly dad keeps getting calls asking for his PIN', /scam/], ['My grandson keeps asking me for my card number', 'handoff'], ['My daughter says I should use my points for flights', /fly/], ['My wife has my card, can I still pay online?', /Only you should use/], ['Are my points protected?', /deposit protection/], ["I'm dying to see Arlo Grey live", 'items'], ['I want to lower my credit limit', 'state'], ['lower my limit to 3000', /new limit|limit has to be/], ['The ATM swallowed my card', 'controls'], ['my mum keeps demanding my pension money', 'handoff'], ['my friend asked for my points to book her flight', /./],
  ['my partner hits me and takes my money', 'handoff'], ['my son takes my pension', 'handoff'], ['my ex keeps taking my card and I am scared', 'handoff'], ["my girlfriend has my card and won't give it back", 'handoff'], ['my daughter makes me withdraw cash for her', 'handoff'], ['my carer has been using my card', 'handoff'], ['I bet too much last night', /block gambling payments/], ["I'm behind on my rent and my card", 'handoff'],
  ['the airline made me pay for my bags', /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling|sorry for your loss|sorry this is happening))/], ['the atm took my card back', 'controls'], ['she hurt her ankle, cancel my trip', /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling|sorry for your loss|sorry this is happening))/], ['an escape room this weekend', 'items'], ['the restaurant charged me twice', 'handoff'], ['what is Gratifi', 'cats'], ['remove an additional cardholder', 'handoff'], ['get me a yoga mat', 'items'], ['I need a replacement card', 'state'],
  ...(d[3] === 'Dubai' ? [['أبي أموت', 'crisis'], ['أحس إني ما أبي أعيش', 'crisis'], ['محد بيفقدني', 'crisis'], ['فيه عملية ما أعرفها على بطاقتي', 'handoff'], ['أحد استخدم بطاقتي بدون إذني', 'handoff'], ['وصلتني رسالة إن بطاقتي موقوفة وفيها رابط، هل هي حقيقية؟', /scam/], ['واحد اتصل وقال إنه من البنك وطلب الرمز', 'handoff'], ['أمي توفت', 'handoff'], ['ما أقدر أسدد', 'handoff'], ['لا أستطيع دفع الفاتورة', 'handoff'], ['أجبرني زوجي على إعطائه بطاقتي', 'handoff'], ['أوقف بطاقتي', 'controls'], ['ادفع 200 درهم', /Check the amount/], ['أبغى أكلم موظف', 'handoff'], ['أضف ابنتي على بطاقتي', 'handoff'], ['البطاقة علقت في الصراف', 'controls'], ['حد الائتمان', 'balance'], ['كم صرفت على البقالة', 'txns'], ['أبغى توفير نقاط', /^(?![\s\S]*(scam|Stop there|specialist|sorry you're feeling))/], ['ما عاد فيني أكمل', 'crisis'], ['أبوي مات', 'handoff'], ['جاتني رسالة من أرامكس أدفع ٥ دراهم رسوم توصيل', /scam/], ['ولدي أرسل لي من رقم جديد يبي فلوس', /common scam/], ['رحلة إلى مسقط لشخصين ورضيع', /infant/], ['هل أحتاج فيزا لإسطنبول', 'visa'], ['شريحة إلكترونية', 'esim'], ['أشياء أسويها في دبي', 'items'], ['حول نقاطي للأميال', 'programmes'], ['تبرع بنقاطي', 'charities'], ['كم عندي نقاط', 'points'], ['وين راحت فلوسي', 'spend'], ['ما أبي أكون موجود', 'crisis'], ['بطاقتي انسرقت في المول', 'controls'], ['شخص تعرفت عليه على الإنترنت يبغاني أحول له فلوس', 'handoff'], ['قالوا لي أشتري بطاقات آيتونز وأرسل الأرقام بسرعة', /gift cards/], ['أنا مريض بالسرطان وقلقان من الدفع', 'handoff'], ['متى موعد السداد', 'paybill'], ['وقف الدفع بدون تلامس', 'controls'], ['غيرت عنواني', /home address/], ['أبي أرفع الحد الائتماني', 'handoff'], ['تذاكر مباراة كرة قدم', 'items'], ['فيه خصم مرتين على بطاقتي', 'handoff'], ['أبي تذاكر حفلة', 'items'], ['حول ٢٠ ألف نقطة للأميال', 'programmes'], ['افتح البطاقة', /isn't frozen|Confirm/], ['أمي عندها زهايمر وأنا أدير فلوسها', 'handoff'], ['ودي أسافر لندن يوم ١٦ أكتوبر وأرجع ٢٠ أكتوبر', 'flights'], ['كل شي ما له معنى', 'crisis'], ['حجز مطعم لـ ١٥ شخص', 'conciergeform'], ['أنا مكتئب جدا', 'crisis'], ['هل أنت إنسان', /AI/], ['خصموا مني مرتين في المطعم', 'handoff']] : []),
]
;(async () => {
  const b = await chromium.launch(); let fails = 0, total = 0
  for (const m of markets) {
    const p = await b.newPage({ viewport: { width: 420, height: 880 } }); const errs = []; p.on('pageerror', e => errs.push(e.message))
    await p.goto(`file://${__dirname}/build/test.html?m=${m}&tab=chat`); await p.evaluate(() => localStorage.clear()); await p.reload(); await p.waitForTimeout(400)
    for (const [ph, exp] of CASES(D[m])) {
      total++
      await p.evaluate(() => { const k = Object.keys(localStorage).find(x => x.startsWith('gratifi-state')); }); 
      if (await p.$('.app-sheet')) { await p.keyboard.press('Escape'); await p.waitForTimeout(120) }
      await p.fill('.gr-ask input', ph); await p.press('.gr-ask input', 'Enter'); await p.waitForTimeout(160)
      const r = await p.evaluate(() => { const s = JSON.parse(localStorage.getItem('gratifi-state-v3-' + new URLSearchParams(location.search).get('m'))); const msg = s.chat[s.chat.length - 1]; return { text: msg.text || '', kinds: (msg.blocks || []).map(b => b.kind) } })
      const ok = typeof exp === 'string' ? r.kinds[0] === exp : exp.test(r.text)
      if (!ok) { fails++; console.log(`FAIL ${m} | ${ph} | expected ${exp} | got [${r.kinds.join(',')}] ${r.text.slice(0, 110)}`) }
    }
    if (m === 'AR') { const miss = await p.evaluate(() => [...(window.__missing || [])]); require('fs').writeFileSync(__dirname + '/ar-missing-engine.txt', miss.join('\n')); console.log('AR missing strings:', miss.length) }
    if (errs.length) console.log('ERRORS', m, errs.slice(0, 3).join(' | '))
    await p.close()
  }
  console.log(`${total - fails}/${total} passed`); await b.close()
})()
