(async () => {
  const H = await require('./h.js')('AR', 'light', 'ar')
  const { p, full, nav, ask, click, last, st, lastMsg, sheetText, confirm, waitSheetGone, done, shot } = H
  const L = require('./lib.js')(H)
  const latin = async (tag) => { const t = await p.locator('.app').innerText(); const runs = (t.match(/[A-Za-z][A-Za-z '&,.-]{2,}/g) || []).map(x => x.trim()).filter(x => x.length > 2); const u = [...new Set(runs)]; console.log(`LATIN[${tag}]`, u.slice(0, 80).join(' | ')) }
  console.log('dir', await p.evaluate(() => document.documentElement.dir + ' ' + document.documentElement.lang))
  await full('home'); await latin('home'); await nav(2); await full('explore'); await latin('explore')
  await p.locator('.gr-cattile').nth(0).click(); await p.waitForTimeout(300); await full('explore-flights'); await latin('ex-fl')
  await nav(3); await full('chat'); await latin('chat')
  await ask('رحلات إلى مسقط نهاية الأسبوع القادم لشخصين'); await L.log('fl'); await full('fl')
  await p.locator('.gr-flight').first().click(); await p.waitForTimeout(500); await full('fares'); await latin('fares')
  await click(/تابع/).catch(async () => { await last().locator('.gr-btn').last().click() }); await p.waitForTimeout(400)
  await last().locator('.app-in:not([disabled])').first().fill('سارة أحمد'); await full('seats'); await latin('seats')
  await last().locator('.gr-btn').last().click(); await p.waitForTimeout(500); await full('checkout'); await latin('checkout')
  const pay = p.getByRole('button', { name: /^ادفع/ }).last(); console.log('pay', await pay.innerText().catch(() => 'none')); await pay.click(); await p.waitForTimeout(400); console.log('SHEET', await sheetText()); await shot('sheet')
  await confirm(); await p.waitForTimeout(800); await shot('sheet-done'); await waitSheetGone(); await L.log('paid'); await full('receipt'); await latin('receipt')
  await ask('كم أدين؟'); await L.log('owe'); await full('owe'); await latin('owe')
  await ask('طاولة لشخصين الليلة'); await L.log('dine'); await L.pickFirst(); await full('dine'); await latin('dine')
  await ask('حليب وبيض وخبز'); await L.log('groc'); await full('groc'); await latin('groc')
  await ask('جمّد بطاقتي'); await L.log('freeze'); await full('freeze'); await latin('freeze')
  await ask('أريد إلغاء رحلتي'); await L.log('cancel'); await full('cancel'); await latin('cancel')
  await ask('I want a hotel in Istanbul for 2 nights'); await L.log('en-in-ar'); await full('en')
  await nav(4); await full('wallet'); await latin('wallet'); await click('عرض بطاقة الصعود').catch(() => console.log('no pass btn')); await full('pass'); await latin('pass')
  await nav(5); await full('me'); await latin('me')
  const miss = await p.evaluate(() => [...(window.__missing || [])]); console.log('MISSING', miss.length, miss.slice(0, 60).join(' || '))
  console.log(await done())
})()
