(async () => {
  const H = await require('./h.js')('UK', 'light', 'uk-cat')
  const { p, full, nav, ask, click, last, st, lastMsg, done } = H
  const L = require('./lib.js')(H)
  await nav(3); await ask("hello")
  const step = async (label, fn) => { const a = await L.snap(); try { await fn() } catch (e) { console.log('!! ' + label + ' ' + e.message.split('\n')[0]); await H.shot('fail-' + label) } const b = await L.snap(); console.log(`== ${label}: ${L.diff(a, b)}`) }
  await step('stay', async () => {
    await ask('hotel in Lisbon for 3 nights from 16 Oct for two'); await L.log('stay'); await full('stay-list')
    await L.pickFirst(); await full('stay-detail'); console.log('  cta', await L.cta()); await full('stay-checkout')
    const s = await st(); const d = Object.values(s.drafts)[0]; console.log('  draft', d.total, d.when, JSON.stringify(d.detail))
    console.log('  ', await L.payIt()); await L.log('stay-done')
  })
  await step('dining', async () => {
    await ask('table for 4 at 8pm tomorrow'); await L.log('dine'); await full('dine-list')
    await L.pickFirst(); await full('dine-detail'); console.log('  cta', await L.cta()); await full('dine-confirm')
    const s = await st(); const d = Object.values(s.drafts)[0]; console.log('  draft', d.when, JSON.stringify(d.detail))
    console.log('  ', await L.payIt()); await L.log('dine-done'); await full('dine-done')
  })
  await step('ride', async () => {
    await ask('A ride now'); await L.pickFirst(); await p.locator('.gr-detail .gr-slot').last().click(); await full('ride-detail'); console.log('  cta', await L.cta())
    const s = await st(); const d = Object.values(s.drafts)[0]; console.log('  draft', d.total, JSON.stringify(d.detail)); console.log('  ', await L.payIt()); await L.log('ride-done')
  })
  await step('train', async () => { await ask('book a train to Edinburgh'); await L.log('train'); await L.pickFirst(); await full('train-detail'); console.log('  cta', await L.cta()); console.log('  ', await L.payIt()); await L.log('train-done') })
  await step('train-mcr', async () => { await ask('book a train to Manchester'); await L.log('train-mcr') })
  await step('carhire', async () => { await ask('Hire a car'); await L.log('car'); await L.pickFirst(); await full('car-detail'); console.log('  cta', await L.cta()); const s = await st(); const d = Object.values(s.drafts)[0]; console.log('  draft', d.total, d.when, JSON.stringify(d.detail)); console.log('  ', await L.payIt()) })
  await step('exp', async () => { await ask('Things to do in Lisbon'); await L.log('exp'); await L.pickFirst(); await full('exp-detail'); console.log('  cta', await L.cta()); const s = await st(); const d = Object.values(s.drafts)[0]; console.log('  draft', d.total, d.when); console.log('  ', await L.payIt()) })
  await step('lounge', async () => { await ask('Book a lounge'); await L.log('lounge'); await full('lounge-list'); await L.pickFirst(); await full('lounge-detail'); console.log('  cta', await L.cta()); await full('lounge-confirm'); console.log('  ', await L.payIt()); await L.log('lounge-done') })
  await step('lounge-cancel', async () => { await ask('cancel my lounge'); await L.log('lc'); await full('lounge-cancel'); await click('Yes, cancel'); await L.log('lc2') })
  await step('fasttrack', async () => { await ask('Fast track security'); await L.log('ft'); await L.pickFirst(); console.log('  cta', await L.cta()); console.log('  ', await L.payIt()); await L.log('ft-done') })
  await step('grocery', async () => { await ask('Milk, eggs and bread'); await L.log('groc'); await full('groc'); await click('Checkout'); await full('groc-checkout'); console.log('  ', await L.payIt()); await L.log('groc-done') })
  await step('shop', async () => { await ask('Noise-cancelling headphones'); await L.log('shop'); await L.pickFirst(); await full('shop-detail'); console.log('  cta', await L.cta()); console.log('  ', await L.payIt('Card')); await L.log('shop-done'); await full('shop-done') })
  await step('affiliate', async () => { await ask('Earn extra points shopping'); await L.log('aff'); await full('aff-list'); await L.pickFirst(); await full('aff-detail'); console.log('  cta', await L.cta()); await L.log('aff-done') })
  await step('gift', async () => { await ask('A gift card for a friend'); await L.log('gift'); await L.pickFirst(); await p.locator('.gr-detail .app-in').nth(0).fill('Sam'); await p.locator('.gr-detail .app-in').nth(1).fill('sam@example'); await full('gift-bademail'); await p.locator('.gr-detail .app-in').nth(1).fill('sam@example.com'); console.log('  cta', await L.cta()); await full('gift-checkout'); console.log('  ', await L.payIt()); await L.log('gift-done') })
  await step('sub-included', async () => { await ask('Which subscriptions are included?'); await L.log('subs'); await full('subs-list'); await L.pickFirst(1); await full('sub-detail'); console.log('  cta', await L.cta()); console.log('  ', await L.payIt()); await L.log('sub-inc-done') })
  await step('sub-paid', async () => { await ask('Start a streaming subscription'); await L.log('subs2'); await L.pickFirst(0); await full('sub2-detail'); console.log('  cta', await L.cta()); await full('sub2-checkout'); console.log('  ', await L.payIt('Card')); await L.log('sub2-done') })
  await step('sub-pause', async () => { await ask('pause my Screenly subscription'); await L.log('pause') })
  await step('sub-cancel', async () => { await ask('cancel my Screenly subscription'); await L.log('scancel'); await click(/^Yes/); await L.log('scancel2') })
  await step('tickets', async () => { await ask('Concerts this month'); await L.log('tix'); await L.pickFirst(); await full('tix-detail'); console.log('  cta', await L.cta()); console.log('  ', await L.payIt()); await L.log('tix-done') })
  await step('tickets-cancel', async () => { await ask('cancel my concert tickets'); await L.log('tixc'); await full('tix-cancel') })
  await nav(4); await full('wallet')
  console.log(await done())
})()
