(async () => {
  const H = await require('./h.js')('UK', 'light', 'uk-b')
  const { p, full, nav, ask, click, last, st, lastMsg, sheetText, confirm, waitSheetGone, done } = H
  const L = require('./lib.js')(H)
  await nav(3); await ask('hello')
  const step = async (label, fn) => { const a = await L.snap(); try { await fn() } catch (e) { console.log('!! ' + label + ' ' + e.message.split('\n')[0]); await H.shot('fail-' + label) } const b = await L.snap(); console.log(`== ${label}: ${L.diff(a, b)}`) }
  await step('gift', async () => { await ask('A gift card for a friend'); await L.pickFirst(1); const d = last().locator('.gr-detail'); await d.locator('.app-in').nth(0).fill('Sam'); await d.locator('.app-in').nth(1).fill('sam@example.com'); await click('£100'); await full('gift-detail'); console.log('  cta', await L.cta()); await full('gift-checkout'); console.log('  ', await L.payIt()); await L.log('gift-done'); await full('gift-done') })
  await step('gift-cancel', async () => { await ask('cancel my gift card'); await L.log('gc') })
  await step('offer', async () => { await ask('Show me card offers'); await L.log('offers'); await full('offers'); const adds = last().getByRole('button', { name: 'Add' }); console.log('  add btns', await adds.count()); await adds.nth(3).click(); await p.waitForTimeout(300); await L.log('offer-added') })
  await step('shop-offer', async () => { await ask('Noise-cancelling headphones'); await L.pickFirst(); await L.cta(); console.log('  ', await L.payIt('Card')); const s = await st(); console.log('  earned', s.bookings[0].earned, s.ledger.slice(0, 3).map(l => l.label + ' ' + l.pts).join(' | ')) })
  await step('shop-cancel', async () => { await ask('cancel my headphones'); await L.log('hc'); await full('hp-cancel'); await click('Yes, cancel'); await L.log('hc2'); const s = await st(); console.log('  ', s.ledger.slice(0, 3).map(l => l.label + ' ' + l.pts).join(' | ')) })
  await step('shop-cancel2', async () => { await ask('cancel my headphones'); await L.log('hc3') })
  await step('jacket-claim', async () => { await ask('Rain shell jacket'); await L.pickFirst(); await L.cta(); console.log('  ', await L.payIt()); await ask('my jacket arrived damaged'); await L.log('claim'); await full('claim-form'); await click("It arrived damaged"); await click('Send claim'); await L.log('claim-sent'); await full('claim-sent') })
  await step('return', async () => { await ask('I want to return my jacket'); await L.log('ret') })
  await step('owe', async () => { await ask('What do I owe?'); await L.log('owe'); await full('owe'); await click('Minimum'); await full('owe-min'); await click(/^Pay £/); console.log('  SHEET', await sheetText()); await confirm(); await waitSheetGone(); await L.log('paid'); const s = await st(); console.log('  card', s.card.balance, s.card.due, s.card.min) })
  await step('freeze', async () => { await ask('Freeze my card'); await L.log('freeze'); await full('freeze') })
  await step('freeze-toggle', async () => { const sw = last().locator('[role=switch]'); console.log('  switches', await sw.count()); await sw.first().click(); await p.waitForTimeout(300); await L.log('frozen'); })
  await step('pay-frozen', async () => { await ask('Leather trainers'); await L.pickFirst(); await L.cta(); console.log('  ', await L.payIt('Card')); await L.log('frozen-pay'); await full('frozen-pay') })
  await step('unfreeze', async () => { await ask('unfreeze my card'); await L.log('unf'); console.log('  SHEET', await sheetText()); await confirm(); await waitSheetGone(); await L.log('unf2') })
  await step('online-off', async () => { await ask('block online payments'); await L.log('online'); await ask('turn on online payments'); await L.log('online-on'); console.log('  sheet?', await sheetText()) })
  await step('statement', async () => { await ask('Show my statement'); await L.log('stmt'); await full('stmt') })
  await step('lost', async () => { await ask('I lost my card'); await L.log('lost'); await click('Send a replacement'); await L.log('repl'); await click('Send a replacement').catch(() => console.log('  replacement btn disabled')); })
  await step('limit', async () => { await ask('increase my credit limit'); await L.log('limit'); await ask('spread a big purchase into instalments'); await L.log('instal') })
  await step('hardship', async () => { await ask("I'm struggling to pay my bills"); await L.log('hard'); await full('hard'); await ask('my husband died, what do I do with his card'); await L.log('bereave') })
  await step('pin', async () => { await ask('change my PIN'); await L.log('pin'); await ask('what is my card number'); await L.log('cardnum'); await ask('send £50 to my mum'); await L.log('send') })
  await step('transfer', async () => { await ask('Transfer 5000 points to Northway'); await L.log('xfer'); await full('xfer'); const b = last().locator('.gr-btn').first(); console.log('  btn', await b.innerText()); await b.click(); await p.waitForTimeout(400); console.log('  SHEET', await sheetText()); await confirm(); await waitSheetGone(); await L.log('xfer-done') })
  await step('xfer-undo', async () => { await ask('cancel my points transfer'); await L.log('xundo') })
  await step('invest', async () => { await ask('Put points into gold'); await L.log('inv'); await full('inv'); await last().locator('.gr-ack input').check(); await click('Continue with the partner'); console.log('  SHEET', await sheetText()); await confirm(); await waitSheetGone(); await L.log('inv-done') })
  await step('sell', async () => { await ask('sell my gold'); await L.log('sell') })
  await step('donate', async () => { await ask('Donate points to charity'); await L.log('don'); await last().locator('.gr-btn').first().click(); await p.waitForTimeout(400); console.log('  SHEET', await sheetText()); await confirm(); await waitSheetGone(); await L.log('don-done') })
  await step('visa', async () => { await ask('Do I need a visa for New York?'); await L.log('visa'); await full('visa') })
  await step('ins', async () => { await ask('Travel insurance'); await L.log('ins'); await full('ins'); await last().locator('.gr-btn').first().click(); await p.waitForTimeout(400); console.log('  ', await L.payIt()) })
  await step('esim', async () => { await ask('eSIM for data abroad'); await L.pickFirst(); console.log('  ', await L.payIt()); await L.log('esim-done') })
  await step('concierge', async () => { await ask('Get me a table at a sold-out restaurant'); await L.log('conc'); await p.fill('.app-ta', 'Saturday, 2 people, around 8pm'); await click('Send to the concierge'); await L.log('conc-sent'); await full('conc') })
  await step('benefits', async () => { await ask('What does my card cover?'); await L.log('ben'); await full('ben') })
  await step('complain', async () => { await ask('I want to complain'); await L.log('comp'); await click('Chat').catch(() => {}); await p.waitForTimeout(2000); await L.log('comp2'); await full('comp') })
  await nav(5); await full('me-after')
  console.log(await done())
})()
