(async () => {
  const H = await require('./h.js')('MY', 'light', 'my')
  const { p, full, nav, ask, click, last, st, lastMsg, sheetText, confirm, waitSheetGone, done, shot } = H
  const L = require('./lib.js')(H)
  await full('home'); await nav(3); await ask('hello')
  await ask('Flights to Penang next weekend for two'); await L.log('fl')
  await p.locator('.gr-flight').first().click(); await p.waitForTimeout(500)
  await click(/Continue with/); await last().locator('.app-in:not([disabled])').first().fill('Aisyah Tan'); await click('Continue', { exact: true }); await full('checkout')
  const pay = p.getByRole('button', { name: /^Pay / }).last(); console.log(await pay.innerText()); await pay.click(); await p.waitForTimeout(400)
  console.log('SHEET', await sheetText()); await shot('sheet')
  await p.locator('.app-sheet .gr-btn').last().click(); await p.waitForTimeout(700); await shot('approving'); await waitSheetGone(); await L.log('paid'); await full('receipt')
  let s = await st(); let b = s.bookings[0]; console.log('booking', b.total, b.pts, b.card, b.earned, 'bal', s.balance)
  await ask('A hotel in Langkawi with a pool'); await L.pickFirst(); await full('stay'); await L.cta(); console.log(await L.payIt('Card')); await L.log('stay')
  await ask('Milk, eggs and bread'); await click('Checkout'); console.log(await L.payIt()); await L.log('groc')
  await ask('A gift card for a friend'); await L.pickFirst(); const d = last().locator('.gr-detail'); await d.locator('.app-in').nth(0).fill('Mei'); await d.locator('.app-in').nth(1).fill('mei@example.com'); await full('gift'); await L.cta(); console.log(await L.payIt()); await L.log('gift')
  await ask('Concerts this month'); await L.pickFirst(); await full('tix'); await L.cta(); console.log(await L.payIt())
  await ask('A ride now'); await full('rides')
  await ask('Do I need a visa for Singapore?'); await full('visa')
  await ask('Travel insurance'); await full('ins')
  await ask('I want to cancel my hotel'); await L.log('hc'); await click('Yes, cancel'); await L.log('hc2')
  await nav(5); await full('me'); await nav(4); await full('wallet')
  s = await st(); console.log('ledger', s.ledger.slice(0, 8).map(l => l.label + ' ' + l.pts).join(' | '))
  console.log(await done())
})()
