const { chromium } = require('/home/claude/.npm-global/lib/node_modules/playwright');
const APP = '/tmp/claude-0/-home-claude/d2529b2f-e36e-5c22-8d08-213fa2f214ae/scratchpad/gratifi/review/';
const SH = __dirname + '/shots/';
module.exports = async function open(market = 'UK', theme = 'light', file = 'test.html', tag = 'x') {
  const b = await chromium.launch();
  const ctx = await b.newContext({ viewport: { width: 420, height: 880 }, deviceScaleFactor: 1 });
  const p = await ctx.newPage();
  const errs = []; p.on('pageerror', e => errs.push('PAGE ' + e.message)); p.on('console', m => { if (m.type() === 'error') errs.push('CON ' + m.text()) });
  p.on('dialog', d => d.accept());
  const url = (x = '') => `file://${APP}${file}?m=${market}&theme=${theme}${x}`;
  await p.goto(url()); await p.evaluate(() => localStorage.clear()); await p.goto(url()); await p.waitForTimeout(500);
  let n = 0;
  const H = { p, errs, b, market };
  H.shot = async (name, fullPage) => { await p.waitForTimeout(350); const f = `${SH}${market}-${tag}-${String(++n).padStart(2, '0')}-${name}.png`; if (fullPage) { const el = await p.$('.app-main .app-scroll'); if (el) { await el.evaluate(e => e.scrollTop = e.scrollHeight) ; await p.waitForTimeout(500) } } await p.screenshot({ path: f }); return f };
  H.tall = async (name) => { await p.waitForTimeout(350); const el = await p.$('.app-main .app-scroll'); const h = el ? await el.evaluate(e => e.scrollHeight) : 880; await p.setViewportSize({ width: 420, height: Math.min(5000, h + 200) }); await p.waitForTimeout(400); const f = `${SH}${market}-${tag}-${String(++n).padStart(2, '0')}-${name}.png`; await p.screenshot({ path: f }); await p.setViewportSize({ width: 420, height: 880 }); return f };
  H.bottom = async (name, hgt = 1100) => { await p.setViewportSize({ width: 420, height: hgt }); await p.waitForTimeout(200); await p.evaluate(() => { const e = document.querySelector('.app-main .app-scroll'); e.scrollTop = e.scrollHeight }); await p.waitForTimeout(700); const f = `${SH}${market}-${tag}-${String(++n).padStart(2, '0')}-${name}.png`; await p.screenshot({ path: f }); await p.setViewportSize({ width: 420, height: 880 }); return f };
  H.nav = async (i) => { await p.click(`.gr-nav button:nth-child(${i})`); await p.waitForTimeout(300) };
  H.ask = async (t, wait = 700) => { await p.fill('.gr-ask input', t); await p.press('.gr-ask input', 'Enter'); await p.waitForTimeout(wait) };
  H.last = async () => p.evaluate(() => { const a = [...document.querySelectorAll('.gr-answer')]; return a.length ? a[a.length - 1].innerText : '' });
  H.lastN = async (k = 2) => p.evaluate(k => { const a = [...document.querySelectorAll('.gr-answer')]; return a.slice(-k).map(x => x.innerText).join('\n-----\n') }, k);
  H.text = async (sel = '.app-main') => p.evaluate(s => document.querySelector(s)?.innerText || '', sel);
  H.btn = async (name, exact = false, scope) => { const base = scope ? p.locator(scope) : p; const l = base.getByRole('button', { name, exact }).last(); await l.scrollIntoViewIfNeeded(); await l.click(); await p.waitForTimeout(450) };
  H.state = async () => p.evaluate(m => JSON.parse(localStorage.getItem('gratifi-state-v3-' + m)), market);
  H.confirm = async (code = '482193') => { await p.waitForTimeout(300); const s = await p.$('.app-sheet'); if (!s) { errs.push('NO SHEET'); return false } const ins = await p.$$('.app-sheet input'); if (ins.length >= 6) { for (let i = 0; i < 6; i++) await ins[i].fill(code[i]) } else if (ins.length) await ins[0].fill(code); await p.locator('.app-sheet .gr-btn').last().click(); await p.waitForSelector('.app-sheet', { state: 'detached', timeout: 9000 }).catch(() => errs.push('SHEET STUCK')); await p.waitForTimeout(600); return true };
  H.pickItem = async (nth = 0) => { await p.locator('.gr-answer').last().locator('.gr-itemrow').nth(nth).click(); await p.waitForTimeout(450) };
  H.detailCta = async () => { const c = p.locator('.gr-answer').last().locator('.gr-detail .gr-btn').last(); await c.scrollIntoViewIfNeeded(); await c.click(); await p.waitForTimeout(450) };
  H.pay = async () => { const l = p.getByRole('button', { name: /^(Pay |ادفع )/ }).last(); await l.scrollIntoViewIfNeeded(); await l.click(); await p.waitForTimeout(300) };
  H.close = async () => { const e2 = await p.evaluate(() => window.__errs || []); if (errs.length || e2.length) console.log('ERRORS:', [...errs, ...e2].join(' | ').slice(0, 1500)); await b.close() };
  return H;
};
