const setup=require('./lib.js');
(async()=>{ const m=process.argv[2]||'UK'; const h=await setup(m,{tag:'a11y'}); const {p,nav,ask,full,lastText,log,btn,state,confirm,sheetText,shot}=h;
const audit = (tag)=>p.evaluate((tag)=>{ const un=[]; document.querySelectorAll('button,a,[role=button],[role=switch],[role=radio],[role=tab]').forEach(b=>{ const n=(b.getAttribute('aria-label')||b.textContent||'').trim(); const lb=b.getAttribute('aria-labelledby'); if(!n && !lb && b.offsetParent) un.push(b.className) }); const inp=[]; document.querySelectorAll('input,textarea,select').forEach(i=>{ const id=i.id; const lab=i.getAttribute('aria-label')||i.getAttribute('aria-labelledby')||(id&&document.querySelector(`label[for="${id}"]`))||i.closest('label'); if(!lab && i.offsetParent) inp.push(i.outerHTML.slice(0,120)) }); const live=[...document.querySelectorAll('[aria-live]')].map(e=>e.className+':'+e.getAttribute('aria-live')); const imgs=[...document.querySelectorAll('img')].filter(i=>!i.hasAttribute('alt')).length; const svg=[...document.querySelectorAll('svg')].filter(s=>!s.getAttribute('aria-hidden') && !s.getAttribute('role') && !s.closest('[aria-label]') && !s.closest('button')).length; return {tag, unnamed:un.slice(0,6), unlabelled:inp.slice(0,6), live, imgsNoAlt:imgs, svgExposed:svg, lang:document.documentElement.lang, dir:document.documentElement.dir, h1:[...document.querySelectorAll('h1,h2')].map(x=>x.tagName+':'+x.textContent.slice(0,20)).slice(0,5)} }, tag);
log(JSON.stringify(await audit('home')));
await nav(3); await ask('Flights to Lisbon on 16 Oct for two'); log(JSON.stringify(await audit('chat')));
await p.locator('.gr-flight').first().click(); await p.waitForTimeout(400); await btn(/Continue with/); log(JSON.stringify(await audit('seats')));
await p.locator('.gr-answer').last().locator('input.app-in').nth(1).fill('Sam Taylor'); await btn('Continue',{exact:true}); await btn(/^Pay /);
log(await p.evaluate(()=>{ const d=document.querySelector('[role=dialog]'); const a=document.activeElement; return JSON.stringify({dialog:!!d, modal:d?.getAttribute('aria-modal'), label:d?.getAttribute('aria-label')||d?.getAttribute('aria-labelledby'), focusInside: d?.contains(a), active:a?.outerHTML.slice(0,80)}) }));
for (let i=0;i<12;i++) await p.keyboard.press('Tab'); log('after tabs focus inside:', await p.evaluate(()=>document.querySelector('[role=dialog]')?.contains(document.activeElement)));
await p.keyboard.press('Escape'); await p.waitForTimeout(300); log('esc closes:', !(await p.$('[role=dialog]')), 'focus returned to:', await p.evaluate(()=>document.activeElement?.outerHTML.slice(0,80)));
await nav(4); log(JSON.stringify(await audit('wallet'))); await nav(5); log(JSON.stringify(await audit('me')));
await h.done() })()
