const L = require('./lib.js')
module.exports = async (h) => { const { p, nav, ask, click, full, last, shot, summ, lastText, log } = h
  await nav(3); await ask('Flights to Lisbon next weekend for two')
  await p.locator('.gr-flight').first().click(); await p.waitForTimeout(400); await click(/Continue with/); await click('Continue', true)
  await p.getByText('Card', { exact: true }).last().click().catch(e => log('no card radio')); await p.waitForTimeout(300)
  log('PAY:', await h.btn(/^Pay /).innerText()); await click(/^Pay /); await L.confirm(h); await last('booked'); await summ('booked')
  await nav(4); await full('wallet'); log('WALLET:', (await p.locator('.app-main').innerText()).replace(/\n/g,' | ').slice(0,1500))
  await click('Show pass').catch(e => log('no show pass')); await full('pass'); log('PASS:', (await p.locator('.app-main').innerText()).replace(/\n/g,' | ').slice(0,1500))
  await nav(3); await ask('change my flight'); await last('change-ask'); log('CHG:', (await lastText()).replace(/\n/g,' | '))
  await p.locator('.gr-answer').last().locator('.gr-slot').nth(1).click().catch(e=>log('no slot')); await p.waitForTimeout(300); await last('change-pick'); log('CHG2:', (await lastText()).replace(/\n/g,' | '))
  await p.locator('.gr-answer').last().locator('.gr-btn').last().click(); await p.waitForTimeout(600); await last('change-next'); log('CHG3:', (await lastText()).replace(/\n/g,' | '))
  if (await p.$('.app-sheet')) await L.confirm(h); else { const pay = p.getByRole('button', { name: /^Pay / }); if (await pay.count()) { await pay.last().click(); await L.confirm(h) } }
  await last('changed'); log('CHG4:', (await lastText()).replace(/\n/g,' | ')); await summ('after change')
  await ask('change my seat'); await last('seat-ask'); log('SEAT:', (await lastText()).replace(/\n/g,' | ').slice(0,600))
  const seats = p.locator('.gr-answer').last().locator('.gr-seat'); log('seats', await seats.count())
  await seats.nth(4).click().catch(()=>{}); await p.waitForTimeout(300); await last('seat-pick')
  await click('Save seats').catch(e => log('no save seats')); await p.waitForTimeout(400); if (await p.$('.app-sheet')) await L.confirm(h); await last('seat-saved'); log('SEAT2:', (await lastText()).replace(/\n/g,' | ').slice(0,600))
  await ask('cancel my flight'); await last('cancel-ask'); log('CAN:', (await lastText()).replace(/\n/g,' | '))
  await click('Yes, cancel').catch(e => log('no yes cancel')); await p.waitForTimeout(400); if (await p.$('.app-sheet')) await L.confirm(h); await last('cancelled'); log('CAN2:', (await lastText()).replace(/\n/g,' | ')); await summ('after cancel')
  log('yes-cancel still live:', await p.getByRole('button', { name: 'Yes, cancel' }).count())
  await p.getByRole('button', { name: 'Yes, cancel' }).first().click({ timeout: 2000 }).catch(e => log('first yes not clickable')); await p.waitForTimeout(500); if (await p.$('.app-sheet')) await L.confirm(h)
  await ask('cancel my flight'); await last('cancel-again'); log('CAN3:', (await lastText()).replace(/\n/g,' | ')); await summ('after 2nd cancel')
  await nav(4); await full('wallet-after')
  await nav(5); await full('me-after')
}
