module.exports = [
  'flights to Lisbon for my wife and me on 14 October',
  'flights to Lisbon 14 Oct to 18 Oct',
  'flights to Lisbon from Oct 14 to Oct 18',
  'Lisbon 14.10 - 18.10',
  'flights to Lisbon on 14/10/2026 back 18/10/2026',
  'flights to Lisbon Wednesday week',
  'flights to Lisbon in two weeks',
  'flights to Lisbon over half term',
  'flights to Lisbon at Christmas',
  'flights to Lisbon mid October for a week',
  'flights to Lisbon for a week from the 20th',
  'flights to Paris leaving around 3pm on Friday',
  'flights to Paris, 2 adults 1 child',
  'Paris for me and my two kids',
  'fly to paris with my mum and dad',
  'weekend in barcelona for the four of us',
  'can I get a flight to lisbon tomorrow',
  'flight to lisbon tonight',
  'flights to Lisbon on 30 September 2027',
  'return to Lisbon on the 3rd, come back on the 1st',
  '#reset',
  'Flights to Lisbon next weekend for two',
  'change it to three nights',
  'back on the 13th',
  'depart in the afternoon',
  'the 14:15 one',
  'actually just me',
  'what\'s the cheapest?',
  'is there wifi on board',
  'hotel there',
  'with breakfast',
  'for 4 nights',
  'cheaper',
  'book the first one',
  '#reset',
  'Table for 2 at 12:30 on Sunday',
  'table tonight at 9pm',
  'table at 1pm today',
  'lunch for 3 on saturday',
  'book Kanji for 4 on 3 October at 7pm',
  'dinner at 11:45pm tonight',
]
