const setup = require('./h.js')
;(async () => {
  const H = await setup('IN', { tag: 'IN-otp2', q: '&tab=chat' })
  const { p, ask, btn, shot, money, lastAnswer } = H
  // simulate expired lock
  await ask('hello')
  await p.evaluate(() => { const k = 'gratifi-state-v3-IN'; const s = JSON.parse(localStorage.getItem(k)); s.seen.otp = { n: 3, at: Date.now() - 16 * 60000 }; localStorage.setItem(k, JSON.stringify(s)) })
  await p.reload(); await p.waitForTimeout(600)
  const m0 = await money(); console.log('m0', m0)
  await ask('A hotel in Goa with a pool'); await lastAnswer().locator('.gr-itemrow').first().click(); await p.waitForTimeout(300); await lastAnswer().locator('.gr-detail .gr-btn').last().click(); await p.waitForTimeout(300)
  await p.getByRole('radio', { name: /^Card/ }).last().click(); await p.waitForTimeout(200); await shot('checkout-card', true)
  await btn(/^Pay /)
  console.log('after expiry', await p.evaluate(() => document.querySelector('.app-sheet')?.innerText))
  await p.locator('.app-sheet input').first().focus()
  await p.evaluate(() => { const el = document.activeElement; const dt = new DataTransfer(); dt.setData('text/plain', '482 193'); el.dispatchEvent(new ClipboardEvent('paste', { clipboardData: dt, bubbles: true, cancelable: true })) })
  await p.waitForTimeout(200); await shot('pasted')
  console.log('pasted values', await p.$$eval('.app-sheet input', xs => xs.map(x => x.value).join('')), 'focus', await p.evaluate(() => document.activeElement?.getAttribute('aria-label')))
  await p.keyboard.press('Enter'); await p.waitForTimeout(400); await shot('checking'); await p.waitForTimeout(2500); await shot('paid', true)
  console.log('money after pay', await money())
  const s = await H.S(); console.log('ledger', JSON.stringify(s.ledger.slice(0,4)), 'txn0', JSON.stringify(s.txns[0]))
  // points+card with typed code in a second checkout, backspace handling
  await ask('Noise-cancelling headphones'); await lastAnswer().locator('.gr-itemrow').first().click(); await p.waitForTimeout(300); await lastAnswer().locator('.gr-detail .gr-btn').last().click(); await p.waitForTimeout(300)
  await p.getByRole('radio', { name: /^Points and card/ }).last().click(); await p.waitForTimeout(200); await shot('mix', true)
  await btn(/^Pay /); await shot('mix-sheet')
  await p.keyboard.type('4821'); await p.keyboard.press('Backspace'); await p.keyboard.press('Backspace'); await p.waitForTimeout(100)
  console.log('after backspaces', await p.$$eval('.app-sheet input', xs => xs.map(x => x.value || '_').join('')), await p.evaluate(() => document.activeElement?.getAttribute('aria-label')))
  await p.keyboard.type('2193'); await p.waitForTimeout(100)
  console.log('after retype', await p.$$eval('.app-sheet input', xs => xs.map(x => x.value || '_').join('')))
  await shot('mix-typed')
  // Close during checking: click confirm and immediately Escape
  await p.locator('.app-sheet .gr-btn').last().click(); await p.waitForTimeout(300); await p.keyboard.press('Escape'); await p.waitForTimeout(2000)
  console.log('after esc during checking', await money(), 'sheet?', !!(await p.$('.app-sheet')))
  await shot('after-esc', true)
  await H.done()
})()
