const setup = require('./h.js')
;(async () => {
  const H = await setup('IN', { tag: 'IN-otp', q: '&tab=chat' })
  const { p, ask, btn, shot, money, lastAnswer, confirmSheet } = H
  console.log('start', await money())
  await ask('A hotel in Goa with a pool'); await shot('list', true)
  await lastAnswer().locator('.gr-itemrow').first().click(); await p.waitForTimeout(400); await shot('detail', true)
  await lastAnswer().locator('.gr-detail .gr-btn').last().click(); await p.waitForTimeout(400)
  // choose card
  await p.getByRole('button', { name: /^Card/ }).last().click().catch(e => console.log('no card opt', e.message)); await p.waitForTimeout(200)
  await shot('checkout', true)
  await btn(/^Pay /); await shot('sheet')
  const ins = p.locator('.app-sheet input')
  console.log('boxes', await ins.count(), 'focused aria', await p.evaluate(() => document.activeElement?.getAttribute('aria-label')))
  // wrong code typed then Enter
  await p.keyboard.type('111111'); await shot('typed-wrong'); await p.keyboard.press('Enter'); await p.waitForTimeout(400); await shot('wrong1')
  console.log('after wrong1', await money(), await p.evaluate(() => document.querySelector('.app-sheet')?.innerText))
  await p.keyboard.type('222222'); await p.keyboard.press('Enter'); await p.waitForTimeout(400); await shot('wrong2')
  console.log('after wrong2 sheet', await p.evaluate(() => document.querySelector('.app-sheet')?.innerText))
  // close by Escape and reload
  await p.keyboard.press('Escape'); await p.waitForTimeout(300); console.log('sheet after esc', !!(await p.$('.app-sheet')))
  await p.reload(); await p.waitForTimeout(600)
  await btn(/^Pay /); await p.waitForTimeout(300); await shot('reopen-after-reload')
  console.log('reopen sheet', await p.evaluate(() => document.querySelector('.app-sheet')?.innerText))
  await p.keyboard.type('333333'); await p.keyboard.press('Enter'); await p.waitForTimeout(400); await shot('locked')
  console.log('locked sheet', await p.evaluate(() => document.querySelector('.app-sheet')?.innerText))
  await p.keyboard.press('Escape'); await p.reload(); await p.waitForTimeout(600)
  await btn(/^Pay /); await p.waitForTimeout(300); await shot('locked-reload')
  console.log('locked after reload', await p.evaluate(() => document.querySelector('.app-sheet')?.innerText))
  console.log('money after lock', await money())
  // try other sensitive: bill payment during lock
  await p.keyboard.press('Escape'); await ask('pay my bill'); await btn(/^Pay /); await p.waitForTimeout(300)
  console.log('bill during lock', await p.evaluate(() => document.querySelector('.app-sheet')?.innerText))
  await shot('bill-locked')
  await p.keyboard.press('Escape')
  // Fast forward: set otp.at to 16 min ago
  await p.evaluate(() => { const k = 'gratifi-state-v3-IN'; const s = JSON.parse(localStorage.getItem(k)); s.seen.otp.at -= 16 * 60000; localStorage.setItem(k, JSON.stringify(s)) })
  await p.reload(); await p.waitForTimeout(600)
  await ask('A hotel in Goa with a pool'); await lastAnswer().locator('.gr-itemrow').first().click(); await p.waitForTimeout(300); await lastAnswer().locator('.gr-detail .gr-btn').last().click(); await p.waitForTimeout(300)
  await p.getByRole('button', { name: /^Card/ }).last().click(); await btn(/^Pay /)
  console.log('after expiry', await p.evaluate(() => document.querySelector('.app-sheet')?.innerText))
  // paste the code
  await p.locator('.app-sheet input').first().focus()
  await p.evaluate(() => { const el = document.activeElement; const dt = new DataTransfer(); dt.setData('text/plain', '482 193'); el.dispatchEvent(new ClipboardEvent('paste', { clipboardData: dt, bubbles: true, cancelable: true })) })
  await p.waitForTimeout(200); await shot('pasted')
  console.log('pasted values', await p.$$eval('.app-sheet input', xs => xs.map(x => x.value).join('')), 'focus', await p.evaluate(() => document.activeElement?.getAttribute('aria-label')))
  await p.keyboard.press('Enter'); await p.waitForTimeout(2500); await shot('paid', true)
  console.log('money after pay', await money())
  await H.tall('receipt-tall')
  await H.done()
})()
