const h=require('./h.js');(async()=>{const M=process.argv[2]||'UK';const H=await h.open(M,{tag:'a11y',theme:process.argv[3]||'light'});const {p}=H;
const audit=async(tag)=>{const r=await p.evaluate(()=>{
 const lum=c=>{const m=c.match(/[\d.]+/g).map(Number);const [r,g,b]=m.slice(0,3).map(v=>{v/=255;return v<=0.03928?v/12.92:Math.pow((v+0.055)/1.055,2.4)});return 0.2126*r+0.7152*g+0.0722*b};
 const bgOf=e=>{while(e){const c=getComputedStyle(e).backgroundColor;if(c&&!/rgba\(0, 0, 0, 0\)|transparent/.test(c)){const a=c.match(/[\d.]+/g);if(a.length<4||+a[3]>0.5)return c}e=e.parentElement}return 'rgb(255,255,255)'};
 const low=[];document.querySelectorAll('body *').forEach(e=>{if(!e.childNodes.length||![...e.childNodes].some(n=>n.nodeType===3&&n.textContent.trim()))return;const r=e.getBoundingClientRect();if(!r.width)return;const cs=getComputedStyle(e);if(cs.visibility==='hidden'||+cs.opacity<0.5)return;const L1=lum(cs.color),L2=lum(bgOf(e));const cr=(Math.max(L1,L2)+0.05)/(Math.min(L1,L2)+0.05);const big=parseFloat(cs.fontSize)>=24||(parseFloat(cs.fontSize)>=18.6&&+cs.fontWeight>=700);if(cr<(big?3:4.5))low.push(e.textContent.trim().slice(0,30)+' '+cr.toFixed(2)+' '+cs.color+' on '+bgOf(e))});
 const noName=[...document.querySelectorAll('button,a,[role=button],input,[role=switch]')].filter(b=>{const n=(b.getAttribute('aria-label')||b.innerText||b.getAttribute('title')||b.getAttribute('placeholder')||'').trim();const id=b.id&&document.querySelector('label[for="'+b.id+'"]');return !n&&!id&&!b.closest('label')&&b.getBoundingClientRect().width}).map(b=>b.outerHTML.slice(0,120));
 const small=[...document.querySelectorAll('button,[role=button],[role=switch],a')].filter(b=>{const r=b.getBoundingClientRect();return r.width&&(r.height<24||r.width<24)}).map(b=>(b.innerText||b.getAttribute('aria-label')||'').slice(0,20)+' '+Math.round(b.getBoundingClientRect().width)+'x'+Math.round(b.getBoundingClientRect().height));
 return {low:[...new Set(low)].slice(0,25),noName:noName.slice(0,10),small:small.slice(0,10),lang:document.documentElement.lang,dir:document.documentElement.dir}});console.log('==',tag,JSON.stringify(r,null,1))};
await audit('home');await H.nav(2);await audit('explore');await H.nav(5);await audit('me');await H.nav(4);await audit('wallet');await H.nav(3);
await H.ask('A hotel in Lisbon with a pool'); await p.locator('.gr-answer').last().locator('.gr-itemrow').first().click(); await p.waitForTimeout(300); await audit('detail'); await p.locator('.gr-answer').last().locator('.gr-detail .gr-btn').last().click(); await p.waitForTimeout(300); await audit('checkout');
await p.getByRole('button',{name:/^(Pay|ادفع)/}).last().click(); await p.waitForTimeout(500);
console.log(await p.evaluate(()=>{const d=document.querySelector('.app-sheet');const f=document.activeElement;return JSON.stringify({role:d?.getAttribute('role')||d?.closest('[role]')?.getAttribute('role'),modal:d?.getAttribute('aria-modal'),label:d?.getAttribute('aria-labelledby')||d?.getAttribute('aria-label'),focusInSheet:d?.contains(f),focus:f?.outerHTML.slice(0,80),inert:[...document.querySelectorAll('[inert]')].map(e=>e.className).slice(0,4)})}));
for(let i=0;i<8;i++) await p.keyboard.press('Tab'); console.log('after tabs focus in sheet', await p.evaluate(()=>document.querySelector('.app-sheet')?.contains(document.activeElement)));
await p.keyboard.press('Escape'); await p.waitForTimeout(300); console.log('closed', !(await p.$('.app-sheet')), await p.evaluate(()=>document.activeElement?.outerHTML.slice(0,80)));
console.log(H.errs);await H.close()})()
