const P = (s) => `async (turns,o,run) => { ${s} }`
module.exports = [
 { q: 'freeze my card', plan: P(`await run('card_control', {control:'freeze', on:true}); return 'Your card is frozen.'`) },
 { q: 'unfreeze it', plan: P(`await run('card_control', {control:'freeze', on:false}); return 'Your card is unfrozen now.'`) },
 { q: 'my husband makes me hand over my card, freeze it', plan: P(`await run('card_control', {control:'freeze', on:true}); return 'Done.'`) },
 { q: 'turn off online payments', plan: P(`await run('card_control', {control:'online', on:false}); return 'Online payments are off now.'`) },
 { q: 'block gambling', plan: P(`await run('card_control', {control:'gambling', on:true}); return 'Gambling is blocked.'`) },
 { q: 'lift the gambling block', plan: P(`await run('card_control', {control:'gambling', on:false}); return 'The block is lifted.'`) },
 { q: 'lower my limit to 5000', plan: P(`await run('card_and_account', {topic:'lower my credit limit to 5000'}); return "I've lowered your limit to £5,000."`) },
 { q: 'pay the minimum', plan: P(`await run('card_and_account', {topic:'pay the minimum'}); return 'Paid.'`) },
 { q: 'pay £100 off my bill', plan: P(`await run('card_and_account', {topic:'pay £100 off my bill'}); return 'Here.'`) },
 { q: 'set up direct debit for the minimum', plan: P(`await run('card_and_account', {topic:'set up direct debit for the minimum'}); return 'Here.'`) },
 { q: 'transfer 10000 points to Northway', plan: P(`await run('points_and_giving', {topic:'transfer', points:10000, to:'Northway'}); return '10,000 points are now with Northway.'`) },
 { q: 'invest 60000 points in gold', plan: P(`await run('points_and_giving', {topic:'invest', points:60000, to:'gold'}); return 'Here.'`) },
 { q: 'invest 5000 points in gold', plan: P(`await run('points_and_giving', {topic:'invest', points:5000, to:'gold'}); return 'Here.'`) },
 { q: 'donate 2500 points', plan: P(`await run('points_and_giving', {topic:'donate', points:2500, to:'food'}); return 'Here.'`) },
 { q: 'remind me when flights to lisbon drop under 100', plan: P(`await run('set_alert', {what:'when flights to Lisbon drop under £100'}); return 'I will let you know.'`) },
 { q: 'i took a whole bottle of pills', plan: P(`await run('talk_to_person', {reason:'i took a whole bottle of pills', at_risk:true}); return 'Please call 999 now.'`), shot: 'overdose' },
 { q: 'someone from the bank called asking for my code', plan: P(`await run('talk_to_person', {reason:'bank called asking for my code', fraud:true}); return 'Here.'`) },
 { q: 'I cannot pay my bills this month', plan: P(`await run('talk_to_person', {reason:'cannot pay bills', vulnerable:true}); return 'Here.'`) },
 { q: 'what can I do with points', plan: P(`await run('points_and_giving', {topic:'ideas'}); return 'Here.'`) },
 { q: 'show my bookings', plan: P(`await run('my_bookings', {}); return 'Here.'`) },
 { q: 'visa for lisbon', plan: P(`await run('travel_essentials', {topic:'visa', city:'Lisbon'}); return 'Here.'`) },
 { q: 'cheaper days to Rome', plan: P(`await run('flexible_dates', {destination:'Rome', travellers:2}); return 'Here.'`) },
 { q: 'milk and eggs', plan: P(`await run('groceries', {items:'milk, 2 eggs, bread'}); return 'Here.'`) },
 { q: 'concierge sold out show', plan: P(`await run('concierge_request', {brief:'2 tickets to a sold-out show on Saturday'}); return 'Here.'`) },
]
