const P = (s) => `async (turns,o,run) => { ${s} }`
module.exports = [
 { q: 'table for 2 at Kanji tonight 8pm', plan: P(`await run('prepare_checkout', {id:'DN-London-3', quantity:2, option:'20:00'}); return "I've booked your table at Kanji for 8pm. You're all set."`) },
 { q: 'table for 14 at Kanji saturday', plan: P(`await run('prepare_checkout', {id:'DN-London-3', quantity:14, date:'2026-10-03', option:'20:00'}); return 'Here is your table.'`) },
 { q: 'table for 13 at Kanji saturday', plan: P(`await run('show_item', {id:'DN-London-3', guests:13}); return 'Here it is.'`) },
 { q: 'table for 0', plan: P(`await run('prepare_checkout', {id:'DN-London-3', quantity:0, option:'20:00'}); return 'Here.'`) },
 { q: 'table at 3am', plan: P(`await run('prepare_checkout', {id:'DN-London-3', quantity:2, option:'03:00'}); return 'Here.'`) },
 { q: 'table yesterday', plan: P(`await run('prepare_checkout', {id:'DN-London-3', quantity:2, date:'2026-09-29', option:'20:00'}); return 'Here.'`) },
 { q: 'hotel lisbon 45 nights', plan: P(`await run('prepare_checkout', {id:'ST-Lisbon-0', nights:45, date:'2026-10-10'}); return 'Here.'`) },
 { q: 'hotel lisbon 2.5 nights', plan: P(`await run('prepare_checkout', {id:'ST-Lisbon-0', nights:2.5, date:'2026-10-10'}); return 'Here.'`) },
 { q: 'hotel lisbon 5 guests 1 room', plan: P(`await run('prepare_checkout', {id:'ST-Lisbon-0', nights:2, quantity:5, rooms:1, date:'2026-10-10'}); return 'Here.'`) },
 { q: 'hotel lisbon suite for 4 nights for 3 people', plan: P(`await run('prepare_checkout', {id:'ST-Lisbon-0', nights:4, quantity:3, option:'Suite', date:'2026-10-10'}); return 'Here.'`) },
 { q: 'gift card no email', plan: P(`await run('prepare_checkout', {id:'GC-1', option:'50', recipient:'Sam'}); return 'Here.'`) },
 { q: 'gift card bad email', plan: P(`await run('prepare_checkout', {id:'GC-1', option:'50', recipient:'Sam', email:'sam@'}); return 'Here.'`) },
 { q: 'gift card 37 pounds', plan: P(`await run('prepare_checkout', {id:'GC-1', option:'37', recipient:'Sam', email:'sam@example.com'}); return 'Here.'`) },
 { q: 'gift card 50 for sam', plan: P(`await run('prepare_checkout', {id:'GC-1', option:'50', recipient:'Sam', email:'sam@example.com'}); return 'Your gift card has been sent to Sam.'`) },
 { q: 'jacket no size', plan: P(`await run('prepare_checkout', {id:'SH-4'}); return 'Here.'`) },
 { q: 'jacket size XXXL', plan: P(`await run('prepare_checkout', {id:'SH-4', option:'XXXL'}); return 'Here.'`) },
 { q: 'jacket size M qty 500', plan: P(`await run('prepare_checkout', {id:'SH-4', option:'M', quantity:500}); return 'Here.'`) },
 { q: 'lounge for 5', plan: P(`await run('prepare_checkout', {id:'AP-1', quantity:5}); return 'Here.'`) },
 { q: 'ride to heathrow at 6am tomorrow', plan: P(`await run('prepare_checkout', {id:'GT-1', destination:'Heathrow', date:'2026-10-01', pickup_time:'06:00'}); return 'Here.'`) },
 { q: 'ride at 9am today', plan: P(`await run('prepare_checkout', {id:'GT-1', destination:'office', date:'2026-09-30', pickup_time:'09:00'}); return 'Here.'`) },
 { q: 'ride at 25:99', plan: P(`await run('prepare_checkout', {id:'GT-1', destination:'office', pickup_time:'25:99'}); return 'Here.'`) },
 { q: 'car hire 4 days', plan: P(`await run('prepare_checkout', {id:'GT-4', days:4}); return 'Here.'`) },
 { q: 'car hire 3 days', plan: P(`await run('prepare_checkout', {id:'GT-4', days:3}); return 'Here.'`) },
 { q: 'train to edinburgh 3 people', plan: P(`await run('prepare_checkout', {id:'GT-6', quantity:3, date:'2026-10-02'}); return 'Here.'`) },
 { q: 'cinema 2 for 1, 3 people', plan: P(`await run('prepare_checkout', {id:'ET-4', quantity:3}); return 'Here.'`) },
 { q: 'cinema 2 for 1, next month', plan: P(`await run('prepare_checkout', {id:'ET-4', quantity:2, date:'2026-10-20'}); return 'Here.'`) },
 { q: 'arlo grey 2 tickets on the 25th', plan: P(`await run('prepare_checkout', {id:'ET-1', quantity:2, date:'2026-10-25'}); return 'Here.'`) },
 { q: 'subscribe screenly', plan: P(`await run('prepare_checkout', {id:'SB-1'}); return 'Screenly is now active.'`) },
 { q: 'laptop 9 of them', plan: P(`await run('prepare_checkout', {id:'SH-3', quantity:9}); return 'Here.'`) },
 { q: 'invented id', plan: P(`await run('prepare_checkout', {id:'SH-99'}); return 'Here.'`) },
 { q: 'flight checkout via prepare', plan: P(`const s = await run('search_flights', {destination:'Lisbon', depart_date:'2026-10-09', travellers:2}); await run('prepare_checkout', {id: s.data?.options?.[0]?.id || 'FL-1'}); return 'Here.'`) },
]
