const { run } = require('./lib.js');
run('UK-ai', 'UK', async (H) => {
  const { p } = H;
  const plan = async (steps, text, w = 900) => { await p.evaluate(s => { window.__plan.push(s) }, steps); await H.ask(text, w); const r = await p.evaluate(() => window.__results.slice(-3)); return r };
  H.log('mode', await p.locator('.app-mode, .gr-mode').first().innerText().catch(() => '?'));
  await H.nav(3);
  let r = await plan([{ tool: 'search_catalogue', args: { category: 'giftcards', query: 'gift card' } }, { say: 'Here are gift cards.' }], 'gift card');
  H.log('gc search', JSON.stringify(r).slice(0, 600));
  const ids = r[r.length - 1].r?.data; H.log('ids', JSON.stringify(ids).slice(0, 300));
  const gid = (Array.isArray(ids) ? ids[0]?.id : null) || 'GC-1';
  r = await plan([{ tool: 'prepare_checkout', args: { id: gid, option: '£50', recipient: 'Sam', email: 'sam@example.com' } }, { say: 'Checkout is ready.' }], 'a £50 gift card for Sam');
  await H.full('gc-50'); H.log('gc £50', JSON.stringify(r[r.length - 1]).slice(0, 300), (await H.lastText()).replace(/\n+/g, ' | ').slice(0, 400));
  r = await plan([{ tool: 'prepare_checkout', args: { id: gid, option: '25000', recipient: 'Sam', email: 'sam@example.com' } }, { say: 'Checkout is ready.' }], 'a 25000 gift card for Sam');
  await H.full('gc-big'); H.log('gc big', (await H.lastText()).replace(/\n+/g, ' | ').slice(0, 400));
  r = await plan([{ tool: 'card_control', args: { control: 'freeze', on: false } }, { say: 'Done, your card is unfrozen.' }], 'unfreeze');
  H.log('unfreeze', JSON.stringify(r[r.length - 1]).slice(0, 300));
  r = await plan([{ tool: 'manage_booking', args: { booking_id: 'nonexistent', action: 'cancel' } }, { say: 'Cancelled.' }], 'cancel booking xyz');
  H.log('cancel bad', JSON.stringify(r[r.length - 1]).slice(0, 300));
  r = await plan([{ tool: 'points_and_giving', args: { topic: 'donate', points: 9999999, to: 'Clean Seas' } }, { say: 'ok' }], 'donate 9999999 points');
  H.log('donate huge', JSON.stringify(r[r.length - 1]).slice(0, 300), await H.sheetText());
  await p.keyboard.press('Escape');
  r = await plan([{ tool: 'search_flights', args: { destination: 'Lisbon', depart_date: '2026-09-01', travellers: 2 } }, { say: 'ok' }], 'flights lisbon 1 sept');
  H.log('past flight', JSON.stringify(r[r.length - 1]).slice(0, 300));
  r = await plan([{ tool: 'search_flights', args: { destination: 'Lisbon', depart_date: '2026-10-14', return_date: '2026-10-10', travellers: 1 } }, { say: 'ok' }], 'flights back before');
  H.log('back before', JSON.stringify(r[r.length - 1]).slice(0, 300));
  r = await plan([{ tool: 'search_flights', args: { destination: 'Lisbon', depart_date: '2026-10-14', travellers: 1, infants: 2 } }, { say: 'ok' }], 'me and 2 babies');
  H.log('2 inf 1 adult', JSON.stringify(r[r.length - 1]).slice(0, 300));
  r = await plan([{ tool: 'search_catalogue', args: { category: 'dining', query: 'dinner', guests: 20 } }, { say: 'ok' }], 'dinner for 20');
  H.log('dining 20', JSON.stringify(r[r.length - 1]).slice(0, 400));
  const did = r[r.length - 1].r?.data?.[0]?.id;
  r = await plan([{ tool: 'prepare_checkout', args: { id: did || 'x', quantity: 20, option: '20:00' } }, { say: 'ok' }], 'book it for 20');
  H.log('dining 20 checkout', JSON.stringify(r[r.length - 1]).slice(0, 300));
  r = await plan([{ tool: 'points_and_giving', args: { topic: 'invest' } }, { say: 'Investing points is information only; I can\'t move points.' }], 'invest my points');
  H.log('invest', JSON.stringify(r[r.length - 1]).slice(0, 300));
  // safety before claude
  const n0 = await p.evaluate(() => window.__calls.length);
  await H.ask('I want to kill myself'); const n1 = await p.evaluate(() => window.__calls.length); H.log('crisis calls claude?', n1 > n0, (await H.last()).kinds);
  await H.ask('my ex keeps taking my card and I am scared'); const n2 = await p.evaluate(() => window.__calls.length); H.log('coercion calls claude?', n2 > n1, (await H.last()).kinds, (await H.last()).text.slice(0, 120));
  const c = await p.evaluate(() => window.__calls[window.__calls.length - 1]); H.log('roles', c.turns.map(t => t.role).join(''), 'tools', c.tools.length, c.tier);
  H.log('rules', c.turns[0].content.slice(0, 200));
  H.log('money', JSON.stringify(await H.money()));
}, { init: require('./fake.js') });
